force-app/main/default/objects/FieloPLT__Action__c/FieloPLT__Action__c.object-meta.xml
<CustomObject>
    <description>Action comprises an Object (either a Salesforce standard or a custom object) and a Member (either an Individual, Organization or Organization Contributor).</description>
    <label>Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Transaction__c/FieloPLT__Transaction__c.object-meta.xml
<CustomObject>
    <description>Transactions are the result of performing specific activities, which in exchange grant Points, Badges or Rewards to Members.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Transaction__c/fields/FieloPLT__Action__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Automatically generated related Action.</description>
    <inlineHelpText>Related Action.</inlineHelpText>
    <label>Action</label>
    <referenceTo>FieloPLT__Action__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Transaction__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Transaction Points.</description>
    <inlineHelpText>Enter the number of Transaction Points.</inlineHelpText>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Transaction__c/fields/FieloPLT__Type__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Type__c</fullName>
    <description>Different kind of Transactions which depend on their purpose: Adjustment, Challenge Reward, Expiration and Reversion</description>
    <inlineHelpText>Transaction type (Adjustment, Challenge Reward, Expiration and Reversion).</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Challenge Reward</fullName>
            </value>
            <value>
                <fullName>Expiration</fullName>
            </value>
            <value>
                <fullName>Reversion</fullName>
            </value>
            <value>
                <fullName>Betcoins Extra - Cortesia</fullName>
            </value>
            <value>
                <fullName>Youbet Extra - Fornecedor - Elegível H1 &gt;= 80%</fullName>
            </value>
            <value>
                <fullName>Elegibilidade - % AM YTD - AGO 18 &gt;= 100% - DISTR</fullName>
            </value>
            <value>
                <fullName>Elegibilidade - % AM YTD - SET 18 &gt;= 100% - DISTR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Transaction__c/fields/V_MetaDoParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_MetaDoParticipante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nova estrutura - Relaciona o registro de ano fiscal do objeto Meta do Participante à transação que gerou pontos.</description>
    <inlineHelpText>Relaciona o registro de ano fiscal do objeto Meta do Participante à transação que gerou pontos.</inlineHelpText>
    <label>Meta do Participante</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipLabel>Transações</relationshipLabel>
    <relationshipName>Transa_es</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_TotalBetcoins__c.field-meta.xml
<CustomField>
    <fullName>V_TotalBetcoins__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Betcoins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SX_Transaction_After.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 01/02/2019
* 
* Name: SX_Transaction_After.cls
* 
* Classe para disparar ações after em FieloPLT__Transaction__c
*
* Ações:
* 1 - sumarizar total de pontos nas metas
*******************************************************************************/
public with sharing class SX_Transaction_After {

	@TestVisible final public static String EXPIRATION = 'Expiration';

	public static void execute() {

		VN_TriggerCheck.assert();

		List<FieloPLT__Transaction__c> lLstTrigger = (List<FieloPLT__Transaction__c>) (trigger.isDelete ? trigger.old : trigger.new);

		Set<Id> lSetMetas = new Set<Id>();
		List<FieloPLT__Transaction__c> lLstTrans = new List<FieloPLT__Transaction__c>();
		for(FieloPLT__Transaction__c trans: lLstTrigger){

			if( (trans.FieloPLT__Action__c != null || trans.FieloPLT__Type__c != EXPIRATION )
				&& (VN_TriggerCheck.isChanged(trans, FieloPLT__Transaction__c.V_MetaDoParticipante__c) || trigger.isDelete) ){

				if(trans.V_MetaDoParticipante__c != null) lSetMetas.add(trans.V_MetaDoParticipante__c);

				// se deixou de ter meta, guarda meta antiga para recálculo
				if(trigger.isUpdate && VN_TriggerCheck.isChanged(trans, FieloPLT__Transaction__c.V_MetaDoParticipante__c) 
					&& ((FieloPLT__Transaction__c)trigger.oldMap.get( trans.id )).V_MetaDoParticipante__c != null){
					lSetMetas.add(((FieloPLT__Transaction__c)trigger.oldMap.get( trans.id )).V_MetaDoParticipante__c);
				}
				
				lLstTrans.add(trans);
			}
		}

		// atualiza campos "totais" das metas
		if(!lSetMetas.isEmpty()){

			Map<Id, VN_MetaParticipante__c> lMapMeta = new Map<Id, VN_MetaParticipante__c>([SELECT Id, 
				V_TotalBetcoins__c FROM VN_MetaParticipante__c WHERE Id =: lSetMetas]);


			for(FieloPLT__Transaction__c trans: lLstTrans){

				if(lMapMeta.containsKey(trans.V_MetaDoParticipante__c)){
					VN_MetaParticipante__c lMeta = lMapMeta.get(trans.V_MetaDoParticipante__c);

					if(lMeta.V_TotalBetcoins__c == null) lMeta.V_TotalBetcoins__c = 0;

					Decimal lPoint = trans.FieloPLT__Points__c != null ? trans.FieloPLT__Points__c : 0;

					if(trigger.isInsert || trigger.isUpdate){

						lMeta.V_TotalBetcoins__c += lPoint;

						//desconta da meta antiga
						if(trigger.isUpdate && VN_TriggerCheck.isChanged(trans, FieloPLT__Transaction__c.V_MetaDoParticipante__c) 
							&& ((FieloPLT__Transaction__c)trigger.oldMap.get( trans.id )).V_MetaDoParticipante__c != null){

							if(lMapMeta.containsKey(((FieloPLT__Transaction__c)trigger.oldMap.get( trans.id )).V_MetaDoParticipante__c)){
								VN_MetaParticipante__c lMetaOld = lMapMeta.get(((FieloPLT__Transaction__c)trigger.oldMap.get( trans.id )).V_MetaDoParticipante__c);

								if(lMetaOld.V_TotalBetcoins__c == null) lMetaOld.V_TotalBetcoins__c = 0;
								lMetaOld.V_TotalBetcoins__c -= lPoint;
							}
						}

					} else if(trigger.isDelete){
						lMeta.V_TotalBetcoins__c -= lPoint;
					}
				}
			}

			if(!lMapMeta.isEmpty()) update lMapMeta.values();
		}
	}
}