force-app/main/default/objects/FieloPLT__Action__c/FieloPLT__Action__c.object-meta.xml
<CustomObject>
    <description>Action comprises an Object (either a Salesforce standard or a custom object) and a Member (either an Individual, Organization or Organization Contributor).</description>
    <label>Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Action__c/fields/FieloPLT__RuleTrigger__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__RuleTrigger__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Action Engine Trigger.</description>
    <inlineHelpText>Choose an Engine Trigger related to the Action.</inlineHelpText>
    <label>Engine Trigger</label>
    <referenceTo>FieloPLT__RuleTrigger__c</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Member&apos;s points.</description>
    <inlineHelpText>Member&apos;s points.</inlineHelpText>
    <label>Points</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program that the Member belongs to.</description>
    <inlineHelpText>The Program that the Member belongs to</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Type__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Type__c</fullName>
    <description>The type of Member: Individual (physical person or sole proprietorship), Organization Contributor Member (physical person contributing to an organization) or Organization Member (a company or entity).</description>
    <inlineHelpText>Choose what kind of Member this is: Individual (physical person or sole proprietorship), Organization Contributor Member (physical person contributing to an organization) or Organization Member (a company or entity).</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual Account</fullName>
                <default>true</default>
                <label>Individual Member</label>
            </value>
            <value>
                <fullName>Organization Account</fullName>
                <label>Organization Member</label>
            </value>
            <value>
                <fullName>Organization Contributor</fullName>
                <label>Organization Contributor Member</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Saldo de betcoins (extras) do participante.Saldo de pontos gerado pela iniciativa Youbet Complementar.</description>
    <inlineHelpText>Saldo de betcoins (extras) do participante.Saldo de pontos gerado pela iniciativa Youbet Complementar.</inlineHelpText>
    <label>Betcoins - Extra</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_MetasAnoFiscalVigenteNovo__c.field-meta.xml
<CustomField>
    <fullName>V_MetasAnoFiscalVigenteNovo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Exibe a identificação do ano fiscal vigente do participante.</description>
    <inlineHelpText>Exibe a identificação do ano fiscal vigente do participante.</inlineHelpText>
    <label>Metas do Ano Fiscal Vigente</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipLabel>Participantes</relationshipLabel>
    <relationshipName>Participantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Program__c/FieloPLT__Program__c.object-meta.xml
<CustomObject>
    <description>Programs establish the general operation settings for your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Promotion__c/FieloPLT__Promotion__c.object-meta.xml
<CustomObject>
    <description>Promotions is a way of encouraging Members to behave in a particular way so as to drive their engagement.</description>
    <label>Promotion</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Promotion__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Program that the Promotion belongs to.</description>
    <inlineHelpText>This is the Program you&apos;re implementing the Promotion in.</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RuleTrigger__c/FieloPLT__RuleTrigger__c.object-meta.xml
<CustomObject>
    <description>Action Trigger underlays Actions and evaluate the conditions that the chosen object needs to fulfill so as to define when an Action Trigger must process a record.</description>
    <label>Action Trigger</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Transaction__c/FieloPLT__Transaction__c.object-meta.xml
<CustomObject>
    <description>Transactions are the result of performing specific activities, which in exchange grant Points, Badges or Rewards to Members.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Transaction__c/fields/FieloPLT__Action__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Automatically generated related Action.</description>
    <inlineHelpText>Related Action.</inlineHelpText>
    <label>Action</label>
    <referenceTo>FieloPLT__Action__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Transaction__c/fields/FieloPLT__Member__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>It shows the Member who generated the Transaction.</description>
    <inlineHelpText>Enter the Member who generated the Transaction.</inlineHelpText>
    <label>Member</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Transaction__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Transaction Points.</description>
    <inlineHelpText>Enter the number of Transaction Points.</inlineHelpText>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Transaction__c/fields/FieloPLT__Type__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Type__c</fullName>
    <description>Different kind of Transactions which depend on their purpose: Adjustment, Challenge Reward, Expiration and Reversion</description>
    <inlineHelpText>Transaction type (Adjustment, Challenge Reward, Expiration and Reversion).</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Challenge Reward</fullName>
            </value>
            <value>
                <fullName>Expiration</fullName>
            </value>
            <value>
                <fullName>Reversion</fullName>
            </value>
            <value>
                <fullName>Betcoins Extra - Cortesia</fullName>
            </value>
            <value>
                <fullName>Youbet Extra - Fornecedor - Elegível H1 &gt;= 80%</fullName>
            </value>
            <value>
                <fullName>Elegibilidade - % AM YTD - AGO 18 &gt;= 100% - DISTR</fullName>
            </value>
            <value>
                <fullName>Elegibilidade - % AM YTD - SET 18 &gt;= 100% - DISTR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Transaction__c/fields/V_MetaDoParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_MetaDoParticipante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nova estrutura - Relaciona o registro de ano fiscal do objeto Meta do Participante à transação que gerou pontos.</description>
    <inlineHelpText>Relaciona o registro de ano fiscal do objeto Meta do Participante à transação que gerou pontos.</inlineHelpText>
    <label>Meta do Participante</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipLabel>Transações</relationshipLabel>
    <relationshipName>Transa_es</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/VN_GerenciadorMetaParticipanteAF__c.object-meta.xml
<CustomObject>
    <description>Gerenciador dos registros de metas dos participantes por Ano Fiscal.</description>
    <label>Gerenciador Meta Participante AF</label>
    <nameField>
        <displayFormat>GMAF-{000000}</displayFormat>
        <label>No. Gerenciador Ano Fiscal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gerenciador Metas Participantes AF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_TotalBetcoins__c.field-meta.xml
<CustomField>
    <fullName>V_TotalBetcoins__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Betcoins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SX_Transaction_AfterTest.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                date: 04/02/2019
*
* 
* Name: SX_Transaction_AfterTest.cls
* 
* Classe de testes para da SX_Transaction_After.cls
*******************************************************************************/

@isTest
public with sharing class SX_Transaction_AfterTest {

	static testMethod void testFuncional(){

		FieloPLT__Program__c lProg = SObjectForTest.getProgram('Test');
		insert lProg;

		FieloPLT__Member__c lMember = SObjectForTest.getMember(lProg.Id);
		insert lMember;

		VN_GerenciadorMetaParticipanteAF__c lGerenciador = SObjectForTest.getGerenciadorMetaParticipante();
		insert lGerenciador;

		VN_MetaParticipante__c lMeta = SObjectForTest.getMetasNovaEstrutura(lMember.Id, lGerenciador.Id, Label.V_AnoFiscal);
		insert lMeta;

		VN_MetaParticipante__c lMeta2 = SObjectForTest.getMetasNovaEstrutura(lMember.Id, lGerenciador.Id, 'FY20');
		insert lMeta2;

		lMember.V_MetasAnoFiscalVigenteNovo__c = lMeta.Id;
		update lMember;

		FieloPLT__Promotion__c lPromotion = SObjectForTest.getPromotion(lProg.Id);
		insert lPromotion;

		FieloPLT__RuleTrigger__c lRuleTrgg = SObjectForTest.getRuleTrigger();
		insert lRuleTrgg;

		FieloPLT__Action__c lAction = SObjectForTest.getAction(lRuleTrgg.Id);
		insert lAction;

		List<FieloPLT__Transaction__c> lLstTransaction = new List<FieloPLT__Transaction__c>();

		FieloPLT__Transaction__c lTrs = SObjectForTest.getTransaction(lMember.Id);
		lTrs.FieloPLT__Action__c = lAction.Id;
			lLstTransaction.add(lTrs);

		FieloPLT__Transaction__c lTrs2 = SObjectForTest.getTransaction(lMember.Id);
		lTrs2.FieloPLT__Action__c = lAction.Id;
		lTrs2.V_BetcoinsComp__c = 5;
		lTrs2.FieloPLT__Points__c = 0;
		lLstTransaction.add(lTrs2);

		FieloPLT__Transaction__c lTrs3 = SObjectForTest.getTransaction(lMember.Id);
		lTrs3.FieloPLT__Type__c = SX_Transaction_After.EXPIRATION;
		lTrs3.V_BetcoinsComp__c = 5;
		lLstTransaction.add(lTrs3);

		FieloPLT__Transaction__c lTrs4 = SObjectForTest.getTransaction(lMember.Id);
		lTrs4.FieloPLT__Type__c = 'Adjustment';
		lLstTransaction.add(lTrs4);

		Test.startTest();
			insert lLstTransaction;     
		Test.stopTest();

		//INSERT
		Map<Id,VN_MetaParticipante__c> lMapMetaResultInsert = new Map<Id,VN_MetaParticipante__c>([SELECT Id, 
			V_TotalBetcoins__c FROM VN_MetaParticipante__c]);

		System.assertEquals(lTrs.FieloPLT__Points__c + lTrs4.FieloPLT__Points__c, lMapMetaResultInsert.get(lMeta.Id).V_TotalBetcoins__c); //perene
		//System.assertEquals(lTrs2.V_BetcoinsComp__c, lMapMetaResultInsert.get(lMeta.Id).V_TotalBetcoinsCompAF__c); //extra
		System.assertEquals(0, lMapMetaResultInsert.get(lMeta2.Id).V_TotalBetcoins__c); //perene meta 2
		//System.assertEquals(0, lMapMetaResultInsert.get(lMeta2.Id).V_TotalBetcoinsCompAF__c); //extra meta 2

		// UPDATE
		lTrs2.V_MetaDoParticipante__c = lMeta2.Id;
		update lTrs2;

		Map<Id,VN_MetaParticipante__c> lMapMetaResultUpdate =  new Map<Id,VN_MetaParticipante__c>([SELECT Id, 
			V_TotalBetcoins__c FROM VN_MetaParticipante__c]);

		System.assertEquals(lTrs.FieloPLT__Points__c + lTrs4.FieloPLT__Points__c, lMapMetaResultUpdate.get(lMeta.Id).V_TotalBetcoins__c); //perene
		//System.assertEquals(0, lMapMetaResultUpdate.get(lMeta.Id).V_TotalBetcoinsCompAF__c); //extra
		System.assertEquals(0, lMapMetaResultUpdate.get(lMeta2.Id).V_TotalBetcoins__c); //perene meta 2
		//System.assertEquals(lTrs2.V_BetcoinsComp__c, lMapMetaResultUpdate.get(lMeta2.Id).V_TotalBetcoinsCompAF__c); //extra meta 2

		//DELETE
		delete lLstTransaction; 

		Map<Id,VN_MetaParticipante__c> lMapMetaResultDelete = new  Map<Id,VN_MetaParticipante__c>([SELECT Id, 
			V_TotalBetcoins__c FROM VN_MetaParticipante__c]);

		System.assertEquals(0, lMapMetaResultDelete.get(lMeta.Id).V_TotalBetcoins__c); //perene
		//System.assertEquals(0, lMapMetaResultDelete.get(lMeta.Id).V_TotalBetcoinsCompAF__c); //extra
		System.assertEquals(0, lMapMetaResultDelete.get(lMeta2.Id).V_TotalBetcoins__c); //perene meta 2
		//System.assertEquals(0, lMapMetaResultDelete.get(lMeta.Id).V_TotalBetcoinsCompAF__c); //extra meta 2
	}
}