force-app/main/default/objects/VN_Resultado__c/VN_Resultado__c.object-meta.xml
<CustomObject>
    <description>Armazena as vendas mês a mês por ano fiscal.</description>
    <label>Resultado</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>No. Resultado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resultados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_Resultado__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <description>Ano fiscal relacionado à meta do participante. Por exemplo: FY19</description>
    <inlineHelpText>Ano fiscal relacionado à meta do participante. Por exemplo: FY19</inlineHelpText>
    <label>Ano Fiscal</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VN_ResultadoTest.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: LK                date: 02/11/2018
*
* 
* Name: VN_ResultadoTest.cls
* 
* Classe de testes para a trigger VN_Resultado
*******************************************************************************/
@isTest(SeeAllData=true) 
public with sharing class VN_ResultadoTest {
	static testMethod void processarCalculos(){
	
        
        VN_Resultado__c lRes = [SELECT Id, V_AnoFiscal__c FROM VN_Resultado__c limit 1];
        lRes.V_AnoFiscal__c = 'FY00';
            
		Test.startTest();  
        update lRes;
        Test.stopTest();	
	}
}