force-app/main/default/objects/FieloPLT__Agreement__c/FieloPLT__Agreement__c.object-meta.xml
<CustomObject>
    <description>Terms and conditions of service that Members need to accept in order to be part of the loyalty Program in which you wish to include them.</description>
    <label>Agreement</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Version</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Agreement__c/fields/FieloPLT__Agreement__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Agreement__c</fullName>
    <description>Agreement terms and conditions.</description>
    <inlineHelpText>Enter the Agreement terms and conditions.</inlineHelpText>
    <label>Agreement</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Agreement__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It shows the Program which the Agreement belongs to.</description>
    <inlineHelpText>Choose the Program which the Agreement belongs to.</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Agreement__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Agreement status: Draft, Current, Active or Deprecated.</description>
    <inlineHelpText>Agreement status: Draft, Current, Active or Deprecated.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Agreement__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Agreement.</description>
    <inlineHelpText>Related Agreement.</inlineHelpText>
    <label>Agreement</label>
    <referenceTo>FieloPLT__Agreement__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program that the Member belongs to.</description>
    <inlineHelpText>The Program that the Member belongs to</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</description>
    <inlineHelpText>Choose Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Program__c/FieloPLT__Program__c.object-meta.xml
<CustomObject>
    <description>Programs establish the general operation settings for your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Program__c/fields/V_RegulamentoElite__c.field-meta.xml
<CustomField>
    <fullName>V_RegulamentoElite__c</fullName>
    <description>Utilizado para a inclusão do regulamento da iniciativa Elite.</description>
    <inlineHelpText>Utilizado para a inclusão do regulamento da iniciativa Elite.</inlineHelpText>
    <label>Regulamento Elite</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Program__c/fields/V_RegulamentoSPY__c.field-meta.xml
<CustomField>
    <fullName>V_RegulamentoSPY__c</fullName>
    <description>Utilizado para a inclusão do regulamento da iniciativa SPY.</description>
    <inlineHelpText>Utilizado para a inclusão do regulamento da iniciativa SPY.</inlineHelpText>
    <label>Regulamento SPY</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/FieloPLT__Reward__c.object-meta.xml
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Reward__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Program that the Reward is associated with.</description>
    <inlineHelpText>The Program in which you&apos;ll use this Reward</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SX_AgreementController.cls
public without sharing class SX_AgreementController {

	@AuraEnabled
    public static FieloPLT__Member__c getMember() {
        List<FieloPLT__Member__c> lMemberLst = [SELECT Id, FieloPLT__Program__c, FieloPLT__Program__r.V_RegulamentoElite__c,
                        FieloPLT__Program__r.V_RegulamentoSPY__c,  FieloPLT__Agreement__c
	                FROM FieloPLT__Member__c
	                WHERE FieloPLT__User__c =: UserInfo.getUserId()];

	    return lMemberLst.isEmpty() ? null : lMemberLst[0];         
    }
    
    @AuraEnabled
    public static FieloPLT__Reward__c getRewardAgreement(String aMemberId, String aType){
        String lIniciativa;
        if (aType == 'youbet') {
            lIniciativa = Label.V_IniciativaPerene;
        } else if (aType == 'youbet-extra') {
            lIniciativa = Label.V_IniciativaComplementar;
        }
        return SX_RewardServices.getReward(aMemberId, lIniciativa);
	}

	@AuraEnabled
    public static FieloPLT__Agreement__c getAgreement(String aIdProgram){

    	FieloPLT__Agreement__c lAgreement;
        try{
            lAgreement = FieloPLT.AgreementService.getCurrentAgreement(aIdProgram, new Set<String>{'Id', 'FieloPLT__Status__c', 'FieloPLT__Agreement__c'});

    	} catch (Exception e) {
    		system.debug('### error getAgreement: '+e);
        }
        return lAgreement;
	}

	@AuraEnabled
    public static String acceptAgreement(Boolean aAgree, String aIdMember){

        if (!aAgree) return '';
        try {
            FieloPLT.MemberService.acceptCurrentAgreement(aIdMember);
            return 'Sucesso';
        } catch (Exception e) {
            if(e.getTypeName() == 'System.DmlException'){
    			return ((System.DmlException) e).getDmlMessage(0);
    		}
        }
        return Label.V_ErroGenerico;
	}
}