force-app/main/default/objects/FieloPLT__Agreement__c/FieloPLT__Agreement__c.object-meta.xml
<CustomObject>
    <description>Terms and conditions of service that Members need to accept in order to be part of the loyalty Program in which you wish to include them.</description>
    <label>Agreement</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Version</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Agreement__c/fields/FieloPLT__Agreement__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Agreement__c</fullName>
    <description>Agreement terms and conditions.</description>
    <inlineHelpText>Enter the Agreement terms and conditions.</inlineHelpText>
    <label>Agreement</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Agreement__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It shows the Program which the Agreement belongs to.</description>
    <inlineHelpText>Choose the Program which the Agreement belongs to.</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Agreement__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Agreement status: Draft, Current, Active or Deprecated.</description>
    <inlineHelpText>Agreement status: Draft, Current, Active or Deprecated.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Agreement__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Agreement.</description>
    <inlineHelpText>Related Agreement.</inlineHelpText>
    <label>Agreement</label>
    <referenceTo>FieloPLT__Agreement__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Member&apos;s points.</description>
    <inlineHelpText>Member&apos;s points.</inlineHelpText>
    <label>Points</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program that the Member belongs to.</description>
    <inlineHelpText>The Program that the Member belongs to</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</description>
    <inlineHelpText>Choose Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Saldo de betcoins (extras) do participante.Saldo de pontos gerado pela iniciativa Youbet Complementar.</description>
    <inlineHelpText>Saldo de betcoins (extras) do participante.Saldo de pontos gerado pela iniciativa Youbet Complementar.</inlineHelpText>
    <label>Betcoins - Extra</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Program__c/FieloPLT__Program__c.object-meta.xml
<CustomObject>
    <description>Programs establish the general operation settings for your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SX_HomeThemeController.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: LK                                                   date: 15/09/2018
* 
* Name: SX_HomeThemeController.cls
* 
* Classe controladora para SX_Theme_Home
*******************************************************************************/

public without sharing class SX_HomeThemeController {

    @AuraEnabled
    public static Boolean isAdmin() {
        List<Profile> lProfile = [SELECT Id, Name FROM Profile WHERE Id=: userinfo.getProfileId() LIMIT 1];
        return !lProfile.isEmpty() && lProfile[0].Name.contains('Administrador do sistema') ? true : false;         
    }

	// Campos faltando:
	// Score Atual, Score Projetado, Posição no Ranking
	// Vagas remanescentes, Badges
	@AuraEnabled
    public static  List<FieloPLT__Member__c> getMembers() {
        List<FieloPLT__Member__c> lMemberLst = [SELECT Id, Name, FieloPLT__Program__c, FieloPLT__User__c
	                FROM FieloPLT__Member__c
	                WHERE FieloPLT__User__c =: UserInfo.getUserId()];
        if(lMemberLst.isEmpty())
            return null;
        else    
            return lMemberLst;               
    }

    @AuraEnabled
    public static FieloPLT__Member__c getMember() {
        List<FieloPLT__Member__c> lMemberLst = [SELECT Id, Name, FieloPLT__Program__c, FieloPLT__User__c, FieloPLT__Points__c,
         V_BetcoinsComp__c, FieloPLT__Agreement__c
	                FROM FieloPLT__Member__c
	                WHERE FieloPLT__User__c =: UserInfo.getUserId()];
        if(lMemberLst.isEmpty())
            return null;
        else    
            return lMemberLst[0];           
    }

    @AuraEnabled
    public static Boolean aceitarRegulamento(String aIdMember){

        try {
            FieloPLT.MemberService.acceptCurrentAgreement(aIdMember);
            return true;
        } catch (Exception e) {}
        return false;
    }

    @AuraEnabled
    public static FieloPLT__Agreement__c getAgreement(String aIdProgram){

        FieloPLT__Agreement__c lAgreement;
        try{
            lAgreement = FieloPLT.AgreementService.getCurrentAgreement(aIdProgram, new Set<String>{'Id', 'FieloPLT__Status__c', 'FieloPLT__Agreement__c'});

        } catch (Exception e) {
            system.debug('### error getAgreement: '+e);
        }
        return lAgreement;
    }
}