force-app/main/default/objects/FieloPLT__Agreement__c/FieloPLT__Agreement__c.object-meta.xml
<CustomObject>
    <description>Terms and conditions of service that Members need to accept in order to be part of the loyalty Program in which you wish to include them.</description>
    <label>Agreement</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Version</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Agreement__c/fields/FieloPLT__Agreement__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Agreement__c</fullName>
    <description>Agreement terms and conditions.</description>
    <inlineHelpText>Enter the Agreement terms and conditions.</inlineHelpText>
    <label>Agreement</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Agreement__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It shows the Program which the Agreement belongs to.</description>
    <inlineHelpText>Choose the Program which the Agreement belongs to.</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Agreement__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Agreement status: Draft, Current, Active or Deprecated.</description>
    <inlineHelpText>Agreement status: Draft, Current, Active or Deprecated.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Agreement__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Agreement.</description>
    <inlineHelpText>Related Agreement.</inlineHelpText>
    <label>Agreement</label>
    <referenceTo>FieloPLT__Agreement__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program that the Member belongs to.</description>
    <inlineHelpText>The Program that the Member belongs to</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</description>
    <inlineHelpText>Choose Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_RegistroParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_RegistroParticipante__c</fullName>
    <description>Registro exclusivo do participante na Serasa Experian. Não aceita duplicidade de registros.</description>
    <externalId>true</externalId>
    <inlineHelpText>Registro exclusivo do participante na Serasa Experian. Não aceita duplicidade de registros.</inlineHelpText>
    <label>Login</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FieloPLT__Program__c/FieloPLT__Program__c.object-meta.xml
<CustomObject>
    <description>Programs establish the general operation settings for your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LightningLoginFormController.cls
global class LightningLoginFormController {

    public LightningLoginFormController() {
        
    }

    @AuraEnabled
    public static String login(String registroMember, String password, String startUrl) {
        if (false) {
            return 'forceError';
        }
        List<FieloPLT__Member__c> lstMember = [SELECT FieloPLT__Status__c, FieloPLT__User__r.Username, FieloPLT__Agreement__c, FieloPLT__Program__c
                FROM FieloPLT__Member__c WHERE V_RegistroParticipante__c =: registroMember
                OR FieloPLT__User__r.Username =: registroMember];
        if (!lstMember.isEmpty()) {
            if(lstMember[0].FieloPLT__Status__c != 'Active') return 'Usuário inativo';
            registroMember = lstMember[0].FieloPLT__User__r.Username;
        } else {
            return 'Usuário não encontrado';
        }
        try{
            ApexPages.PageReference lgn = Site.login(registroMember, password, startUrl);
            aura.redirect(lgn);
            return null;
        }
        catch (Exception ex) {
            return ex.getMessage();            
        }
    }

    @AuraEnabled
    public static String forgotPassword(String username, String checkEmailUrl) {
        try {
            Site.forgotPassword(username);
            ApexPages.PageReference checkEmailRef = new PageReference(checkEmailUrl);
            if(!Site.isValidUsername(username)) {
                return Label.Site.invalid_email;
            }
            aura.redirect(checkEmailRef);
            return null;
        }
        catch (Exception ex) {
            return ex.getMessage();
        }
    }
    
    @AuraEnabled
    public static Boolean getIsUsernamePasswordEnabled() {
        Auth.AuthConfiguration authConfig = getAuthConfig();
        return authConfig.getUsernamePasswordEnabled();
    }

    @AuraEnabled
    public static Boolean getIsSelfRegistrationEnabled() {
        Auth.AuthConfiguration authConfig = getAuthConfig();
        return authConfig.getSelfRegistrationEnabled();
    }

    @AuraEnabled
    public static String getSelfRegistrationUrl() {
        Auth.AuthConfiguration authConfig = getAuthConfig();
        if (authConfig.getSelfRegistrationEnabled()) {
            return authConfig.getSelfRegistrationUrl();
        }
        return null;
    }

    @AuraEnabled
    public static String getForgotPasswordUrl() {
        Auth.AuthConfiguration authConfig = getAuthConfig();
        return authConfig.getForgotPasswordUrl();
    }
    
    @TestVisible
    private static Auth.AuthConfiguration getAuthConfig(){
        Id networkId = Network.getNetworkId();
        Auth.AuthConfiguration authConfig = new Auth.AuthConfiguration(networkId,'');
        return authConfig;
    }

    @AuraEnabled
    global static String setExperienceId(String expId) {
        // Return null if there is no error, else it will return the error message 
        try {
            if (expId != null) {
                Site.setExperienceId(expId);
            }
            return null; 
        } catch (Exception ex) {
            return ex.getMessage();            
        }
    }   
}