force-app/main/default/objects/FieloPLT__Reward__c/FieloPLT__Reward__c.object-meta.xml
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_IsActive__c.field-meta.xml
<CustomField>
    <fullName>V_IsActive__c</fullName>
    <formula>AND(V_YoubetCompleto__c,
				RecordType.Name = &apos;Leilões&apos;,
				OR (ISBLANK(V_DataHoraInicioYoubet__c),
								V_DataHoraInicioYoubet__c &lt;= NOW()),
				V_DataHoraFimYoubet__c &gt;= NOW())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_YoubetProcessado__c.field-meta.xml
<CustomField>
    <fullName>V_YoubetProcessado__c</fullName>
    <description>Campo atualizado com data e hora após processamento do batch para indicar o lance vencedor após a vigência do Youbet. Se assinalado, indica que o Youbet encerrado já teve a indicação do lance ganhador.</description>
    <inlineHelpText>Campo atualizado com data e hora após processamento do batch para indicar o lance vencedor após a vigência do Youbet. Se assinalado, indica que o Youbet encerrado já teve a indicação do lance ganhador.</inlineHelpText>
    <label>Youbet Processado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VN_LogBatch__c/VN_LogBatch__c.object-meta.xml
<CustomObject>
    <label>Log Batch</label>
    <nameField>
        <displayFormat>Log - {00000000}</displayFormat>
        <label>Nome de Log Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs Batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_LogBatch__c/fields/V_ErroResultado__c.field-meta.xml
<CustomField>
    <fullName>V_ErroResultado__c</fullName>
    <label>Erro Resultado</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VN_LogBatch__c/fields/V_IdBatch__c.field-meta.xml
<CustomField>
    <fullName>V_IdBatch__c</fullName>
    <label>Id Batch</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_LogBatch__c/fields/V_Processo__c.field-meta.xml
<CustomField>
    <fullName>V_Processo__c</fullName>
    <label>Processo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/VN_ParticipanteComPerfilCompativel__c.object-meta.xml
<CustomObject>
    <description>Lista relacionada do Youbet, participantes que possuem compatibilidade de cargo, área, liderança e elegibilidade no momento da criação do Youbet.</description>
    <label>Participante Com Perfil Compatível</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>No. Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes Com Perfis Compatíveis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_EnviaEmailInicioLeilao__c.field-meta.xml
<CustomField>
    <fullName>V_EnviaEmailInicioLeilao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Envia Email Inicio Leilão</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Reward__c.field-meta.xml
<CustomField>
    <fullName>V_Reward__c</fullName>
    <description>Youbet relacionado ao participante com compatibilidade de critérios (Cargo, Área, Liderança e Elegibilidade).</description>
    <inlineHelpText>Youbet relacionado ao participante com compatibilidade de critérios (Cargo, Área, Liderança e Elegibilidade).</inlineHelpText>
    <label>Youbet</label>
    <referenceTo>FieloPLT__Reward__c</referenceTo>
    <relationshipLabel>Participantes Com Perfis Compatíveis</relationshipLabel>
    <relationshipName>ParticipantesPerfiCompativeis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_YoubetProcessado__c.field-meta.xml
<CustomField>
    <fullName>V_YoubetProcessado__c</fullName>
    <formula>V_Reward__r.V_YoubetProcessado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Youbet Processado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SX_BatchEmailInicioLeilao.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: PV                                   date: 13/08/2019
* 
* Batch para atualizar campo para disparo de email no inicio do leilao
*
* System.schedule('SX_BatchEmailInicioLeilao - Hora','0 0 * * * ? *', new SX_BatchEmailInicioLeilao());
* System.schedule('SX_BatchEmailInicioLeilao - MeiaHora','0 30 * * * ? *', new SX_BatchEmailInicioLeilao());
*******************************************************************************/
global class SX_BatchEmailInicioLeilao implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
    
    global String fMsgErro;

	global void execute(SchedulableContext sc) {
        Database.executeBatch(this, 150);
    }

	global SX_BatchEmailInicioLeilao() {
		if(SX_Utils.batchIsProcessing('SX_BatchEmailInicioLeilao')) return;
		fMsgErro = '';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([
            SELECT Id, V_EnviaEmailInicioLeilao__c
            FROM VN_ParticipanteComPerfilCompativel__c
            WHERE V_EnviaEmailInicioLeilao__c = false
            AND V_Reward__r.V_IsActive__c = true
            AND V_Reward__r.RecordTypeId =: VN_RecType.getID('FieloPLT__Reward__c', Label.V_RecTypeLeiloes)
            AND V_Reward__r.V_YoubetProcessado__c = null
        ]);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
   		if(scope == null || scope.isEmpty()) return;

   		List<VN_ParticipanteComPerfilCompativel__c> lPPCompativelLst = (List<VN_ParticipanteComPerfilCompativel__c>)scope;

   		for(VN_ParticipanteComPerfilCompativel__c lPPCompativel : lPPCompativelLst){
            lPPCompativel.V_EnviaEmailInicioLeilao__c = true;
   		}

   		try {
            List<Database.SaveResult> lSaveResultLst = Database.update(lPPCompativelLst, false);
   			
            for(Database.SaveResult lSaveResult : lSaveResultLst) {
                if (!lSaveResult.isSuccess()){
                    for(Database.Error err : lSaveResult.getErrors()) {
                        fMsgErro += ' ' + err.getMessage();
                    }
                }  
            } 
		} catch(Exception e){
			fMsgErro = String.valueOf(e.getMessage());
			throw e;
		}
	}
	
	global void finish(Database.BatchableContext BC) {
		if(String.isNotEmpty(fMsgErro)){
			insert new VN_LogBatch__c(V_Processo__c = 'SX_BatchEmailInicioLeilao',
				 V_IdBatch__c = BC.getJobId(), V_ErroResultado__c = fMsgErro.left(32768));
		}
	}
}