force-app/main/default/objects/FieloPLT__Redemption__c/FieloPLT__Redemption__c.object-meta.xml
<CustomObject>
    <description>Redemptions are the orders generated by Members when they redeem their available Points for Rewards. Redemptions may include as many &quot;Redemptions Items&quot; as Rewards redeemed, as each Redemption Item represents a particular redeemed Reward.</description>
    <label>Redemption</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Redemption statuses. The available options are: Open, Closed, Pending and Rejected.</description>
    <inlineHelpText>Choose the Redemption status (Open, Closed, Pending or Rejected).</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Desqualificado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/V_LanceGanhador__c.field-meta.xml
<CustomField>
    <fullName>V_LanceGanhador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lance Ganhador</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/FieloPLT__RedemptionItem__c.object-meta.xml
<CustomObject>
    <description>Redemption Items represent each item which is part of a Redemption order.</description>
    <label>Redemption Item</label>
    <nameField>
        <displayFormat>RI-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemption Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Quantity__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of Redemption items.</description>
    <inlineHelpText>Number of Redemption items.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Redemption__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Redemption__c</fullName>
    <description>The Redemption order that the Member has made.</description>
    <inlineHelpText>The Redemption order that the Member has made.</inlineHelpText>
    <label>Redemption</label>
    <referenceTo>FieloPLT__Redemption__c</referenceTo>
    <relationshipLabel>Redemption Items</relationshipLabel>
    <relationshipName>RedemptionItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Reward__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Reward that the Member has redeemed.</description>
    <inlineHelpText>The Reward that the Member has redeemed.</inlineHelpText>
    <label>Reward</label>
    <referenceTo>FieloPLT__Reward__c</referenceTo>
    <relationshipLabel>Redemption Items</relationshipLabel>
    <relationshipName>RedemptionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Where a Redemption Item is in the order process: Delivered, Open, Expired, Ready, Reverted or Pending</description>
    <inlineHelpText>Where this item is in the order process.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Reverted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/V_DataHoraFimYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_DataHoraFimYoubet__c</fullName>
    <formula>FieloPLT__Reward__r.V_DataHoraFimYoubet__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data/Hora Fim do Youbet</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/V_LanceGanhador__c.field-meta.xml
<CustomField>
    <fullName>V_LanceGanhador__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo indica o lance do leilão ganhador (maior quantidade de pontos). Será atualizado por batch após o término da vigência do leilão.</description>
    <inlineHelpText>Campo indica o lance do leilão ganhador (maior quantidade de pontos). Será atualizado por batch após o término da vigência do leilão.</inlineHelpText>
    <label>Lance Ganhador</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/FieloPLT__Reward__c.object-meta.xml
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_DataHoraFimYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_DataHoraFimYoubet__c</fullName>
    <description>Data e hora para finalizar a vigência do youbet.</description>
    <inlineHelpText>Data e hora para finalizar a vigência do youbet.</inlineHelpText>
    <label>Data/Hora Fim do Youbet</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_YoubetProcessado__c.field-meta.xml
<CustomField>
    <fullName>V_YoubetProcessado__c</fullName>
    <description>Campo atualizado com data e hora após processamento do batch para indicar o lance vencedor após a vigência do Youbet. Se assinalado, indica que o Youbet encerrado já teve a indicação do lance ganhador.</description>
    <inlineHelpText>Campo atualizado com data e hora após processamento do batch para indicar o lance vencedor após a vigência do Youbet. Se assinalado, indica que o Youbet encerrado já teve a indicação do lance ganhador.</inlineHelpText>
    <label>Youbet Processado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VN_LogBatch__c/VN_LogBatch__c.object-meta.xml
<CustomObject>
    <label>Log Batch</label>
    <nameField>
        <displayFormat>Log - {00000000}</displayFormat>
        <label>Nome de Log Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs Batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_LogBatch__c/fields/V_ErroResultado__c.field-meta.xml
<CustomField>
    <fullName>V_ErroResultado__c</fullName>
    <label>Erro Resultado</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VN_LogBatch__c/fields/V_IdBatch__c.field-meta.xml
<CustomField>
    <fullName>V_IdBatch__c</fullName>
    <label>Id Batch</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_LogBatch__c/fields/V_Processo__c.field-meta.xml
<CustomField>
    <fullName>V_Processo__c</fullName>
    <label>Processo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SX_BatchLanceGanhador.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 11/09/2018
* 
* 
* Batch para procassar o Lance Ganhador
*
*******************************************************************************/
global class SX_BatchLanceGanhador implements Database.Batchable<sObject>, Database.Stateful, Schedulable {

	global String fMsgErro;

	global void execute(SchedulableContext sc) {
        Database.executeBatch(this, 150);
    }

	
	global SX_BatchLanceGanhador() {

		if(SX_Utils.batchIsProcessing('SX_BatchLanceGanhador')) return;
		fMsgErro = '';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {

		return Database.getQueryLocator([SELECT Id, V_YoubetProcessado__c, (SELECT Id, V_LanceGanhador__c, 
											FieloPLT__Redemption__c FROM FieloPLT__RedemptionItems__r 
													WHERE FieloPLT__Status__c =: Label.V_StatusOpen
													ORDER BY FieloPLT__Quantity__c DESC LIMIT 1)
										 FROM FieloPLT__Reward__c
										 WHERE V_DataHoraFimYoubet__c <: system.now()
										 AND RecordTypeId =: VN_RecType.getID('FieloPLT__Reward__c', Label.V_RecTypeLeiloes)
										 AND V_YoubetProcessado__c = null]);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {

   		if ( scope == null || scope.isEmpty()) return; 
   		List<FieloPLT__Reward__c> lLstReward = ( List<FieloPLT__Reward__c> ) scope; 

   		List<FieloPLT__RedemptionItem__c> lLstRedItem = new List<FieloPLT__RedemptionItem__c>(); 
   		List<FieloPLT__Redemption__c> lLstRedemption = new List<FieloPLT__Redemption__c>(); 

   		for(FieloPLT__Reward__c rew: lLstReward){

   			rew.V_YoubetProcessado__c = system.now();

   			for(FieloPLT__RedemptionItem__c rdi: rew.FieloPLT__RedemptionItems__r){
   				rdi.V_LanceGanhador__c = true;
   				lLstRedItem.add(rdi);
   				lLstRedemption.add(new FieloPLT__Redemption__c(
   						Id = rdi.FieloPLT__Redemption__c, 
   						FieloPLT__Status__c = 'Closed')
   				);
   			}
   		}

   		Savepoint sp = Database.setSavepoint();

   		try{

   			update lLstReward;
   			FieloPLT.SobjectService.enableAdminPermission(true);
   			update lLstRedItem;
   			FieloPLT.SobjectService.enableAdminPermission(false);
   			update lLstRedemption;

   			List<FieloPLT__Redemption__c> lLstRedmpDesqualificado = [SELECT Id, FieloPLT__Status__c
   				FROM FieloPLT__Redemption__c WHERE FieloPLT__Status__c =: Label.V_StatusOpen 
   				AND Id IN (SELECT FieloPLT__Redemption__c FROM FieloPLT__RedemptionItem__c 
   				WHERE FieloPLT__Reward__c =: lLstReward)];

   			for(FieloPLT__Redemption__c redmp: lLstRedmpDesqualificado){
   				redmp.FieloPLT__Status__c = 'Desqualificado';
   			}
   			update lLstRedmpDesqualificado;

		}catch(Exception e){
			Database.rollBack(sp);
			fMsgErro = String.valueOf(e.getMessage());
			throw e;
		}
	}
	
	global void finish(Database.BatchableContext BC) {

		if(String.isNotEmpty(fMsgErro)){
			insert new VN_LogBatch__c(V_Processo__c = 'Lance Ganhador',
				 V_IdBatch__c = BC.getJobId(), V_ErroResultado__c = fMsgErro.left(32768));
		}
	}	
}