force-app/main/default/objects/FieloPLT__Redemption__c/FieloPLT__Redemption__c.object-meta.xml
<CustomObject>
    <description>Redemptions are the orders generated by Members when they redeem their available Points for Rewards. Redemptions may include as many &quot;Redemptions Items&quot; as Rewards redeemed, as each Redemption Item represents a particular redeemed Reward.</description>
    <label>Redemption</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/FieloPLT__RedemptionItem__c.object-meta.xml
<CustomObject>
    <description>Redemption Items represent each item which is part of a Redemption order.</description>
    <label>Redemption Item</label>
    <nameField>
        <displayFormat>RI-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemption Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Points needed to redeem the Redemption item</description>
    <inlineHelpText>Points needed to redeem the Redemption item.</inlineHelpText>
    <label>Points</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Quantity__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of Redemption items.</description>
    <inlineHelpText>Number of Redemption items.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Redemption__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Redemption__c</fullName>
    <description>The Redemption order that the Member has made.</description>
    <inlineHelpText>The Redemption order that the Member has made.</inlineHelpText>
    <label>Redemption</label>
    <referenceTo>FieloPLT__Redemption__c</referenceTo>
    <relationshipLabel>Redemption Items</relationshipLabel>
    <relationshipName>RedemptionItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Reward__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Reward that the Member has redeemed.</description>
    <inlineHelpText>The Reward that the Member has redeemed.</inlineHelpText>
    <label>Reward</label>
    <referenceTo>FieloPLT__Reward__c</referenceTo>
    <relationshipLabel>Redemption Items</relationshipLabel>
    <relationshipName>RedemptionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Where a Redemption Item is in the order process: Delivered, Open, Expired, Ready, Reverted or Pending</description>
    <inlineHelpText>Where this item is in the order process.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Reverted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <description>Saldo de pontos gerado pela iniciativa Youbet Extra. Quando a iniciativa for criada, necessário renomear o rótulo do campo para &quot;Betcoins - Nome do Leilão&quot;.</description>
    <inlineHelpText>Saldo de pontos gerado pela iniciativa Youbet Extra. Quando a iniciativa for criada, necessário renomear o rótulo do campo para &quot;Betcoins - Nome do Leilão&quot;.</inlineHelpText>
    <label>Betcoins - Extra</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/V_DataHoraFimYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_DataHoraFimYoubet__c</fullName>
    <formula>FieloPLT__Reward__r.V_DataHoraFimYoubet__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data/Hora Fim do Youbet</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/V_DataHoraInicioYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_DataHoraInicioYoubet__c</fullName>
    <formula>FieloPLT__Reward__r.V_DataHoraInicioYoubet__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data/Hora Início do Youbet</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/FieloPLT__Reward__c.object-meta.xml
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Reward__c/fields/FieloPLT__Image__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Image__c</fullName>
    <description>Reward image which can be uploaded.</description>
    <inlineHelpText>Upload an attractive image for your Reward.</inlineHelpText>
    <label>Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Number of Points needed to redeem a Reward.</description>
    <inlineHelpText>Enter the number of Points needed to redeem this Reward.</inlineHelpText>
    <label>Points</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/Iniciativa__c.field-meta.xml
<CustomField>
    <fullName>Iniciativa__c</fullName>
    <description>Tipos de iniciativa do incentivo.</description>
    <inlineHelpText>Tipos de iniciativa do incentivo.</inlineHelpText>
    <label>Iniciativa</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Youbet Perene</fullName>
            </value>
            <value>
                <fullName>Youbet Extra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <description>Preencha com valor igual a 1 para Youbet Extra. E com 0 (zero) quando for Youbet Perene.</description>
    <inlineHelpText>Preencha com valor igual a 1 para Youbet Extra. E com 0 (zero) quando for Youbet Perene</inlineHelpText>
    <label>Betcoins - Extra</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_DataHoraFimYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_DataHoraFimYoubet__c</fullName>
    <description>Data e hora para finalizar a vigência do youbet.</description>
    <inlineHelpText>Data e hora para finalizar a vigência do youbet.</inlineHelpText>
    <label>Data/Hora Fim do Youbet</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_DataHoraInicioYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_DataHoraInicioYoubet__c</fullName>
    <description>Data e hora para iniciar a vigência do youbet.</description>
    <inlineHelpText>Data e hora para iniciar a vigência do youbet.</inlineHelpText>
    <label>Data/Hora Início do Youbet</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_IsActive__c.field-meta.xml
<CustomField>
    <fullName>V_IsActive__c</fullName>
    <formula>AND(V_YoubetCompleto__c,
				RecordType.Name = &apos;Leilões&apos;,
				OR (ISBLANK(V_DataHoraInicioYoubet__c),
								V_DataHoraInicioYoubet__c &lt;= NOW()),
				V_DataHoraFimYoubet__c &gt;= NOW())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_LanceMinimo__c.field-meta.xml
<CustomField>
    <fullName>V_LanceMinimo__c</fullName>
    <description>Quando preenchido, deverá haver regra para não permitir que o participante dê um lance menor para o youbet que o valor preenchido neste campo.</description>
    <inlineHelpText>Quando preenchido, deverá haver regra para não permitir que o participante dê um lance menor para o youbet que o valor preenchido neste campo.</inlineHelpText>
    <label>Lance Mínimo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_LanceResgatarAgora__c.field-meta.xml
<CustomField>
    <fullName>V_LanceResgatarAgora__c</fullName>
    <description>Quando este campo estiver prenchido com alguma pontuação, quer dizer que o primeiro participante que der esse valor no lance, o youbet será encerrado.</description>
    <inlineHelpText>Quando este campo estiver prenchido com alguma pontuação, quer dizer que o primeiro participante que der esse valor no lance, o youbet será encerrado.</inlineHelpText>
    <label>Lance para Resgatar Agora</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_RegulamentoYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_RegulamentoYoubet__c</fullName>
    <description>Utilizado para a inclusão do texto de regulamento do Youbet Perene ou Complementar.</description>
    <inlineHelpText>Utilizado para a inclusão do texto de regulamento do Youbet Perene ou Complementar.</inlineHelpText>
    <label>Regulamento Youbet</label>
    <length>100768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/VN_ParticipanteComPerfilCompativel__c.object-meta.xml
<CustomObject>
    <description>Lista relacionada do Youbet, participantes que possuem compatibilidade de cargo, área, liderança e elegibilidade no momento da criação do Youbet.</description>
    <label>Participante Com Perfil Compatível</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>No. Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes Com Perfis Compatíveis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Member__c.field-meta.xml
<CustomField>
    <fullName>V_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Participante relacionado ao youbet de compatibilidade.</description>
    <inlineHelpText>Participante relacionado ao youbet de compatibilidade.</inlineHelpText>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Youbets Compatíveis</relationshipLabel>
    <relationshipName>V_RewardsCompativeis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Reward__c.field-meta.xml
<CustomField>
    <fullName>V_Reward__c</fullName>
    <description>Youbet relacionado ao participante com compatibilidade de critérios (Cargo, Área, Liderança e Elegibilidade).</description>
    <inlineHelpText>Youbet relacionado ao participante com compatibilidade de critérios (Cargo, Área, Liderança e Elegibilidade).</inlineHelpText>
    <label>Youbet</label>
    <referenceTo>FieloPLT__Reward__c</referenceTo>
    <relationshipLabel>Participantes Com Perfis Compatíveis</relationshipLabel>
    <relationshipName>ParticipantesPerfiCompativeis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SX_RewardServices.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: PT                         							date: 21/09/2018
* 
* Name: SX_RewardServices.cls
* 
* Classe que implementa funcões do reward
*******************************************************************************/
public with sharing class SX_RewardServices {
	
	public static FieloPLT__Reward__c getReward(String aMemberId, String aIniciativa) {
		List<VN_ParticipanteComPerfilCompativel__c> lstRewardCompativel = [SELECT V_Reward__c
				FROM VN_ParticipanteComPerfilCompativel__c WHERE V_Member__c =: aMemberId
				AND V_Reward__r.Iniciativa__c =: aIniciativa
				AND (V_Reward__r.V_IsActive__c = true OR V_Reward__r.V_DataHoraInicioYoubet__c >: System.now() )
				 ORDER BY V_Reward__r.V_IsActive__c DESC, 
				V_Reward__r.V_DataHoraFimYoubet__c LIMIT 1];
		if (lstRewardCompativel.isEmpty()) return null;

		List<FieloPLT__Reward__c> lstReward = [SELECT Id, Name, FieloPLT__Points__c, V_BetcoinsComp__c, Iniciativa__c,
				FieloPLT__Image__c, V_LanceResgatarAgora__c, V_LanceMinimo__c, V_DataHoraFimYoubet__c, V_IsActive__c,
			    V_RegulamentoYoubet__c, (SELECT FieloPLT__Quantity__c, FieloPLT__Redemption__r.FieloPLT__Member__r.Name FROM FieloPLT__RedemptionItems__r 
										WHERE FieloPLT__Status__c =: Label.V_StatusOpen
										ORDER BY FieloPLT__Quantity__c DESC LIMIT 1)
				FROM FieloPLT__Reward__c
				WHERE Id =: lstRewardCompativel[0].V_Reward__c];
		if (!lstReward.isEmpty()) {
			return lstReward[0];
		} else {
			return null;
		}
	}
}