force-app/main/default/objects/FieloPLT__Redemption__c/FieloPLT__Redemption__c.object-meta.xml
<CustomObject>
    <description>Redemptions are the orders generated by Members when they redeem their available Points for Rewards. Redemptions may include as many &quot;Redemptions Items&quot; as Rewards redeemed, as each Redemption Item represents a particular redeemed Reward.</description>
    <label>Redemption</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Points needed to redeem the Reward.</description>
    <inlineHelpText>Points needed to redeem the Reward.</inlineHelpText>
    <label>Points</label>
    <summarizedField>FieloPLT__RedemptionItem__c.FieloPLT__Points__c</summarizedField>
    <summaryFilterItems>
        <field>FieloPLT__RedemptionItem__c.FieloPLT__Status__c</field>
        <operation>notEqual</operation>
        <value>Reverted</value>
    </summaryFilterItems>
    <summaryForeignKey>FieloPLT__RedemptionItem__c.FieloPLT__Redemption__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Redemption statuses. The available options are: Open, Closed, Pending and Rejected.</description>
    <inlineHelpText>Choose the Redemption status (Open, Closed, Pending or Rejected).</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Desqualificado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <description>Saldo de pontos gerado pela iniciativa Youbet Extra. Quando a iniciativa for criada, necessário renomear o rótulo do campo para &quot;Betcoins - Nome do Leilão&quot;.</description>
    <inlineHelpText>Saldo de pontos gerado pela iniciativa Youbet Extra. Quando a iniciativa for criada, necessário renomear o rótulo do campo para &quot;Betcoins - Nome do Leilão&quot;.</inlineHelpText>
    <label>Betcoins - Extra</label>
    <summarizedField>FieloPLT__RedemptionItem__c.V_BetcoinsComp__c</summarizedField>
    <summaryFilterItems>
        <field>FieloPLT__RedemptionItem__c.FieloPLT__Status__c</field>
        <operation>notEqual</operation>
        <value>Reverted</value>
    </summaryFilterItems>
    <summaryForeignKey>FieloPLT__RedemptionItem__c.FieloPLT__Redemption__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/V_LanceGanhador__c.field-meta.xml
<CustomField>
    <fullName>V_LanceGanhador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lance Ganhador</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/V_MetaParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_MetaParticipante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ano Fiscal</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipLabel>Resgates/Lances</relationshipLabel>
    <relationshipName>Resgates_Lances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_LancesLeiloes__c.field-meta.xml
<CustomField>
    <fullName>V_LancesLeiloes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lances Leilões</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_LeiloesGanhos__c.field-meta.xml
<CustomField>
    <fullName>V_LeiloesGanhos__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Leilões Ganhos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SX_Redemption_After.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 01/02/2019
* 
* Name: SX_Redemption_After.cls
* 
* Classe para disparar ações after em FieloPLT__Redemption__c
*
* Ações:
* 1 - sumarizar total de lances e lance ganhador nas metas
*******************************************************************************/
public with sharing class SX_Redemption_After {

	@TestVisible final static String CLOSED = 'Closed';
	@TestVisible final static String REVERTED = 'Reverted';

	public static void execute() {

		VN_TriggerCheck.assert();

		List<FieloPLT__Redemption__c> lLstTrigger = (List<FieloPLT__Redemption__c>) (trigger.isDelete ? trigger.old : trigger.new);

		Set<Id> lSetMetas = new Set<Id>();
		for(FieloPLT__Redemption__c redemp: lLstTrigger){

			if( VN_TriggerCheck.isChangedTo(redemp, FieloPLT__Redemption__c.FieloPLT__Status__c, CLOSED) 
				|| VN_TriggerCheck.isChangedTo(redemp, FieloPLT__Redemption__c.FieloPLT__Status__c, REVERTED) 
				|| VN_TriggerCheck.isChanged(redemp, FieloPLT__Redemption__c.V_MetaParticipante__c)
				|| VN_TriggerCheck.isChanged(redemp, FieloPLT__Redemption__c.V_LanceGanhador__c)
				|| trigger.isDelete){

				if(redemp.V_MetaParticipante__c != null) lSetMetas.add(redemp.V_MetaParticipante__c);

				// se deixou de ter meta, guarda meta antiga para recálculo
				if(trigger.isUpdate && VN_TriggerCheck.isChanged(redemp, FieloPLT__Redemption__c.V_MetaParticipante__c) 
					&& ((FieloPLT__Redemption__c)trigger.oldMap.get( redemp.id )).V_MetaParticipante__c != null){
					lSetMetas.add(((FieloPLT__Redemption__c)trigger.oldMap.get( redemp.id )).V_MetaParticipante__c);
				}
			}
		}

		// atualiza campos "totais" das metas
		if(!lSetMetas.isEmpty()){

			List<VN_MetaParticipante__c> lLstMeta = [SELECT Id, Name, V_LancesLeiloes__c, V_LeiloesGanhos__c,
				(SELECT Id, V_BetcoinsComp__c, FieloPLT__Points__c, V_LanceGanhador__c 
				FROM Resgates_Lances__r WHERE FieloPLT__Status__c =: CLOSED) FROM VN_MetaParticipante__c WHERE Id =: lSetMetas];

			for(VN_MetaParticipante__c meta: lLstMeta){

				meta.V_LancesLeiloes__c = 0;
				meta.V_LeiloesGanhos__c = 0; 

				for(FieloPLT__Redemption__c redemp: meta.Resgates_Lances__r){

					if(redemp.FieloPLT__Points__c > 0){
						meta.V_LancesLeiloes__c ++;

						if(redemp.V_LanceGanhador__c) meta.V_LeiloesGanhos__c ++;
					} 					
				}
			}
			if(!lLstMeta.isEmpty()) update lLstMeta;
		}
	}
}