force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualMetaYTD__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualMetaYTD__c</fullName>
    <formula>V_AMYTD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% Meta YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ScoreElite__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreElite__c</fullName>
    <formula>V_ScoreAtingimentoFY__c + V_ScoreSuperacaoFY__c + V_ScoreSuperacaoQ1__c + V_ScorePotencialCarteira__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score Elite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_TotalVendasYTD__c.field-meta.xml
<CustomField>
    <fullName>V_TotalVendasYTD__c</fullName>
    <label>Total de Vendas -YTD</label>
    <summarizedField>VN_Sumarizador__c.V_Valor__c</summarizedField>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_ProcessarMecanicas__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>VN_Sumarizador__c.V_MetaDoParticipante__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/VN_MetaParticipanteTrigger.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 08/08/2019
* 
* Name: VN_MetaParticipanteTrigger.cls
* 
* Classe manipuladora da trigger after de MetaParticipante
*******************************************************************************/
public with sharing class VN_MetaParticipanteTrigger {

	public static void atualizarRanking() {
		
		VN_TriggerCheck.assert();

		Set<String> lSetAnoFiscal = new Set<String>();
	  	for (VN_MetaParticipante__c meta : (List<VN_MetaParticipante__c>) trigger.new) {

			  if(VN_TriggerCheck.isChanged(meta, VN_MetaParticipante__c.V_ScoreElite__c)
			  			|| VN_TriggerCheck.isChanged(meta, VN_MetaParticipante__c.V_PercentualMetaYTD__c)
						|| VN_TriggerCheck.isChanged(meta, VN_MetaParticipante__c.V_TotalVendasYTD__c)){
	  			lSetAnoFiscal.add(meta.Name);
	  		}
	  	}
	  	if(!lSetAnoFiscal.isEmpty()){
			List<ApexClass> lstClasses = [SELECT Id FROM ApexClass WHERE Name = 'SX_BatchAtualizarRankingNaMeta'];
			Integer lSuperacaoScheduler = [SELECT COUNT() FROM AsyncApexJob 
				                        WHERE Status IN ('Processing','Preparing','Queued') 
				                        AND ApexClassID =: lstClasses[0].Id] ;
				
			if(lSuperacaoScheduler <= 0){
				Datetime lScheduledTime = datetime.now().addMinutes(3);
				String sch = '00 ' + lScheduledTime.minute() + ' '+ lScheduledTime.hour() + ' '
					+ ' ' + lScheduledTime.day() + ' ' + lScheduledTime.month() + ' ? ' + lScheduledTime.year();
				String jobId = system.schedule('Atualizar_Posição_Ranking' + lScheduledTime, sch,  new SX_BatchAtualizarRankingNaMeta(lSetAnoFiscal));
			}
		}
	}
}