force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_CodParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_CodParticipante__c</fullName>
    <description>Código exclusivo do participante relacionado ao registro do ano fiscal.</description>
    <formula>V_Participante__r.V_RegistroParticipante__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Código exclusivo do participante relacionado ao registro do ano fiscal.</inlineHelpText>
    <label>Cód. Participante</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualAM1Semestre__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAM1Semestre__c</fullName>
    <label>% AM - 1º Semestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualAM2Semestre__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAM2Semestre__c</fullName>
    <label>% AM - 2º Semestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualAM2Trimestre__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAM2Trimestre__c</fullName>
    <label>% AM - 2º Trimestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualAM3Trimestre__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAM3Trimestre__c</fullName>
    <label>% AM - 3º Trimestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualAM4Trimestre__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAM4Trimestre__c</fullName>
    <label>% AM - 4º Trimestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_QtdMesesComMetaRes1Semestre__c.field-meta.xml
<CustomField>
    <fullName>V_QtdMesesComMetaRes1Semestre__c</fullName>
    <label>Qtd Meses com Meta/Res. - 1º Semestre</label>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Mes__c</field>
        <operation>equals</operation>
        <value>1, 2, 3, 4, 5, 6</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Meta__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Valor__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>VN_Sumarizador__c.V_MetaDoParticipante__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_QtdMesesComMetaRes2Semestre__c.field-meta.xml
<CustomField>
    <fullName>V_QtdMesesComMetaRes2Semestre__c</fullName>
    <label>Qtd Meses com Meta/Res. - 2º Semestre</label>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Mes__c</field>
        <operation>equals</operation>
        <value>7, 8, 9, 10, 11, 12</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Meta__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Valor__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>VN_Sumarizador__c.V_MetaDoParticipante__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_QtdMesesComMetaRes2Trimestre__c.field-meta.xml
<CustomField>
    <fullName>V_QtdMesesComMetaRes2Trimestre__c</fullName>
    <label>Qtd Meses com Meta/Res. -  2º Trimestre</label>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Mes__c</field>
        <operation>equals</operation>
        <value>3, 4, 5</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Meta__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Valor__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>VN_Sumarizador__c.V_MetaDoParticipante__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_QtdMesesComMetaRes3Trimestre__c.field-meta.xml
<CustomField>
    <fullName>V_QtdMesesComMetaRes3Trimestre__c</fullName>
    <label>Qtd Meses com Meta/Res. - 3º Trimestre</label>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Mes__c</field>
        <operation>equals</operation>
        <value>7, 8, 9</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Meta__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Valor__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>VN_Sumarizador__c.V_MetaDoParticipante__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_QtdMesesComMetaRes4Trimestre__c.field-meta.xml
<CustomField>
    <fullName>V_QtdMesesComMetaRes4Trimestre__c</fullName>
    <label>Qtd Meses com Meta/Res. - 4º Trimestre</label>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Mes__c</field>
        <operation>equals</operation>
        <value>10, 11, 12</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Meta__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Valor__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>VN_Sumarizador__c.V_MetaDoParticipante__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_SuperacaoH1__c.field-meta.xml
<CustomField>
    <fullName>V_SuperacaoH1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Superação H1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_SuperacaoH2__c.field-meta.xml
<CustomField>
    <fullName>V_SuperacaoH2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Superação H2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_SuperacaoQ2__c.field-meta.xml
<CustomField>
    <fullName>V_SuperacaoQ2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Superação Q2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_SuperacaoQ3__c.field-meta.xml
<CustomField>
    <fullName>V_SuperacaoQ3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Superação Q3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_SuperacaoQ4__c.field-meta.xml
<CustomField>
    <fullName>V_SuperacaoQ4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Superação Q4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <description>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</description>
    <formula>V_AnoFiscal__r.V_Vigente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SX_BatchAtualizaSuperacaoMeta.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: LK                          date: 26/11/2019
* 
* Name: SX_BatchAtualizaSuperacaoMeta.cls
* 
* Batch para atualizar Superação na Meta
*******************************************************************************/
global with sharing class SX_BatchAtualizaSuperacaoMeta implements Database.Batchable<sObject>, Schedulable {
    global VN_MetaParticipante__c fMetaSerasa;
    global Boolean fVerificarTrimestre2;
	global Boolean fVerificarTrimestre3;
	global Boolean fVerificarTrimestre4;
	global Boolean fVerificarSemestre1;
	global Boolean fVerificarSemestre2;

    global void execute(SchedulableContext sc) {
        Database.executeBatch(this, 50);
    }

    global SX_BatchAtualizaSuperacaoMeta() {
        fVerificarTrimestre2 = false;
	    fVerificarTrimestre3 = false;
	    fVerificarTrimestre4 = false;
	    fVerificarSemestre1 = false;
	    fVerificarSemestre2 = false;
        fMetaSerasa = new VN_MetaParticipante__c();
		List<VN_MetaParticipante__c> lstMetaSerasa = new List<VN_MetaParticipante__c>();
		//Busca Meta Principal da Serasa
		lstMetaSerasa = [SELECT Id, V_PercentualAM2Trimestre__c, V_PercentualAM3Trimestre__c, V_PercentualAM4Trimestre__c, 
					V_PercentualAM1Semestre__c, V_PercentualAM2Semestre__c 
                    FROM VN_MetaParticipante__c WHERE V_CodParticipante__c = 'SSK3473' AND V_Vigente__c = true];

		if(!lstMetaSerasa.isEmpty()){
			fMetaSerasa = lstMetaSerasa[0];
            
            if(fMetaSerasa.V_PercentualAM2Trimestre__c > 101)
			    fVerificarTrimestre2 = true;
            if(fMetaSerasa.V_PercentualAM3Trimestre__c > 101)
                fVerificarTrimestre3 = true;
            if(fMetaSerasa.V_PercentualAM4Trimestre__c > 101)
                fVerificarTrimestre4 = true;
            if(fMetaSerasa.V_PercentualAM1Semestre__c > 102)
                fVerificarSemestre1 = true;
            if(fMetaSerasa.V_PercentualAM2Semestre__c > 102)
                fVerificarSemestre2 = true;
            
            if(!(fVerificarTrimestre2 || fVerificarTrimestre3 || fVerificarTrimestre4 
                    || fVerificarSemestre1 || fVerificarSemestre2)){
                fMetaSerasa = new VN_MetaParticipante__c();
            }
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        if(fMetaSerasa == null)
            return null;

        return Database.getQueryLocator([SELECT V_SuperacaoQ2__c, V_PercentualAM2Trimestre__c, V_QtdMesesComMetaRes2Trimestre__c, 
                V_SuperacaoQ3__c, V_PercentualAM3Trimestre__c, V_QtdMesesComMetaRes3Trimestre__c, 
                V_SuperacaoQ4__c, V_PercentualAM4Trimestre__c, V_QtdMesesComMetaRes4Trimestre__c, 
                V_SuperacaoH1__c, V_PercentualAM1Semestre__c, V_QtdMesesComMetaRes1Semestre__c, 
                V_SuperacaoH2__c, V_PercentualAM2Semestre__c, V_QtdMesesComMetaRes2Semestre__c
                FROM VN_MetaParticipante__c WHERE V_Vigente__c = true]);
    }

    global void execute(Database.BatchableContext BC, List<VN_MetaParticipante__c> aLstMetaScope) {

   		if (aLstMetaScope == null || aLstMetaScope.isEmpty()) 
            return;

        List<VN_MetaParticipante__c> lstMetaToUpdate = new List<VN_MetaParticipante__c>();
        for(VN_MetaParticipante__c lMeta : aLstMetaScope){
            Boolean lUpdateMeta = false;
				
            //Se Meta Serasa 2º Trimestre foi superada
            //Se Meta do 2º Trimestre do Participante foi Superada
            // E se o campo V_SuperacaoQ2__c está falso
            if(fVerificarTrimestre2 && !lMeta.V_SuperacaoQ2__c
                    && lMeta.V_PercentualAM2Trimestre__c > 101 && lMeta.V_QtdMesesComMetaRes2Trimestre__c == 3){
                
                lMeta.V_SuperacaoQ2__c = true;
                lUpdateMeta = true;
            }
            
            //Se Meta Serasa 3º Trimestre foi superada
            //Se Meta do 3º Trimestre do Participante foi Superada
            // E se o campo V_SuperacaoQ3__c está falso
            if(fVerificarTrimestre3 && !lMeta.V_SuperacaoQ3__c 
                    && lMeta.V_PercentualAM3Trimestre__c > 101 && lMeta.V_QtdMesesComMetaRes3Trimestre__c == 3){
                lMeta.V_SuperacaoQ3__c = true;
                lUpdateMeta = true;
            }

            //Se Meta Serasa 4º Trimestre foi superada
            //Se Meta do 4º Trimestre do Participante foi Superada
            // E se o campo V_SuperacaoQ4__c está falso
            if(fVerificarTrimestre4 && !lMeta.V_SuperacaoQ4__c 
                    && lMeta.V_PercentualAM4Trimestre__c > 101 && lMeta.V_QtdMesesComMetaRes4Trimestre__c == 3){
                lMeta.V_SuperacaoQ4__c = true;
                lUpdateMeta = true;
            }

            //Se Meta Serasa 1º Semestre foi superada
            //Se Meta do 1º Semestre do Participante foi Superada
            // E se o campo V_SuperacaoH1__c está falso
            if(fVerificarSemestre1 && !lMeta.V_SuperacaoH1__c 
                    && lMeta.V_PercentualAM1Semestre__c > 102 && lMeta.V_QtdMesesComMetaRes1Semestre__c == 6){
                lMeta.V_SuperacaoH1__c = true;
                lUpdateMeta = true;
            }

            //Se Meta Serasa 2º Semestre foi superada
            //Se Meta do 2º Semestre do Participante foi Superada
            // E se o campo V_SuperacaoH2__c está falso
            if(fVerificarSemestre2 && !lMeta.V_SuperacaoH2__c 
                    && lMeta.V_PercentualAM2Semestre__c > 102 && lMeta.V_QtdMesesComMetaRes2Semestre__c == 6){
                lMeta.V_SuperacaoH2__c = true;
                lUpdateMeta = true;
            }

            if(lUpdateMeta)
            	lstMetaToUpdate.add(lMeta);
        }

		if(!lstMetaToUpdate.isEmpty())
		    update lstMetaToUpdate;
    }

    global void finish(Database.BatchableContext BC) {}
}