force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/VN_GerenciadorMetaParticipanteAF__c.object-meta.xml
<CustomObject>
    <description>Gerenciador dos registros de metas dos participantes por Ano Fiscal.</description>
    <label>Gerenciador Meta Participante AF</label>
    <nameField>
        <displayFormat>GMAF-{000000}</displayFormat>
        <label>No. Gerenciador Ano Fiscal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gerenciador Metas Participantes AF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <description>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</description>
    <inlineHelpText>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</inlineHelpText>
    <label>Ano Fiscal</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sinaliza se o gerenciador é o que está em vigência.</description>
    <inlineHelpText>Sinaliza se o gerenciador é o que está em vigência.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ano fiscal da Meta do participante do participante</description>
    <label>Gerenciador Meta Participante AF</label>
    <referenceTo>VN_GerenciadorMetaParticipanteAF__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ParticRankingElite__c.field-meta.xml
<CustomField>
    <fullName>V_ParticRankingElite__c</fullName>
    <formula>AND(TEXT( V_Participante__r.FieloPLT__Status__c ) = &apos;Active&apos;,
TEXT( V_Participante__r.V_NovoContratado__c) = &apos;Não&apos;,
NOT(CONTAINS( UPPER( V_Participante__r.Name), &apos;TESTE&apos;)),
(V_PapelElite__c &lt;&gt; &apos;NÃO ELEGÍVEL&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Participa Ranking Elite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <description>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</description>
    <formula>V_AnoFiscal__r.V_Vigente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/VN_MetasParticipantes__c.object-meta.xml
<CustomObject>
    <description>Cadastro de metas mês a mês do ano fiscal dos participantes.</description>
    <label>Meta do Participante - OLD</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes - OLD</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ParticRankingElite__c.field-meta.xml
<CustomField>
    <fullName>V_ParticRankingElite__c</fullName>
    <description>Utilizado para indicar se é participante do Ranking do Elite ou não. Não participa se o participante estiver &quot;Inativo&quot; OU tiver &quot;Teste&quot; em seu nome.</description>
    <formula>AND(

TEXT( V_Participante__r.FieloPLT__Status__c ) = &apos;Active&apos;,
NOT(CONTAINS( UPPER( V_Participante__r.Name), &apos;TESTE&apos;))

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Utilizado para indicar se é participante do Ranking do Elite ou não. Não participa se o participante estiver &quot;Inativo&quot; OU tiver &quot;Teste&quot; em seu nome.</inlineHelpText>
    <label>Participante - Ranking Elite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ProcessarCalculosDecimoSegundoMesAF__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarCalculosDecimoSegundoMesAF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Os cálculos dos índices do respectivo mês serão executados pela aplicação somente após o preenchimento desse campo para Verdadeiro.</description>
    <inlineHelpText>Os cálculos dos índices do respectivo mês serão executados pela aplicação somente após o preenchimento desse campo para Verdadeiro.</inlineHelpText>
    <label>Processar Cálculos - Mês 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <description>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</description>
    <formula>V_GerenciadorMetasAF__r.V_Vigente__c</formula>
    <inlineHelpText>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/VN_Sumarizador__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por sumarizar as metas, resultados e ponderados das informações carregas ou atualizadas.</description>
    <label>Sumarizador</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Código do Sumarizador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sumarizadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Mes__c.field-meta.xml
<CustomField>
    <fullName>V_Mes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Faz referência ao mês corrente da meta</description>
    <label>Mês Meta</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_MetaDoParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_MetaDoParticipante__c</fullName>
    <description>Meta dos participantes</description>
    <label>Meta do Participante</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipName>VN_SumarizadoresDosObjetivos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ProcessarCalculos__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarCalculos__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Ao ser assinalado esse campo, os workflows de cálculo do registro serão acionados.</description>
    <inlineHelpText>Ao ser assinalado esse campo, os workflows de cálculo do registro serão acionados.</inlineHelpText>
    <label>Processar Cálculos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SX_ProcessamentosController.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 11/09/2018
* 
* Name: SX_ProcessamentosController.cls
* 
* Classe qua alimenta a page SX_Processamentos
*******************************************************************************/
public with sharing class SX_ProcessamentosController {

    final private String VALIDACAO_MES_ANO = 'É necessário preencher o Mês e o Ano Fiscal para possibilitar esse processamento';
    final private String VALIDACAO_ANO = 'É necessário preencher o Ano Fiscal para possibilitar esse processamento';
    final private String VALIDACAO_SEM_VIGENCIA = 'Não encontamos Metas vigentes para realizar o cálculo';
    private String PRIMEIRO = 'Primeiro';
    private String SEGUNDO = 'Segundo';
    private String TERCEIRO = 'Terceiro';
    private String QUARTO = 'Quarto';
    private String QUINTO = 'Quinto';
    private String SEXTO = 'Sexto';
    private String SETIMO = 'Setimo';
    private String OITAVO = 'Oitavo';
    private String NONO = 'Nono';
    private String DECIMO = 'Decimo';
    public static String DECIMO_PRIMEIRO = 'DecimoPrimeiro';
    public static String DECIMO_SEGUNDO = 'DecimoSegundo';

    public String fMesCalculos {get; set;}
    public String fMesMecanica {get; set;}

    public Boolean fProcessarCalculos {get; set;}
    public Boolean fProcessarAnoFiscal {get; set;}
    public Boolean fProcessarMecanica {get; set;}
    public Boolean fProcessarLanceGanhador {get; set;}
    public Boolean fProcessarSumarizadores {get; set;}


    public String fAnoFiscal {
        get{
            List<VN_GerenciadorMetaParticipanteAF__c> lLstGeren = [SELECT V_AnoFiscal__c 
                                                                FROM VN_GerenciadorMetaParticipanteAF__c
                                                                WHERE V_Vigente__c = true];
            return !lLstGeren.isEmpty() ? lLstGeren[0].V_AnoFiscal__c : '-';
        } 
        set;
    }  

    public SX_ProcessamentosController(){

        fProcessarCalculos = false;
        fProcessarAnoFiscal = false;
        fProcessarMecanica = false;
        fProcessarLanceGanhador = false;
        fProcessarSumarizadores = false;
    }

    public void processarCalculos(){

        if(String.isEmpty(fAnoFiscal) || String.isEmpty(fMesCalculos)){
            SX_Utils.addError(VALIDACAO_MES_ANO);
            return;
        }

        SX_BatchProcessarCalculos lBatch = new SX_BatchProcessarCalculos(fAnoFiscal, Integer.valueOf(fMesCalculos)); 
        Database.executeBatch(lBatch); 
        fMesCalculos = '';
        fProcessarCalculos = true;
    }

    public void processarAnoFiscalConcluido(){

        //if(String.isEmpty(fAnoFiscal)){
        //  SX_Utils.addError(VALIDACAO_ANO);
        //  return;
        //}

        //List<AggregateResult> lLstAgg =  [SELECT COUNT(Id) total
        //                  FROM VN_MetasParticipantes__c
        //                  WHERE Name =: fAnoFiscal
        //                  AND V_ProcessarCalculosDecimoSegundoMesAF__c = false];
        //Integer lTotal = lLstAgg != null ? Integer.valueOf(lLstAgg[0].get('total')) : 0; 
        //if(lTotal > 0){
        //  SX_Utils.addError(Label.V_MensagemAnoFiscal12Mes);
        //  return;
        //}

        //SX_BatchAnoFiscalConcluido lBatch = new SX_BatchAnoFiscalConcluido(fAnoFiscal); 
  //      Database.executeBatch(lBatch); 
  //      fProcessarAnoFiscal = true;
    }

    public void processarMecanica(){

        if(String.isEmpty(fAnoFiscal) || String.isEmpty(fMesMecanica)){
            SX_Utils.addError(VALIDACAO_MES_ANO);
            return;
        }
        Integer lMes = Integer.valueOf(fMesMecanica);

        // String lQuery = 'SELECT COUNT(Id) total '+
        //              'FROM VN_MetasParticipantes__c '+
        //              'WHERE Name = \''+ fAnoFiscal+'\' '+
        //              'AND V_ProcessarCalculos' + fMesMecanica + 'MesAF__c = false';

        // Nova estrutura
        String lQuery = 'SELECT COUNT(Id) total '+
                        'FROM VN_Sumarizador__c '+
                        'WHERE V_MetaDoParticipante__r.Name = \'' + fAnoFiscal +'\' '+
                        'AND V_Mes__c = ' + lMes +
                        ' AND V_ProcessarCalculos__c = false';

        List<AggregateResult> lLstAgg =  (list<AggregateResult>) Database.query(lQuery);
        Integer lTotal = lLstAgg != null ? Integer.valueOf(lLstAgg[0].get('total')) : 0; 
        if(lTotal > 0){
            SX_Utils.addError(Label.V_MensagemProcessarMecanica);
            return;
        }

        //SX_BatchProcessarMecanica lBatch = new SX_BatchProcessarMecanica(fAnoFiscal, fMesMecanica);
        SX_BatchProcessarMecanica lBatch = new SX_BatchProcessarMecanica(fAnoFiscal, lMes);
        Database.executeBatch(lBatch, 2); 
        fProcessarMecanica = true;
    }

    public void processarLanceGanhador(){

        SX_BatchLanceGanhador lBatch = new SX_BatchLanceGanhador(); 
        Database.executeBatch(lBatch); 
        fProcessarLanceGanhador = true;
    }

    public void processarSumarizadores(){
        Database.executeBatch(new SX_BatchAtualizarSumarizador());
        fProcessarSumarizadores = true;
    }


    public  List<SelectOption> getMesDesejado() { 
        // List<SelectOption> lLstOption = new List<SelectOption>();
        // lLstOption.add(new SelectOption('', 'Selecione'));
        // lLstOption.add(new SelectOption(PRIMEIRO, Label.V_PrimeiroMes));
        // lLstOption.add(new SelectOption(SEGUNDO, Label.V_SegundoMes));
        // lLstOption.add(new SelectOption(TERCEIRO, Label.V_TerceiroMes));
        // lLstOption.add(new SelectOption(QUARTO, Label.V_QuartoMes));
        // lLstOption.add(new SelectOption(QUINTO, Label.V_QuintoMes));
        // lLstOption.add(new SelectOption(SEXTO, Label.V_SextoMes));
        // lLstOption.add(new SelectOption(SETIMO, Label.V_SetimoMes));
        // lLstOption.add(new SelectOption(OITAVO, Label.V_OitavoMes));
        // lLstOption.add(new SelectOption(NONO, Label.V_NonoMes));
        // lLstOption.add(new SelectOption(DECIMO, Label.V_DecimoMes));
        // lLstOption.add(new SelectOption(DECIMO_PRIMEIRO, Label.V_DecimoPrimeiroMes));
        // lLstOption.add(new SelectOption(DECIMO_SEGUNDO, Label.V_DecimoSegundoMes));
        // return lLstOption;

        //Nova estrutura
        List<SelectOption> lLstOption = new List<SelectOption>();
        lLstOption.add(new SelectOption('', 'Selecione'));
        lLstOption.add(new SelectOption('1', Label.V_PrimeiroMes));
        lLstOption.add(new SelectOption('2', Label.V_SegundoMes));
        lLstOption.add(new SelectOption('3', Label.V_TerceiroMes));
        lLstOption.add(new SelectOption('4', Label.V_QuartoMes));
        lLstOption.add(new SelectOption('5', Label.V_QuintoMes));
        lLstOption.add(new SelectOption('6', Label.V_SextoMes));
        lLstOption.add(new SelectOption('7', Label.V_SetimoMes));
        lLstOption.add(new SelectOption('8', Label.V_OitavoMes));
        lLstOption.add(new SelectOption('9', Label.V_NonoMes));
        lLstOption.add(new SelectOption('10', Label.V_DecimoMes));
        lLstOption.add(new SelectOption('11', Label.V_DecimoPrimeiroMes));
        lLstOption.add(new SelectOption('12', Label.V_DecimoSegundoMes));
        return lLstOption;
    }
    
    public void recalcularRanking(){

        List<VN_MetaParticipante__c> metas = [SELECT Name FROM VN_MetaParticipante__c where V_ParticRankingElite__c = true];
        Set<String> lSetAnoFiscal = new Set<String>();
    
        for (VN_MetaParticipante__c meta : metas) {
            lSetAnoFiscal.add(meta.Name);
        }

        if(!lSetAnoFiscal.isEmpty()){
            Decimal lRandomNumber = Integer.valueof((Math.random() * 1000000));
            System.scheduleBatch ( new SX_BatchAtualizarRankingNaMeta(lSetAnoFiscal),'Atualizar posição ranking '+lRandomNumber, 1); 
        }
    }
}