force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/VN_GerenciadorMetaParticipanteAF__c.object-meta.xml
<CustomObject>
    <description>Gerenciador dos registros de metas dos participantes por Ano Fiscal.</description>
    <label>Gerenciador Meta Participante AF</label>
    <nameField>
        <displayFormat>GMAF-{000000}</displayFormat>
        <label>No. Gerenciador Ano Fiscal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gerenciador Metas Participantes AF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_CriarAnoFiscalParticipantes__c.field-meta.xml
<CustomField>
    <fullName>V_CriarAnoFiscalParticipantes__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que servirá de gatilho para a criação de registros do Ano Fiscal para os participantes.</description>
    <inlineHelpText>Campo que servirá de gatilho para a criação de registros do Ano Fiscal para os participantes.</inlineHelpText>
    <label>Criar Ano Fiscal para os Participantes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SX_GerenciadorMetaParticipanteAF_After.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 14/09/2018
* 
* Name: SX_GerenciadorMetaParticipanteAF_After.cls
* 
* Classe manipuladora da trigger after de VN_GerenciadorMetaParticipanteAF__c
*******************************************************************************/
public with sharing class SX_GerenciadorMetaParticipanteAF_After {

	public static void criarMetas() {
		
		VN_TriggerCheck.assert();

		Map<Id, VN_GerenciadorMetaParticipanteAF__c> lMapGerenciador = new Map<Id, VN_GerenciadorMetaParticipanteAF__c>();
	  	for (VN_GerenciadorMetaParticipanteAF__c gerenciador : (List<VN_GerenciadorMetaParticipanteAF__c>) trigger.new) {

	  		if(VN_TriggerCheck.isChangedTo(gerenciador, VN_GerenciadorMetaParticipanteAF__c.V_CriarAnoFiscalParticipantes__c, true)){
	  			lMapGerenciador.put(gerenciador.Id, gerenciador);
	  		}
	  	}
	  	if(lMapGerenciador.isEmpty()) return;

	  	Database.executeBatch(new SX_BatchCriarMetas(lMapGerenciador), 200);
	}
}