force-app/main/default/objects/VN_ResumoCargasDadosTemp__c/VN_ResumoCargasDadosTemp__c.object-meta.xml
<CustomObject>
    <description>Carga de dados temporária das integrações com o Fielo.</description>
    <label>Resumo Carga de Dados Temp</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>No. Resumo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resumos Cargas de Dados Temp</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_ResumoCargasDadosTemp__c/fields/V_StatusPDI__c.field-meta.xml
<CustomField>
    <fullName>V_StatusPDI__c</fullName>
    <description>Status de processamento do arquivo recebido (processo automático).</description>
    <inlineHelpText>Status do ETL, aplicação que importa a carga de consumo (processo automático).</inlineHelpText>
    <label>Status do PDI</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Carregando</fullName>
                <default>true</default>
                <label>Carregando</label>
            </value>
            <value>
                <fullName>Carregado</fullName>
            </value>
            <value>
                <fullName>Validado Com Erro</fullName>
            </value>
            <value>
                <fullName>Validado Sem Erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VN_ResumoCargasDadosTempHandler.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: PV                                           date: 01/11/2019
* 
* Name: VN_ResumoCargasDadosTempHandler.cls
* 
* Handler trigger de VN_ResumoCargasDadosTemp__c
*******************************************************************************/
public with sharing class VN_ResumoCargasDadosTempHandler {
    
    public static void processarSumarizadores(){
        VN_TriggerCheck.assert();
        
        for(VN_ResumoCargasDadosTemp__c rcd : (List<VN_ResumoCargasDadosTemp__c>)Trigger.new){
            if(VN_TriggerCheck.isChangedTo(rcd, VN_ResumoCargasDadosTemp__c.V_StatusPDI__c, 'Carregado')){
                Database.executeBatch(new SX_BatchAtualizarSumarizador());
            }
        }
    }
}