force-app/main/default/objects/FieloPLT__Badge__c/FieloPLT__Badge__c.object-meta.xml
<CustomObject>
    <description>Badges are distinctive marks which represent a particular achievement earned by Members.</description>
    <label>Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Badge__c/fields/FieloPLT__Image__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Image__c</fullName>
    <description>Badge Image (Document, Attachment or URL).</description>
    <inlineHelpText>Choose a Badge image (upload an image or enter URL).</inlineHelpText>
    <label>Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Badge__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>It shows the available status for Badges: Draft, Active and Inactive.</description>
    <inlineHelpText>Choose a Badge status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Badge__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <label>Cargo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COORDENADOR | GERENTE REGIONAL VIP</fullName>
            </value>
            <value>
                <fullName>DIRETOR</fullName>
            </value>
            <value>
                <fullName>GERENTE DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Badge__c/fields/V_PapelSalesPersonYear__c.field-meta.xml
<CustomField>
    <fullName>V_PapelSalesPersonYear__c</fullName>
    <label>Papel Sales Person Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GERENTES DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDERES (COORDENADORES) E GERENTE REGIONAIS</fullName>
            </value>
            <value>
                <fullName>DIRETORES</fullName>
            </value>
            <value>
                <fullName>NÃO ELEGÍVEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Badge__c/fields/V_Pontos__c.field-meta.xml
<CustomField>
    <fullName>V_Pontos__c</fullName>
    <description>Pontos equivalentes da badge.</description>
    <inlineHelpText>Pontos equivalentes da badge.</inlineHelpText>
    <label>Pontos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__BadgeMember__c/FieloPLT__BadgeMember__c.object-meta.xml
<CustomObject>
    <description>It links a specific Badge with the particular Member who has obtained a Badge.</description>
    <label>Badge Member</label>
    <nameField>
        <label>Badge Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badge Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__BadgeMember__c/fields/FieloPLT__Badge__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Badge__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Badge granted to a Member.</description>
    <inlineHelpText>Badge granted to a Member.</inlineHelpText>
    <label>Badge</label>
    <referenceTo>FieloPLT__Badge__c</referenceTo>
    <relationshipName>BadgesMembers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__BadgeMember__c/fields/FieloPLT__ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__ExpirationDate__c</fullName>
    <description>Date after which the Badge is no longer valid for the Member.</description>
    <inlineHelpText>Date after which the Badge is no longer valid for the Member.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FieloPLT__BadgeMember__c/fields/FieloPLT__Member__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Member who obtained a Badge.</description>
    <inlineHelpText>Member who obtained a Badge.</inlineHelpText>
    <label>Member</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipName>BadgesMembers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__BadgeMember__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Shows the status of the Badge given to that specific Member.</description>
    <inlineHelpText>Choose the status of the Badge given to that specific Member.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reverted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__BadgeMember__c/fields/V_Pontos__c.field-meta.xml
<CustomField>
    <fullName>V_Pontos__c</fullName>
    <description>Pontos equivalentes da badge no momento em que foi atribuída para o participante.</description>
    <inlineHelpText>Pontos equivalentes da badge no momento em que foi atribuída para o participante.</inlineHelpText>
    <label>Pontos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Image__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Image__c</fullName>
    <description>Member image.</description>
    <inlineHelpText>Member image.</inlineHelpText>
    <label>Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</description>
    <inlineHelpText>Choose Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Area__c.field-meta.xml
<CustomField>
    <fullName>V_Area__c</fullName>
    <description>Área do participante.</description>
    <inlineHelpText>Área do participante.</inlineHelpText>
    <label>Área</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VERTICAIS</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo atual do participante.</description>
    <inlineHelpText>Cargo atual do participante.</inlineHelpText>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COORDENADOR | GERENTE REGIONAL VIP</fullName>
            </value>
            <value>
                <fullName>DIRETOR</fullName>
            </value>
            <value>
                <fullName>GERENTE DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDER</fullName>
            </value>
            <value>
                <fullName>COORDENADOR II</fullName>
                <isActive>false</isActive>
                <label>COORDENADOR II</label>
            </value>
            <value>
                <fullName>GERENTE DE VENDAS</fullName>
                <isActive>false</isActive>
                <label>GERENTE DE VENDAS</label>
            </value>
            <value>
                <fullName>VICE-PRESIDENTE</fullName>
                <isActive>false</isActive>
                <label>VICE-PRESIDENTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Lideranca__c.field-meta.xml
<CustomField>
    <fullName>V_Lideranca__c</fullName>
    <description>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</description>
    <inlineHelpText>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</inlineHelpText>
    <label>Liderança</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>MULTI SECTOR</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
            <value>
                <fullName>VAREJO, CPG E PAGAMENTOS</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS</fullName>
            </value>
            <value>
                <fullName>SERASA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_LiderImediato__c.field-meta.xml
<CustomField>
    <fullName>V_LiderImediato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Líder imediato atual do participante.</description>
    <inlineHelpText>Líder imediato atual do participante.</inlineHelpText>
    <label>Líder Imediato</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Liderados Imediatos</relationshipLabel>
    <relationshipName>Lider_Imediato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_PapelSalesPersonYear__c.field-meta.xml
<CustomField>
    <fullName>V_PapelSalesPersonYear__c</fullName>
    <label>Papel Sales Person of the Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GERENTES DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDERES (COORDENADORES) E GERENTE REGIONAIS</fullName>
            </value>
            <value>
                <fullName>NÃO ELEGÍVEL</fullName>
                <default>true</default>
                <label>NÃO ELEGÍVEL</label>
            </value>
            <value>
                <fullName>DIRETORES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SX_SpyTeamPerformanceController.cls
public with sharing class SX_SpyTeamPerformanceController {
	
	@AuraEnabled
    public static FieloPLT__Member__c getMember() {
        List<FieloPLT__Member__c> lMemberLst = [SELECT Id
								                FROM FieloPLT__Member__c
								                WHERE FieloPLT__User__c =: UserInfo.getUserId()];

	    return lMemberLst.isEmpty() ? null : lMemberLst[0];         
    }

	// @AuraEnabled
	// public static List<Map<String, String>> getPapel(String aIdMember) {

	//     Map<String, Map<String, String>> lMapPapel = new Map<String, Map<String, String>>();
	//     for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
	// 		if(member.V_PapelSalesPersonYear__c == 'NÃO ELEGÍVEL') continue;
	//         lMapPapel.put(member.V_PapelSalesPersonYear__c, new Map<String, String>{'value' => member.V_PapelSalesPersonYear__c, 'label' => member.V_PapelSalesPersonYear__c});
	//     }
	//     return lMapPapel.values();
	// }

    @AuraEnabled
	public static List<Map<String, String>> getArea(String aIdMember) {

	    Map<String, Map<String, String>> lMapArea = new Map<String, Map<String, String>>();
	    for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
	        lMapArea.put(member.V_Area__c, new Map<String, String>{'value' => member.V_Area__c, 'label' => member.V_Area__c});
	    }
	    return lMapArea.values();
	}
	@AuraEnabled
	public static List<Map<String, String>> getSubArea(String aIdMember) {

	    Map<String, Map<String, String>> lMapSubArea = new Map<String, Map<String, String>>();
	    for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
	        lMapSubArea.put(member.V_Lideranca__c, new Map<String, String>{'value' => member.V_Lideranca__c, 'label' => member.V_Lideranca__c});
	    }
	    return lMapSubArea.values();
	}

	@AuraEnabled
	public static List<Map<String, String>> getBadges() {

	    Map<String, Map<String, String>> lMapBadges = new Map<String, Map<String, String>>();
	    for(FieloPLT__Badge__c badge: [SELECT Id, Name, FieloPLT__Image__c, V_Pontos__c FROM FieloPLT__Badge__c 
				WHERE FieloPLT__Status__c = 'Active' ORDER BY Name]){
	    	lMapBadges.put(badge.Name, new Map<String, String>{'value' => badge.Name, 'label' => badge.Name});
	    }
	    return lMapBadges.values();
	}

	@AuraEnabled
    public static List<Badge> getBadgesPerformance(String aArea, String aLideranca, String aBadge, String aPalavraChave, String aIdMember){

        Set<Id> lSetMember = new Set<Id>();
        for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
        	lSetMember.add(member.Id);
        }

    	String lQuery = 'SELECT Id, FieloPLT__Member__c, FieloPLT__Member__r.Name, FieloPLT__Badge__r.Name, FieloPLT__Badge__r.V_Pontos__c' +
					 	' FROM FieloPLT__BadgeMember__c' +
					 	' WHERE FieloPLT__Member__c = :lSetMember'+
					 	' AND FieloPLT__Status__c != \'Reverted\''+
					 	' AND FieloPLT__Badge__r.FieloPLT__Status__c = \'Active\''+
					 	' AND (FieloPLT__ExpirationDate__c = null OR FieloPLT__ExpirationDate__c >= TODAY)';

		if(String.isNotEmpty(aPalavraChave)){
			lQuery += ' AND FieloPLT__Member__r.Name like \'%' + aPalavraChave + '%\'';
		}

		if(String.isNotEmpty(aArea)){
			lQuery += ' AND FieloPLT__Member__r.V_Area__c = \'' + aArea + '\'';
		}

		if(String.isNotEmpty(aLideranca)){
			lQuery += ' AND FieloPLT__Member__r.V_Lideranca__c = \'' + aLideranca + '\'';
		}

		if(String.isNotEmpty(aBadge)){
			lQuery += ' AND FieloPLT__Badge__r.Name = \'' + aBadge + '\'';
		}

		lQuery +=' ORDER BY FieloPLT__Member__r.Name';

		Map<String, Badge> lMapBadge = new Map<String, Badge>();
		for(FieloPLT__BadgeMember__c badgeMember: (List<FieloPLT__BadgeMember__c>)database.query(lQuery)){

			Badge lBadge = lMapBadge.get(badgeMember.FieloPLT__Member__c);
			if(lBadge == null){
				lBadge = new Badge();
				lBadge.wMember =  badgeMember.FieloPLT__Member__r.Name;
				lBadge.wNumBages = 1;
				lBadge.wPontuacao = badgeMember.FieloPLT__Badge__r.V_Pontos__c != null ? badgeMember.FieloPLT__Badge__r.V_Pontos__c : 0;
			} else {
				lBadge.wNumBages ++;
				lBadge.wPontuacao += badgeMember.FieloPLT__Badge__r.V_Pontos__c != null ? badgeMember.FieloPLT__Badge__r.V_Pontos__c : 0;
			}
			lMapBadge.put(badgeMember.FieloPLT__Member__c, lBadge);
		}
		return lMapBadge.values();
	}

	public class Badge{

		@AuraEnabled public String wMember {get; set;}
		@AuraEnabled public Integer wNumBages {get; set;}
		@AuraEnabled public Decimal wPontuacao {get; set;}
	}

	private static List<FieloPLT__Member__c> loadMembers(String aIdMember){
		return [SELECT Id, V_Cargo__c, V_Area__c, V_Lideranca__c, V_PapelSalesPersonYear__c
	            FROM FieloPLT__Member__c
	            WHERE (V_LiderImediato__c  =: aIdMember
	             OR V_LiderImediato__r.V_LiderImediato__c =: aIdMember
	             OR V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__c =: aIdMember
	             OR V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__c =: aIdMember
	             OR V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__c =: aIdMember)
				 AND V_PapelSalesPersonYear__c != 'NÃO ELEGÍVEL'];
	}
}