force-app/main/default/objects/FieloPLT__Badge__c/FieloPLT__Badge__c.object-meta.xml
<CustomObject>
    <description>Badges are distinctive marks which represent a particular achievement earned by Members.</description>
    <label>Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Badge__c/fields/FieloPLT__Image__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Image__c</fullName>
    <description>Badge Image (Document, Attachment or URL).</description>
    <inlineHelpText>Choose a Badge image (upload an image or enter URL).</inlineHelpText>
    <label>Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Badge__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>It shows the available status for Badges: Draft, Active and Inactive.</description>
    <inlineHelpText>Choose a Badge status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Badge__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <label>Cargo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COORDENADOR | GERENTE REGIONAL VIP</fullName>
            </value>
            <value>
                <fullName>DIRETOR</fullName>
            </value>
            <value>
                <fullName>GERENTE DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Badge__c/fields/V_Classificacao__c.field-meta.xml
<CustomField>
    <fullName>V_Classificacao__c</fullName>
    <description>Classificação da badge.</description>
    <label>Classificação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Engajamento</fullName>
            </value>
            <value>
                <fullName>Youbet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Badge__c/fields/V_Ordem__c.field-meta.xml
<CustomField>
    <fullName>V_Ordem__c</fullName>
    <description>Campo utilizado para ordenar a badge no portal.</description>
    <inlineHelpText>Campo utilizado para ordenar a badge no portal.</inlineHelpText>
    <label>Ordem</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Badge__c/fields/V_PapelSalesPersonYear__c.field-meta.xml
<CustomField>
    <fullName>V_PapelSalesPersonYear__c</fullName>
    <label>Papel Sales Person Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GERENTES DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDERES (COORDENADORES) E GERENTE REGIONAIS</fullName>
            </value>
            <value>
                <fullName>DIRETORES</fullName>
            </value>
            <value>
                <fullName>NÃO ELEGÍVEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Badge__c/fields/V_Pontos__c.field-meta.xml
<CustomField>
    <fullName>V_Pontos__c</fullName>
    <description>Pontos equivalentes da badge.</description>
    <inlineHelpText>Pontos equivalentes da badge.</inlineHelpText>
    <label>Pontos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__BadgeMember__c/FieloPLT__BadgeMember__c.object-meta.xml
<CustomObject>
    <description>It links a specific Badge with the particular Member who has obtained a Badge.</description>
    <label>Badge Member</label>
    <nameField>
        <label>Badge Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badge Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__BadgeMember__c/fields/FieloPLT__Badge__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Badge__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Badge granted to a Member.</description>
    <inlineHelpText>Badge granted to a Member.</inlineHelpText>
    <label>Badge</label>
    <referenceTo>FieloPLT__Badge__c</referenceTo>
    <relationshipName>BadgesMembers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__BadgeMember__c/fields/FieloPLT__ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__ExpirationDate__c</fullName>
    <description>Date after which the Badge is no longer valid for the Member.</description>
    <inlineHelpText>Date after which the Badge is no longer valid for the Member.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FieloPLT__BadgeMember__c/fields/FieloPLT__Member__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Member who obtained a Badge.</description>
    <inlineHelpText>Member who obtained a Badge.</inlineHelpText>
    <label>Member</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipName>BadgesMembers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__BadgeMember__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Shows the status of the Badge given to that specific Member.</description>
    <inlineHelpText>Choose the status of the Badge given to that specific Member.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reverted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__BadgeMember__c/fields/V_Classificacao__c.field-meta.xml
<CustomField>
    <fullName>V_Classificacao__c</fullName>
    <description>Classificação da badge.</description>
    <formula>TEXT( FieloPLT__Badge__r.V_Classificacao__c )</formula>
    <inlineHelpText>Classificação da badge.</inlineHelpText>
    <label>Classificação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__BadgeMember__c/fields/V_Pontos__c.field-meta.xml
<CustomField>
    <fullName>V_Pontos__c</fullName>
    <description>Pontos equivalentes da badge no momento em que foi atribuída para o participante.</description>
    <inlineHelpText>Pontos equivalentes da badge no momento em que foi atribuída para o participante.</inlineHelpText>
    <label>Pontos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Image__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Image__c</fullName>
    <description>Member image.</description>
    <inlineHelpText>Member image.</inlineHelpText>
    <label>Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</description>
    <inlineHelpText>Choose Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo atual do participante.</description>
    <inlineHelpText>Cargo atual do participante.</inlineHelpText>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COORDENADOR | GERENTE REGIONAL VIP</fullName>
            </value>
            <value>
                <fullName>DIRETOR</fullName>
            </value>
            <value>
                <fullName>GERENTE DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDER</fullName>
            </value>
            <value>
                <fullName>COORDENADOR II</fullName>
                <isActive>false</isActive>
                <label>COORDENADOR II</label>
            </value>
            <value>
                <fullName>GERENTE DE VENDAS</fullName>
                <isActive>false</isActive>
                <label>GERENTE DE VENDAS</label>
            </value>
            <value>
                <fullName>VICE-PRESIDENTE</fullName>
                <isActive>false</isActive>
                <label>VICE-PRESIDENTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_PapelSalesPersonYear__c.field-meta.xml
<CustomField>
    <fullName>V_PapelSalesPersonYear__c</fullName>
    <label>Papel Sales Person of the Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GERENTES DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDERES (COORDENADORES) E GERENTE REGIONAIS</fullName>
            </value>
            <value>
                <fullName>NÃO ELEGÍVEL</fullName>
                <default>true</default>
                <label>NÃO ELEGÍVEL</label>
            </value>
            <value>
                <fullName>DIRETORES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SX_SpyHomeController.cls
public with sharing class SX_SpyHomeController {
	
	@AuraEnabled
	public static FieloPLT__Member__c getMember() {
		List<FieloPLT__Member__c> lMemberLst = [SELECT Id, V_Cargo__c, V_PapelSalesPersonYear__c
					FROM FieloPLT__Member__c
					WHERE FieloPLT__User__c =: UserInfo.getUserId()];

		return lMemberLst.isEmpty() ? null : lMemberLst[0];         
	}

	@AuraEnabled
	public static List<Badge> getBadges(String aIdMember, String aType, String aCargo) {

		Map<Id, Badge> lMapBadge = new Map<Id, Badge>();
		List<Badge> lLstBadge = new List<Badge>();

		for(FieloPLT__Badge__c badge: [SELECT Id, Name, FieloPLT__Image__c, V_Pontos__c FROM FieloPLT__Badge__c 
				WHERE V_Classificacao__c =: aType AND (V_PapelSalesPersonYear__c = NULL OR V_PapelSalesPersonYear__c =: aCargo )
				AND FieloPLT__Status__c = 'Active' ORDER BY V_Ordem__c ASC NULLS LAST]){

			Badge lBadge = new Badge(); 
			lBadge.wImgURL = Label.V_SiteURL + badge.FieloPLT__Image__c;
			lBadge.wShowColor = false;
			lBadge.wName = badge.Name;
			lMapBadge.put(badge.Id,  lBadge);
			lLstBadge.add(lBadge);
		}

		for(FieloPLT__BadgeMember__c badgeMember: [SELECT Id, FieloPLT__Badge__c FROM FieloPLT__BadgeMember__c WHERE FieloPLT__Badge__c =: lMapBadge.keySet() 
				AND FieloPLT__Member__c =: aIdMember AND FieloPLT__Status__c != 'Reverted' AND (FieloPLT__ExpirationDate__c = null OR FieloPLT__ExpirationDate__c >= TODAY)]){
			Badge lBadge = lMapBadge.get(badgeMember.FieloPLT__Badge__c);
			if(lBadge == null) continue;
			lBadge.wShowColor = true;
		}
		return lMapBadge.values(); 
	}

	@AuraEnabled
	public static String getMyBadges(String aIdMember, String aType) {

		List<AggregateResult> lLstAgg = [SELECT COUNT(Id) total FROM FieloPLT__BadgeMember__c WHERE FieloPLT__Member__c =: aIdMember
				AND FieloPLT__Status__c != 'Reverted' AND (FieloPLT__ExpirationDate__c = null OR FieloPLT__ExpirationDate__c >= TODAY)
				AND FieloPLT__Badge__r.FieloPLT__Status__c = 'Active' AND FieloPLT__Badge__r.V_Classificacao__c =: aType];
		Integer lTotalBadges = !lLstAgg.isEmpty() ? Integer.valueOf(lLstAgg[0].get('total')) : 0;

		return lTotalBadges < 10 ? '0'+String.valueOf(lTotalBadges) : String.valueOf(lTotalBadges);
	}

	 public class Badge{

		@AuraEnabled public String wImgURL {get; set;}
		@AuraEnabled public String wName {get; set;}
		@AuraEnabled public Boolean wShowColor {get; set;}
	}

}