force-app/main/default/objects/VN_LogBatch__c/VN_LogBatch__c.object-meta.xml
<CustomObject>
    <label>Log Batch</label>
    <nameField>
        <displayFormat>Log - {00000000}</displayFormat>
        <label>Nome de Log Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs Batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_LogBatch__c/fields/V_ErroResultado__c.field-meta.xml
<CustomField>
    <fullName>V_ErroResultado__c</fullName>
    <label>Erro Resultado</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VN_LogBatch__c/fields/V_IdBatch__c.field-meta.xml
<CustomField>
    <fullName>V_IdBatch__c</fullName>
    <label>Id Batch</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_LogBatch__c/fields/V_Processo__c.field-meta.xml
<CustomField>
    <fullName>V_Processo__c</fullName>
    <label>Processo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_AnoFiscalConcluido__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscalConcluido__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ano Fiscal Concluido</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SX_BatchAnoFiscalConcluido.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 11/09/2018
* 
* Batch para atualozar os campos "Ano Fiscal Concluído" do Participante
*******************************************************************************/
global class SX_BatchAnoFiscalConcluido implements Database.Batchable<sObject>, Database.Stateful {

	global String fAnoFiscal;
	global String fMsgErro;
	
	global SX_BatchAnoFiscalConcluido(String aAno) {

		if(SX_Utils.batchIsProcessing('SX_BatchAnoFiscalConcluido')) return;
		fAnoFiscal = aAno;
		fMsgErro = '';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {

		return Database.getQueryLocator([SELECT Id, V_AnoFiscalConcluido__c
										FROM VN_MetaParticipante__c
										WHERE Name =: fAnoFiscal]);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {

   		if ( scope == null || scope.isEmpty()) return; 
   		List<VN_MetaParticipante__c> lLstMetas = ( List<VN_MetaParticipante__c> ) scope; 

   		for(VN_MetaParticipante__c metas: lLstMetas){
   			metas.V_AnoFiscalConcluido__c = true;
   		}

   		Database.SaveResult[] lLstResult = database.update(lLstMetas, false);
	  	 
	  	for(integer i=0; i < lLstResult.size(); i++) {
	 	
	 	    Database.SaveResult lResult = lLstResult[i];
	 	    VN_MetaParticipante__c lMetas = lLstMetas[i];	 	
	 	    if(lMetas == null) continue;
	 	    
	 	    if (!lResult.isSuccess()){
		  		for(Database.Error err : lResult.getErrors()) {
		  		 	fMsgErro += ' { ' + lMetas.Id +' }: '+err.getMessage()+' --FIM-- ';
			    }
		    }  
	  	}   	
	}
	
	global void finish(Database.BatchableContext BC) {

		if(String.isNotEmpty(fMsgErro)){
			insert new VN_LogBatch__c(V_Processo__c = 'Ano Fiscal Concluído',
				 V_IdBatch__c = BC.getJobId(), V_ErroResultado__c = fMsgErro.left(32768));
		}
	}	
}