force-app/main/default/objects/VN_LogBatch__c/VN_LogBatch__c.object-meta.xml
<CustomObject>
    <label>Log Batch</label>
    <nameField>
        <displayFormat>Log - {00000000}</displayFormat>
        <label>Nome de Log Batch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs Batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_LogBatch__c/fields/V_ErroResultado__c.field-meta.xml
<CustomField>
    <fullName>V_ErroResultado__c</fullName>
    <label>Erro Resultado</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VN_LogBatch__c/fields/V_IdBatch__c.field-meta.xml
<CustomField>
    <fullName>V_IdBatch__c</fullName>
    <label>Id Batch</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_LogBatch__c/fields/V_Processo__c.field-meta.xml
<CustomField>
    <fullName>V_Processo__c</fullName>
    <label>Processo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_AMYTDAnterior__c.field-meta.xml
<CustomField>
    <fullName>V_AMYTDAnterior__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Valor do % AM YTD Anterior do mês anterior</description>
    <inlineHelpText>Valor do % AM YTD Anterior do mês anterior</inlineHelpText>
    <label>% AM YTD Anterior</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Meta__c.field-meta.xml
<CustomField>
    <fullName>V_Meta__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Meta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualAM1Semestre__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAM1Semestre__c</fullName>
    <label>% AM - 1º Semestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualAMMes__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAMMes__c</fullName>
    <label>% AM Mês</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualSEMes__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualSEMes__c</fullName>
    <label>% SE Mês</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Persona__c.field-meta.xml
<CustomField>
    <fullName>V_Persona__c</fullName>
    <label>Persona</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ResultadoSE__c.field-meta.xml
<CustomField>
    <fullName>V_ResultadoSE__c</fullName>
    <label>Resultado SE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_UltimoMesAtualizado__c.field-meta.xml
<CustomField>
    <fullName>V_UltimoMesAtualizado__c</fullName>
    <label>Último Mês Atualizado</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Valor__c.field-meta.xml
<CustomField>
    <fullName>V_Valor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/VN_Sumarizador__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por sumarizar as metas, resultados e ponderados das informações carregas ou atualizadas.</description>
    <label>Sumarizador</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Código do Sumarizador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sumarizadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_AMYTDAnterior__c.field-meta.xml
<CustomField>
    <fullName>V_AMYTDAnterior__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Campo que recebe o valor do percentual % AM YTD do mês anterior</description>
    <inlineHelpText>Campo que recebe o valor do percentual % AM YTD do mês anterior</inlineHelpText>
    <label>% AM YTD Anterior</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Mes__c.field-meta.xml
<CustomField>
    <fullName>V_Mes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Faz referência ao mês corrente da meta</description>
    <label>Mês Meta</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_MesString__c.field-meta.xml
<CustomField>
    <fullName>V_MesString__c</fullName>
    <formula>CASE( MCEILING(V_Mes__c) ,
10, &quot;Janeiro&quot;,
11, &quot;Fevereiro&quot;,
12, &quot;Março&quot;,
1, &quot;Abril&quot;,
2, &quot;Maio&quot;,
3, &quot;Junho&quot;,
4, &quot;Julho&quot;,
5, &quot;Agosto&quot;,
6, &quot;Setembro&quot;,
7, &quot;Outubro&quot;,
8, &quot;Novembro&quot;,
9, &quot;Dezembro&quot;,
&quot;Error&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mês String</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Meta__c.field-meta.xml
<CustomField>
    <fullName>V_Meta__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Meta Mensal, sumarização da meta da carga por participante</description>
    <inlineHelpText>Faz referência a Meta mensal do Participante.</inlineHelpText>
    <label>Meta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_MetaDoParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_MetaDoParticipante__c</fullName>
    <description>Meta dos participantes</description>
    <label>Meta do Participante</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipName>VN_SumarizadoresDosObjetivos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_MetaYTDSemestre__c.field-meta.xml
<CustomField>
    <fullName>V_MetaYTDSemestre__c</fullName>
    <formula>IF(AND( V_IDXSemestre__c != V_IDXSemestreAnterior__c, V_IDXSemestre__c =1), V_Meta__c ,
IF( V_IDXSemestre__c = V_IDXSemestreAnterior__c, V_MetaYTDSemestreAnterior__c ,
 V_MetaYTDSemestreAnterior__c + V_Meta__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Meta YTD Semestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_MetaYTDTrimestre__c.field-meta.xml
<CustomField>
    <fullName>V_MetaYTDTrimestre__c</fullName>
    <formula>IF(AND( V_IDXTrimestre__c  != V_IDXTrimestreAnterior__c , V_IDXTrimestre__c &lt;=1), V_Meta__c ,
   IF( V_IDXTrimestre__c = V_IDXTrimestreAnterior__c , V_MetaYTDTrimestreAnterior__c ,
 V_MetaYTDTrimestreAnterior__c + V_Meta__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Meta YTD Trimestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_PercentualAMMes__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAMMes__c</fullName>
    <description>Apresenta o percentual de atingimento da meta pelo participante</description>
    <formula>IF ( V_Meta__c &lt;= 0,0,V_Valor__c  /  V_Meta__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Apresenta o percentual de atingimento da meta.</inlineHelpText>
    <label>% AM Mês</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_PercentualAMYTD__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAMYTD__c</fullName>
    <formula>IF(V_IDXAnoFiscal__c&lt;=0,0,(( V_PercentualAMYTDPeriodo__c * V_IDXAnoFiscalPeriodo__c )+ V_PercentualAMYTDFatorado__c )/ V_IDXAnoFiscal__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% AM YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_PercentualAMYTDSemestre__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAMYTDSemestre__c</fullName>
    <formula>IF(V_IDXSemestre__c &lt;=0,0,(( V_PercentualAMYTDSemestrePeriodo__c * V_IDXSemestrePeriodo__c )+ V_PercentualAMYTDSemestreFatorado__c )/ V_IDXSemestre__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% AM YTD Semestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_PercentualAMYTDTrimestre__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAMYTDTrimestre__c</fullName>
    <formula>IF(V_IDXTrimestre__c &lt;=0 ,0, (( V_PercentualAMYTDTrimestrePeriodo__c * V_IDXTrimestrePeriodo__c )+ V_PercentualAMYTDTrimestreFatorado__c )/ V_IDXTrimestre__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% AM YTD Trimestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_PercentualSEMes__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualSEMes__c</fullName>
    <formula>IF(V_Valor__c &lt;=0,0,V_ResultadoSE__c / V_Valor__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% SE Mês</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Persona__c.field-meta.xml
<CustomField>
    <fullName>V_Persona__c</fullName>
    <formula>IF(V_PercentualAMYTD__c &gt;= 1, &apos;UP&apos;, &apos;DOWN&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Persona</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ProcessarMecanicas__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarMecanicas__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Ao ser assinalado esse campo, as mecânicas de pontos do registro serão acionadas. Esse campo só pode ser assinalado se o campo &quot;Processar Cálculos&quot; já estiver assinalado.</description>
    <inlineHelpText>Ao ser assinalado esse campo, as mecânicas de pontos do registro serão acionadas. Esse campo só pode ser assinalado se o campo &quot;Processar Cálculos&quot; já estiver assinalado.</inlineHelpText>
    <label>Processar Mecânicas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ResultadoSE__c.field-meta.xml
<CustomField>
    <fullName>V_ResultadoSE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Resultado SE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ScoreAMYTD__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreAMYTD__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indica o score Elite de atingimento de meta do participante.</description>
    <inlineHelpText>Indica o score Elite de atingimento de meta do participante.</inlineHelpText>
    <label>Score Atingimento Meta YTD</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ScoreSMQ1__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreSMQ1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indica o score Elite de superação de meta Q1  do participante.</description>
    <inlineHelpText>Indica o score Elite de superação de meta Q1  do participante.</inlineHelpText>
    <label>Score SM Elite Q1</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ScoreSMYTD__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreSMYTD__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indica o score Elite de superação de meta do participante.</description>
    <inlineHelpText>Indica o score Elite de superação de meta do participante.</inlineHelpText>
    <label>Score Superação Meta YTD</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Valor__c.field-meta.xml
<CustomField>
    <fullName>V_Valor__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Sumarizador que faz referência ao resultado atingido pelo participante</description>
    <inlineHelpText>Faz referência ao resultado atingido pelo participante</inlineHelpText>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ValorDisputaComercial__c.field-meta.xml
<CustomField>
    <fullName>V_ValorDisputaComercial__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Campo populado via carga.</description>
    <label>Valor Disputa Comercial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ValorYTDSemestre__c.field-meta.xml
<CustomField>
    <fullName>V_ValorYTDSemestre__c</fullName>
    <formula>IF(AND( V_IDXSemestre__c != V_IDXSemestreAnterior__c , V_IDXSemestre__c =1), V_Valor__c,
   IF( V_IDXSemestre__c = V_IDXSemestreAnterior__c , V_ValorYTDSemestreAnterior__c ,
 V_ValorYTDSemestreAnterior__c  +  V_Valor__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor YTD Semestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ValorYTDTrimestre__c.field-meta.xml
<CustomField>
    <fullName>V_ValorYTDTrimestre__c</fullName>
    <formula>IF(AND( V_IDXTrimestre__c != V_IDXTrimestreAnterior__c , V_IDXTrimestre__c &lt;=1), V_Valor__c ,
   IF( V_IDXTrimestre__c = V_IDXTrimestreAnterior__c , V_ValorYTDTrimestreAnterior__c ,
 V_ValorYTDTrimestreAnterior__c + V_Valor__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor YTD Trimestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SX_BatchProcessarMecanica.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 11/09/2018
* 
* 
* Batch para atualizar os campos "Processar Mecânica" do Participante
*
*******************************************************************************/
global class SX_BatchProcessarMecanica implements Database.Batchable<sObject>, Database.Stateful {

	global String fAnoFiscal;
	global Integer fMonth;
	global String fMsgErro;
	global Set<Id> fSetSumarizadorAtualizado;
	
	global SX_BatchProcessarMecanica(String aAno, Integer aMes) {

		if(SX_Utils.batchIsProcessing('SX_BatchProcessarMecanica')) return;
		fAnoFiscal = aAno;
		fMonth = aMes;
		fMsgErro = '';
		fSetSumarizadorAtualizado = new Set<Id>();
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {

		return Database.getQueryLocator([SELECT V_ProcessarMecanicas__c 
										FROM VN_Sumarizador__c
										WHERE V_MetaDoParticipante__r.Name =: fAnoFiscal 
										AND V_Mes__c =: fMonth 
										AND V_ProcessarMecanicas__c = false]);								
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {

   		if ( scope == null || scope.isEmpty()) return;

		List<VN_Sumarizador__c> lstSumarizador = ( List<VN_Sumarizador__c> ) scope;  
		   for(VN_Sumarizador__c lSumarizador: lstSumarizador){
			   lSumarizador.V_ProcessarMecanicas__c = true;
		   }

		Database.SaveResult[] lLstResult = database.update(lstSumarizador, false);
	  	 
	  	for(integer i=0; i < lLstResult.size(); i++) {
	 	
	 	    Database.SaveResult lResult = lLstResult[i];

			VN_Sumarizador__c lSumarizador = lstSumarizador[i];	 	
	 	    if(lSumarizador == null) continue;
	 	    
	 	    if (!lResult.isSuccess()){
		  		for(Database.Error err : lResult.getErrors()) {
					  System.debug('***Erro::' + err);
					fMsgErro += ' { ' + lSumarizador.Id +' }: '+err.getMessage()+' --FIM-- ';
			    }
		    } else {
                fSetSumarizadorAtualizado.add(lSumarizador.Id);
            }
	  	}
	}
	
	global void finish(Database.BatchableContext BC) {

		if(String.isNotEmpty(fMsgErro)){
			insert new VN_LogBatch__c(V_Processo__c = 'Processar Mecânica',
				 V_IdBatch__c = BC.getJobId(), V_ErroResultado__c = fMsgErro.left(32768)); 
		}

		if(!fSetSumarizadorAtualizado.isEmpty()){
            List<VN_Sumarizador__c> lstSumarizadorAtualizado = new List<VN_Sumarizador__c>();
            lstSumarizadorAtualizado = [SELECT V_Mes__c, V_MesString__c, V_AMYTDAnterior__c, V_Persona__c, V_Meta__c, V_Valor__c,
						V_PercentualAMMes__c, V_ResultadoSE__c, V_PercentualSEMes__c, V_MetaDoParticipante__c,
						V_PercentualAMYTDSemestre__c, V_MetaYTDSemestre__c, V_ValorYTDSemestre__c,
						V_PercentualAMYTDTrimestre__c, V_MetaYTDTrimestre__c, V_ValorYTDTrimestre__c,
						V_ScoreSMQ1__c, V_ScoreAMYTD__c, V_ScoreSMYTD__c, V_PercentualAMYTD__c, V_ValorDisputaComercial__c 
                        FROM VN_Sumarizador__c WHERE Id =: fSetSumarizadorAtualizado];
			
			Map<Id, VN_Sumarizador__c> lMapMetaSumarizador = new Map<Id, VN_Sumarizador__c>();
            for(VN_Sumarizador__c lSumarizador : lstSumarizadorAtualizado){
                lMapMetaSumarizador.put(lSumarizador.V_MetaDoParticipante__c, lSumarizador);
            }

            if(!lMapMetaSumarizador.isEmpty()){
                List<VN_MetaParticipante__c> lstMeta = new List<VN_MetaParticipante__c>();
                lstMeta = [SELECT V_AMYTDAnterior__c, V_Persona__c, V_Meta__c, V_Valor__c, V_PercentualAMMes__c,
                            V_ResultadoSE__c, V_UltimoMesAtualizado__c, V_PercentualSEMes__c,
							V_PercentualAM1Semestre__c, V_TotalMetas1Semestre__c, V_TotaldeVendas1Semestre__c,
							V_PercentualAM2Semestre__c, V_TotalMetas2Semestre__c, V_TotaldeVendas2Semestre__c,
							V_PercentualAM1Trimestre__c, V_TotalMetas1Trimestre__c, V_TotaldeVendas1Trimestre__c,
							V_PercentualAM2Trimestre__c, V_TotalMetas2Trimestre__c, V_TotaldeVendas2Trimestre__c,
							V_PercentualAM3Trimestre__c, V_TotalMetas3Trimestre__c, V_TotaldeVendas3Trimestre__c,
							V_PercentualAM4Trimestre__c, V_TotalMetas4Trimestre__c, V_TotaldeVendas4Trimestre__c,
							V_ScoreSuperacaoQ1__c, V_ScoreAtingimentoFY__c, V_ScoreSuperacaoFY__c, V_TotalDisputaComercialAF__c
                            FROM VN_MetaParticipante__c WHERE Id =: lMapMetaSumarizador.keySet()];

                if(!lstMeta.isEmpty()){
                    for(VN_MetaParticipante__c lMeta : lstMeta){
						//Atualiza informações meta do Participante
                        VN_Sumarizador__c lSum = lMapMetaSumarizador.get(lMeta.Id);
                        lMeta.V_AMYTDAnterior__c = lSum.V_AMYTDAnterior__c;
                        lMeta.V_Persona__c = lSum.V_Persona__c;
                        lMeta.V_Meta__c = lSum.V_Meta__c;
                        lMeta.V_Valor__c = lSum.V_Valor__c;
                        lMeta.V_PercentualAMMes__c = lSum.V_PercentualAMMes__c;
                        lMeta.V_ResultadoSE__c = lSum.V_ResultadoSE__c;
                        lMeta.V_PercentualSEMes__c = lSum.V_PercentualSEMes__c;
                        lMeta.V_UltimoMesAtualizado__c = lSum.V_MesString__c;
						lMeta.V_AMYTD__c = lSum.V_PercentualAMYTD__c;
						
						//Novo - Atribui Score (Ating. e Sup)
						lMeta.V_ScoreAtingimentoFY__c = lSum.V_ScoreAMYTD__c;
						lMeta.V_ScoreSuperacaoFY__c = lSum.V_ScoreSMYTD__c;
						lMeta.V_TotalDisputaComercialAF__c = lSum.V_ValorDisputaComercial__c;

						//Atualiza 1º Trimestre Meta Participante
                        if(lSum.V_Mes__c == 3){
                            lMeta.V_PercentualAM1Trimestre__c = lSum.V_PercentualAMYTDTrimestre__c;
                            lMeta.V_TotalMetas1Trimestre__c = lSum.V_MetaYTDTrimestre__c;
                            lMeta.V_TotaldeVendas1Trimestre__c = lSum.V_ValorYTDTrimestre__c;
                        }

						//Atualiza 1º Semestre Meta Participante
						//Atualiza 2º Trimestre Meta Participante
						if(lSum.V_Mes__c == 6){
                            lMeta.V_PercentualAM1Semestre__c = lSum.V_PercentualAMYTDSemestre__c;
                            lMeta.V_TotalMetas1Semestre__c = lSum.V_MetaYTDSemestre__c;
                            lMeta.V_TotaldeVendas1Semestre__c = lSum.V_ValorYTDSemestre__c;
							lMeta.V_PercentualAM2Trimestre__c = lSum.V_PercentualAMYTDTrimestre__c;
                            lMeta.V_TotalMetas2Trimestre__c = lSum.V_MetaYTDTrimestre__c;
                            lMeta.V_TotaldeVendas2Trimestre__c = lSum.V_ValorYTDTrimestre__c;
                        }

						//Atualiza 3º Trimestre Meta Participante
                        if(lSum.V_Mes__c == 9){
                            lMeta.V_PercentualAM3Trimestre__c = lSum.V_PercentualAMYTDTrimestre__c;
                            lMeta.V_TotalMetas3Trimestre__c = lSum.V_MetaYTDTrimestre__c;
                            lMeta.V_TotaldeVendas3Trimestre__c = lSum.V_ValorYTDTrimestre__c;
                        }

						//Atualiza 2º Semestre Meta Participante
                        if(lSum.V_Mes__c == 12){
                            lMeta.V_PercentualAM2Semestre__c = lSum.V_PercentualAMYTDSemestre__c;
                            lMeta.V_TotalMetas2Semestre__c = lSum.V_MetaYTDSemestre__c;
                            lMeta.V_TotaldeVendas2Semestre__c = lSum.V_ValorYTDSemestre__c;
							lMeta.V_PercentualAM4Trimestre__c = lSum.V_PercentualAMYTDTrimestre__c;
                            lMeta.V_TotalMetas4Trimestre__c = lSum.V_MetaYTDTrimestre__c;
                            lMeta.V_TotaldeVendas4Trimestre__c = lSum.V_ValorYTDTrimestre__c;
                        }

						//Atualiza | Score de Superação Q1
						if(lSum.V_Mes__c == 3)
							lMeta.V_ScoreSuperacaoQ1__c = lSum.V_ScoreSMQ1__c;
                    }
                    update lstMeta;
                }
            }
		}
		Set<String> lSetAnoFiscal = new Set<String>{fAnoFiscal};
	  	if(!lSetAnoFiscal.isEmpty()){
			Decimal lRandomNumber = Integer.valueof((Math.random() * 1000000));
			System.scheduleBatch( new SX_BatchAtualizarRankingNaMeta(lSetAnoFiscal),'Atualizar posição ranking '+lRandomNumber, 1); 
		}
	}	
}