force-app/main/default/objects/Contact/fields/V_Member__c.field-meta.xml
<CustomField>
    <fullName>V_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Contatos</relationshipLabel>
    <relationshipName>V_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Account__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Salesforce Account related to the Member.</description>
    <inlineHelpText>Enter the name of a Salesforce Account related to the Member.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Contact__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Salesforce CRM Contact.</description>
    <inlineHelpText>Related Salesforce CRM Contact.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Email__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Email__c</fullName>
    <description>Member&apos;s email address</description>
    <inlineHelpText>Enter the Member&apos;s email address.</inlineHelpText>
    <label>E-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_RegistroParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_RegistroParticipante__c</fullName>
    <description>Registro exclusivo do participante na Serasa Experian. Não aceita duplicidade de registros.</description>
    <externalId>true</externalId>
    <inlineHelpText>Registro exclusivo do participante na Serasa Experian. Não aceita duplicidade de registros.</inlineHelpText>
    <label>Login</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/VN_ContactRelationshipDefault.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 26/09/2018
* 
* Name: VN_ContactRelationshipDefault.trigger
* 
* Classe reflection da Fielo para criar relacionamentos dos members
*
*******************************************************************************/
global without sharing class VN_ContactRelationshipDefault implements FieloPLT.ContactRelationship{
   
    global static List<Contact> getRelatedContacts(List<FieloPLT__Member__c> aLstMembers){

        Map<Id, FieloPLT__Member__c> lMapMember = new Map<Id,FieloPLT__Member__c>();
        List<Contact> lListContact = new List<Contact>();

        List<Account> lLstAccount = [SELECT Id FROM Account WHERE Name =: Label.V_NomeContaSerasa];
        if(lLstAccount.isEmpty()) return lListContact;

        Map<String, Contact> lMapContact = new Map<String, Contact>();
        for(FieloPLT__Member__c member : aLstMembers){

            if (member.FieloPLT__Account__c != null && member.FieloPLT__Contact__c != null) continue;

            if(member.FieloPLT__Account__c == null){ 

            	member.FieloPLT__Account__c = lLstAccount[0].Id;

                //campo de registro é único e obrigatório
                String lNumRegistro = member.V_RegistroParticipante__c; 

                if(member.FieloPLT__Email__c == null) member.FieloPLT__Email__c = lNumRegistro + Label.V_DominioEmailVazio;

                Contact lCtt = new Contact(
                		LastName = member.Name, 
                		Email = member.FieloPLT__Email__c,
                		V_Member__c = member.Id, 
                		AccountId = member.FieloPLT__Account__c);
                lMapContact.put(lNumRegistro, lCtt);
            }
        }

        try{

            if(!lMapContact.isEmpty()) insert lMapContact.values();

            for (FieloPLT__Member__c member : aLstMembers) {                
                String lNumRegistro = member.V_RegistroParticipante__c;
                if (lMapContact.containsKey(lNumRegistro)) {
                    member.FieloPLT__Contact__c = lMapContact.get(lNumRegistro).Id;
                    lListContact.add(new Contact(id = member.FieloPLT__Contact__c));
                }
                else lListContact.add(null);
            }

        } catch(Exception e){
            system.debug('### erro criação conta/contato :' + e.getMessage());
        }
        return lListContact;
    }
}