force-app/main/default/objects/VN_Sumarizador__c/VN_Sumarizador__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por sumarizar as metas, resultados e ponderados das informações carregas ou atualizadas.</description>
    <label>Sumarizador</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Código do Sumarizador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sumarizadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Mes__c.field-meta.xml
<CustomField>
    <fullName>V_Mes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Faz referência ao mês corrente da meta</description>
    <label>Mês Meta</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_MetaDoParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_MetaDoParticipante__c</fullName>
    <description>Meta dos participantes</description>
    <label>Meta do Participante</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipName>VN_SumarizadoresDosObjetivos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SX_SumarizadorTrigger.cls
// /*******************************************************************************
// *                          Copyright (C) 2019 ValueNET
// * ------------------------------------------------------------------------------
// * Author: LK                          date: 18/07/2019
// * 
// * Name: SX_SumarizadorTrigger.cls
// * 
// * Classe para disparar ações do VN_Sumarizador
// *******************************************************************************/
public with sharing class SX_SumarizadorTrigger {
//     public static Set<Integer> fMesProcessado;
//     public static Set<Integer> fMesesAnteriores;
//     public static final Integer MES_6 = 6;
//     public static final Integer MES_9 = 9;
//     public static final Integer MES_12 = 12;
//     public static final Set<Integer> SET_PRIMEIROSEMESTRE = new Set<Integer> {1, 2, 3, 4, 5, 6};
//     public static final Set<Integer> SET_SEGUNDOSEMESTRE = new Set<Integer> {7, 8, 9, 10, 11, 12};
//     public static final Set<Integer> SET_SEGUNDOTRIMESTRE = new Set<Integer> {4, 5, 6};
//     public static final Set<Integer> SET_TERCEIROTRIMESTRE = new Set<Integer> {7, 8, 9};
//     public static final Set<Integer> SET_QUARTOTRIMESTRE = new Set<Integer> {10, 11, 12};

//     public static Set<Id> fSetSumarizador;

//     public static void atualizarSumarizador(){

//         List<VN_Sumarizador__c> lstSumarizadores = (List<VN_Sumarizador__c>) Trigger.new;
//         if(fSetSumarizador == null){
//             fSetSumarizador = new Set<Id>();
//         }

//         if(!system.isBatch()){
        
//             Map<Id, VN_Sumarizador__c> lMapSumarizadorMaisAntigo = new Map<Id, VN_Sumarizador__c>();
//             for(VN_Sumarizador__c lSumarizador : lstSumarizadores){
//                 if(fSetSumarizador.contains(lSumarizador.Id))
//                     continue;
//                 else
//                     fSetSumarizador.add(lSumarizador.Id);

//                 if(!lMapSumarizadorMaisAntigo.containsKey(lSumarizador.V_MetaDoParticipante__c))
//                     lMapSumarizadorMaisAntigo.put(lSumarizador.V_MetaDoParticipante__c, lSumarizador);
//                 else{
//                     if(lMapSumarizadorMaisAntigo.get(lSumarizador.V_MetaDoParticipante__c).V_Mes__c 
//                             > lSumarizador.V_Mes__c){
//                         lMapSumarizadorMaisAntigo.put(lSumarizador.V_MetaDoParticipante__c, lSumarizador);
//                     }
//                 }    
//             }
//             if(!lMapSumarizadorMaisAntigo.isEmpty()){
//                 SX_BatchAtualizarSumarizador lBatch = new SX_BatchAtualizarSumarizador(lMapSumarizadorMaisAntigo.values()); 
//                 Database.executeBatch(lBatch);
//             }
//         }
//     }
}