force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_FirstAccess__c.field-meta.xml
<CustomField>
    <fullName>V_FirstAccess__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Utilizado para validar se é o primeiro acesso do member, para validar se, durante o primeiro login, devemos solicitar o nome de tratamento.</description>
    <label>Primeiro Acesso</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SX_ChangePasswordControllerTest.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: LK                date: 24/09/2018
*
* 
* Name: SX_ChangePasswordControllerTest.cls
* 
* Classe de testes para a classe SX_ChangePasswordController.cls
*******************************************************************************/
@isTest
public with sharing class SX_ChangePasswordControllerTest {
	static testMethod void SX_ChangePasswordControllerTest() {

		User lUser = SObjectForTest.loadUserLoggedMember();

		FieloPLT__Member__c lMember = [select Id from FieloPLT__Member__c where FieloPLT__User__c =: lUser.Id limit 1];
		lMember.V_FirstAccess__c = true;
 		update lMember;	

 		Test.startTest();
 		System.runAs(lUser) {
 			SX_ChangePasswordController lCtrl = new SX_ChangePasswordController();
 			lCtrl.doChangePassword();
 			lCtrl.fFirstAccess = false;
 			lCtrl.doChangePassword();
 			lCtrl.fPassword = 'xx';
 			lCtrl.fConfirmPassword = '123';
 			lCtrl.doChangePassword();
 			lCtrl.fPassword = 'aaaaaaaa';
 			lCtrl.doChangePassword();
 			lCtrl.fConfirmPassword = 'aaaaaaaa';
 			lCtrl.doChangePassword();
 		}
	}
}