force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</description>
    <inlineHelpText>Choose Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_MetasAnoFiscalVigenteNovo__c.field-meta.xml
<CustomField>
    <fullName>V_MetasAnoFiscalVigenteNovo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Exibe a identificação do ano fiscal vigente do participante.</description>
    <inlineHelpText>Exibe a identificação do ano fiscal vigente do participante.</inlineHelpText>
    <label>Metas do Ano Fiscal Vigente</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipLabel>Participantes</relationshipLabel>
    <relationshipName>Participantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_NovoContratado__c.field-meta.xml
<CustomField>
    <fullName>V_NovoContratado__c</fullName>
    <description>Indica se o participante é um novo contratado ou não.</description>
    <inlineHelpText>Indica se o participante é um novo contratado ou não.</inlineHelpText>
    <label>Novo Contratado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_PapelElite__c.field-meta.xml
<CustomField>
    <fullName>V_PapelElite__c</fullName>
    <label>Papel Elite</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DIRETORES</fullName>
            </value>
            <value>
                <fullName>GERENTES DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDERES</fullName>
            </value>
            <value>
                <fullName>LÍDERES (COORDENADORES) E GERENTE REGIONAIS</fullName>
            </value>
            <value>
                <fullName>NÃO ELEGÍVEL</fullName>
                <default>true</default>
                <label>NÃO ELEGÍVEL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_ScoreElite__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreElite__c</fullName>
    <description>Score Elite do ano fiscal vigente.</description>
    <formula>V_MetasAnoFiscalVigenteNovo__r.V_ScoreElite__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Score Elite do ano fiscal vigente.</inlineHelpText>
    <label>Score Elite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/VN_GerenciadorMetaParticipanteAF__c.object-meta.xml
<CustomObject>
    <description>Gerenciador dos registros de metas dos participantes por Ano Fiscal.</description>
    <label>Gerenciador Meta Participante AF</label>
    <nameField>
        <displayFormat>GMAF-{000000}</displayFormat>
        <label>No. Gerenciador Ano Fiscal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gerenciador Metas Participantes AF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <description>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</description>
    <inlineHelpText>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</inlineHelpText>
    <label>Ano Fiscal</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_PeriodoAF__c.field-meta.xml
<CustomField>
    <fullName>V_PeriodoAF__c</fullName>
    <description>Registrar o período do ano fiscal desejado. Exemplo: 2018-2019</description>
    <inlineHelpText>Registrar o período do ano fiscal desejado. Exemplo: 2018-2019</inlineHelpText>
    <label>Período AF</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sinaliza se o gerenciador é o que está em vigência.</description>
    <inlineHelpText>Sinaliza se o gerenciador é o que está em vigência.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ano fiscal da Meta do participante do participante</description>
    <label>Gerenciador Meta Participante AF</label>
    <referenceTo>VN_GerenciadorMetaParticipanteAF__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ElegivelAoElite__c.field-meta.xml
<CustomField>
    <fullName>V_ElegivelAoElite__c</fullName>
    <description>Indica se o participante está elegível ao Elite no momento atual.</description>
    <formula>IF( 

CONTAINS(UPPER( V_Participante__r.Name), &apos;TESTE&apos;), FALSE, 

IF( 
AND( 
TEXT(V_Participante__r.V_NovoContratado__c) = &apos;Não&apos;, 
TEXT(V_Participante__r.FieloPLT__Status__c) = &apos;Active&apos;, 
V_PercentualMetaYTD__c &gt;= 1), TRUE, FALSE ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indica se o participante está elegível ao Elite no momento atual.</inlineHelpText>
    <label>Elegível ao Elite?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PapelElite__c.field-meta.xml
<CustomField>
    <fullName>V_PapelElite__c</fullName>
    <formula>TEXT(V_Participante__r.V_PapelElite__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Papel Elite</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Participante__c.field-meta.xml
<CustomField>
    <fullName>V_Participante__c</fullName>
    <description>Participante relacionado à meta.</description>
    <inlineHelpText>Participante relacionado à meta.</inlineHelpText>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ParticRankingElite__c.field-meta.xml
<CustomField>
    <fullName>V_ParticRankingElite__c</fullName>
    <formula>AND(TEXT( V_Participante__r.FieloPLT__Status__c ) = &apos;Active&apos;,
TEXT( V_Participante__r.V_NovoContratado__c) = &apos;Não&apos;,
NOT(CONTAINS( UPPER( V_Participante__r.Name), &apos;TESTE&apos;)),
(V_PapelElite__c &lt;&gt; &apos;NÃO ELEGÍVEL&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Participa Ranking Elite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualMetaYTD__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualMetaYTD__c</fullName>
    <formula>V_AMYTD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% Meta YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ScoreElite__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreElite__c</fullName>
    <formula>V_ScoreAtingimentoFY__c + V_ScoreSuperacaoFY__c + V_ScoreSuperacaoQ1__c + V_ScorePotencialCarteira__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score Elite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_TotalVendasYTD__c.field-meta.xml
<CustomField>
    <fullName>V_TotalVendasYTD__c</fullName>
    <label>Total de Vendas -YTD</label>
    <summarizedField>VN_Sumarizador__c.V_Valor__c</summarizedField>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_ProcessarMecanicas__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>VN_Sumarizador__c.V_MetaDoParticipante__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_UltimoMesAtualizado__c.field-meta.xml
<CustomField>
    <fullName>V_UltimoMesAtualizado__c</fullName>
    <label>Último Mês Atualizado</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <description>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</description>
    <formula>V_AnoFiscal__r.V_Vigente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SX_RankingController.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: LK                date: 15/07/2019
*
* 
* Name: SX_RankingController.cls
* 
* Classe para o componente SX_Ranking_Cmp.cmp
*******************************************************************************/
public with sharing class SX_RankingController {

    @AuraEnabled
    public static FieloPLT__Member__c getMember() {
        List<FieloPLT__Member__c> lMemberLst = [SELECT Id, V_PapelElite__c, V_MetasAnoFiscalVigenteNovo__c,
                    V_MetasAnoFiscalVigenteNovo__r.V_UltimoMesAtualizado__c, V_MetasAnoFiscalVigenteNovo__r.V_AnoFiscal__r.V_PeriodoAF__c
	                FROM FieloPLT__Member__c
	                WHERE FieloPLT__User__c =: UserInfo.getUserId()];

	    return lMemberLst.isEmpty() ? null : lMemberLst[0];         
    }

    private static String loadAnoFiscalVigente(){

		List<VN_GerenciadorMetaParticipanteAF__c> lLstGeren = [SELECT V_AnoFiscal__c 
																FROM VN_GerenciadorMetaParticipanteAF__c
																WHERE V_Vigente__c = true];
		return lLstGeren.isEmpty() ? '' : lLstGeren[0].V_AnoFiscal__c;
	}  

    @AuraEnabled
    public static Map<Integer,List<Ranking>> getRanking(String aPapelElite){

        String lAnoFiscal = loadAnoFiscalVigente();
        if(String.isEmpty(lAnoFiscal)) return null;

        Integer lQuantidadeVagas = VN_MemberService.getQuantidadeVagas(aPapelElite);
        Integer lQuantidadeRanking = lQuantidadeVagas + 5;
        Map<Integer, List<Ranking>> lMapRanking = new Map<Integer, List<Ranking>>();
        List<Ranking> lstRanking = new List<Ranking>();
        List<Ranking> lstRankingQuaseLa = new List<Ranking>();

        List<VN_MetaParticipante__c> lstMetaParticipante = [SELECT V_Participante__c, V_ParticRankingElite__c,
                                                    V_Participante__r.Name, V_ScoreElite__c, V_ElegivelAoElite__c, V_PercentualMetaYTD__c
                                                    FROM VN_MetaParticipante__c
                                                    WHERE V_PapelElite__c =: aPapelElite AND Name =: lAnoFiscal 
                                                    AND V_Participante__r.V_NovoContratado__c = 'Não'
                                                    AND V_Participante__r.FieloPLT__Status__c = 'Active'
                                                    AND (NOT V_Participante__r.Name like '%Teste%')
                                                    AND (NOT V_Participante__r.Name like '%VAGO_%') // add 10/10 task #17343
                                                    AND (NOT V_Participante__r.Name like '%CARTEIRA_AFASTADO_%') // add 30/10 task #17394
                                                    ORDER BY V_ScoreElite__c DESC, V_PercentualMetaYTD__c DESC, V_TotalVendasYTD__c DESC,
                                                    V_Participante__r.Name ASC
                                                    LIMIT : lQuantidadeRanking];
        
        if(!lstMetaParticipante.isEmpty()){
            Integer lPosicao = 1;
            for(VN_MetaParticipante__c lMetaParticipante : lstMetaParticipante){
                Ranking lRanking = new Ranking();
                lRanking.wPosicao = lPosicao;
                lRanking.wNome = lMetaParticipante.V_Participante__r.Name;
                lRanking.wScore = Integer.valueOf(lMetaParticipante.V_ScoreElite__c);
                lRanking.wElegivel = lMetaParticipante.V_PercentualMetaYTD__c >= 100 ? 'Sim' : 'Não';
                if(lPosicao <= lQuantidadeVagas)
                    lstRanking.add(lRanking);
                else
                    lstRankingQuaseLa.add(lRanking);
                lPosicao ++;    
            }
            lMapRanking.put(0, lstRanking);
            if(!lstRankingQuaseLa.isEmpty())
                lMapRanking.put(1, lstRankingQuaseLa);
            else
                lMapRanking.put(1, null);
    
            return lMapRanking;
        }
        return null;
    }

    public class Ranking {
        @AuraEnabled public Integer wPosicao {get; set;}
        @AuraEnabled public String wNome {get; set;}
        @AuraEnabled public Integer wScore {get; set;}
        @AuraEnabled public String wElegivel {get; set;}
    }
}