force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program that the Member belongs to.</description>
    <inlineHelpText>The Program that the Member belongs to</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo atual do participante.</description>
    <inlineHelpText>Cargo atual do participante.</inlineHelpText>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COORDENADOR | GERENTE REGIONAL VIP</fullName>
            </value>
            <value>
                <fullName>DIRETOR</fullName>
            </value>
            <value>
                <fullName>GERENTE DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDER</fullName>
            </value>
            <value>
                <fullName>COORDENADOR II</fullName>
                <isActive>false</isActive>
                <label>COORDENADOR II</label>
            </value>
            <value>
                <fullName>GERENTE DE VENDAS</fullName>
                <isActive>false</isActive>
                <label>GERENTE DE VENDAS</label>
            </value>
            <value>
                <fullName>VICE-PRESIDENTE</fullName>
                <isActive>false</isActive>
                <label>VICE-PRESIDENTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_NovoContratado__c.field-meta.xml
<CustomField>
    <fullName>V_NovoContratado__c</fullName>
    <description>Indica se o participante é um novo contratado ou não.</description>
    <inlineHelpText>Indica se o participante é um novo contratado ou não.</inlineHelpText>
    <label>Novo Contratado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_PapelElite__c.field-meta.xml
<CustomField>
    <fullName>V_PapelElite__c</fullName>
    <label>Papel Elite</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DIRETORES</fullName>
            </value>
            <value>
                <fullName>GERENTES DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDERES</fullName>
            </value>
            <value>
                <fullName>LÍDERES (COORDENADORES) E GERENTE REGIONAIS</fullName>
            </value>
            <value>
                <fullName>NÃO ELEGÍVEL</fullName>
                <default>true</default>
                <label>NÃO ELEGÍVEL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_ScoreElite__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreElite__c</fullName>
    <description>Score Elite do ano fiscal vigente.</description>
    <formula>V_MetasAnoFiscalVigenteNovo__r.V_ScoreElite__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Score Elite do ano fiscal vigente.</inlineHelpText>
    <label>Score Elite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Program__c/FieloPLT__Program__c.object-meta.xml
<CustomObject>
    <description>Programs establish the general operation settings for your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Program__c/fields/V_RegulamentoElite__c.field-meta.xml
<CustomField>
    <fullName>V_RegulamentoElite__c</fullName>
    <description>Utilizado para a inclusão do regulamento da iniciativa Elite.</description>
    <inlineHelpText>Utilizado para a inclusão do regulamento da iniciativa Elite.</inlineHelpText>
    <label>Regulamento Elite</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PapelElite__c.field-meta.xml
<CustomField>
    <fullName>V_PapelElite__c</fullName>
    <formula>TEXT(V_Participante__r.V_PapelElite__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Papel Elite</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Participante__c.field-meta.xml
<CustomField>
    <fullName>V_Participante__c</fullName>
    <description>Participante relacionado à meta.</description>
    <inlineHelpText>Participante relacionado à meta.</inlineHelpText>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PotencialCarteira__c.field-meta.xml
<CustomField>
    <fullName>V_PotencialCarteira__c</fullName>
    <description>Valor do Tamanho da Carteira do participante. O atual critério é o mesmo valor do total de metas do ano fiscal do participante.</description>
    <inlineHelpText>Valor do Tamanho da Carteira do participante. O atual critério é o mesmo valor do total de metas do ano fiscal do participante.</inlineHelpText>
    <label>Tamanho da Carteira</label>
    <summarizedField>VN_Sumarizador__c.V_Meta__c</summarizedField>
    <summaryForeignKey>VN_Sumarizador__c.V_MetaDoParticipante__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ScoreAtingimentoFY__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreAtingimentoFY__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Score de Atingimento FY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ScoreElite__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreElite__c</fullName>
    <formula>V_ScoreAtingimentoFY__c + V_ScoreSuperacaoFY__c + V_ScoreSuperacaoQ1__c + V_ScorePotencialCarteira__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score Elite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ScorePotencialCarteira__c.field-meta.xml
<CustomField>
    <fullName>V_ScorePotencialCarteira__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indica o score do tamanho da carteira do participante no ano fiscal.</description>
    <inlineHelpText>Indica o score do tamanho da carteira do participante no ano fiscal.</inlineHelpText>
    <label>Score Tamanho da Carteira</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ScoreSuperacaoFY__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreSuperacaoFY__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Score de Superação FY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ScoreSuperacaoQ1__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreSuperacaoQ1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Score de Superação Q1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_UltimoMesAtualizado__c.field-meta.xml
<CustomField>
    <fullName>V_UltimoMesAtualizado__c</fullName>
    <label>Último Mês Atualizado</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/VN_MetasParticipantes__c.object-meta.xml
<CustomObject>
    <description>Cadastro de metas mês a mês do ano fiscal dos participantes.</description>
    <label>Meta do Participante - OLD</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes - OLD</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_Participante__c.field-meta.xml
<CustomField>
    <fullName>V_Participante__c</fullName>
    <description>Participante relacionado à meta.</description>
    <inlineHelpText>Participante relacionado à meta.</inlineHelpText>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipName>Metas_dos_Participantes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_PotencialCarteira__c.field-meta.xml
<CustomField>
    <fullName>V_PotencialCarteira__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Valor do Tamanho da Carteira do participante que será definido pela Área de Planejamento (VN) a cada ano fiscal.</description>
    <inlineHelpText>Valor do Tamanho da Carteira do participante que será definido pela Área de Planejamento (VN) a cada ano fiscal.</inlineHelpText>
    <label>Tamanho da Carteira</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ScoreAMEliteAF__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreAMEliteAF__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indica o score de atingimento de meta Elite do participante no ano fiscal.</description>
    <inlineHelpText>Indica o score de atingimento de meta Elite do participante no ano fiscal.</inlineHelpText>
    <label>Score de AM Elite - AF</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ScoreAMH1EliteSemestre1AF__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreAMH1EliteSemestre1AF__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Score de atingimento de meta Elite no 1o. semestre do ano fiscal.</description>
    <inlineHelpText>Score de atingimento de meta Elite no 1o. semestre do ano fiscal.</inlineHelpText>
    <label>Score AM H1 Elite - 1o. Sem.</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ScoreEliteAF__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreEliteAF__c</fullName>
    <description>Indica o Score Elite do participante no ano fiscal.</description>
    <formula>V_ScorePotencialCarteira__c +
V_ScoreAMEliteAF__c + 
V_ScoreSMEliteAF__c + 
V_ScoreAMH1EliteSemestre1AF__c + 
V_ScoreEliteExtraYoubetAF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indica o Score Elite do participante no ano fiscal.</inlineHelpText>
    <label>Score Elite - AF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ScoreEliteHoje__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreEliteHoje__c</fullName>
    <formula>V_ScorePotencialCarteira__c + 
V_ScoreAMEliteHoje__c +
V_ScoreSMEliteHoje__c +
V_ScoreAMH1EliteSemestre1AF__c + 
V_ScoreEliteExtraYoubetAF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score Elite - Hoje</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ScorePotencialCarteira__c.field-meta.xml
<CustomField>
    <fullName>V_ScorePotencialCarteira__c</fullName>
    <description>Indica o score do tamanho da carteira do participante no ano fiscal.</description>
    <inlineHelpText>Indica o score do tamanho da carteira do participante no ano fiscal.</inlineHelpText>
    <label>Score Tamanho da Carteira</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ScoreSMEliteAF__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreSMEliteAF__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indica o score de superação de meta Elite do participante no ano fiscal.</description>
    <inlineHelpText>Indica o score de superação de meta Elite do participante no ano fiscal.</inlineHelpText>
    <label>Score de SM Elite - AF</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SX_EliteHomeController.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 16/10/2018
* 
* Name: SX_EliteHomeController.cls
* 
* Controller da home Elite
*******************************************************************************/
public with sharing class SX_EliteHomeController {  

    @AuraEnabled
    public static FieloPLT__Member__c getMember() {
        List<FieloPLT__Member__c> lMemberLst = [SELECT Id, V_Cargo__c, V_PapelElite__c, FieloPLT__Program__r.V_RegulamentoElite__c
                    FROM FieloPLT__Member__c
                    WHERE FieloPLT__User__c =: UserInfo.getUserId()];

        return lMemberLst.isEmpty() ? null : lMemberLst[0];         
    }

    // @AuraEnabled
    // public static VN_MetasParticipantes__c getMeta(String aIdMember) {

    //  String lAnoFiscal = loadAnoFiscalVigente();
    //  if(String.isEmpty(lAnoFiscal)) return null;

    //  List<VN_MetasParticipantes__c> lLstMeta = [SELECT Id, V_ScoreEliteAF__c, V_ScorePotencialCarteira__c,
    //                                              V_ScoreAMH1EliteSemestre1AF__c, V_ScoreAMEliteAF__c, V_ScoreSMEliteAF__c,
    //                                              V_ScoreEliteHoje__c, V_Participante__r.V_NovoContratado__c
    //                                              FROM VN_MetasParticipantes__c
    //                                              WHERE V_Participante__c =: aIdMember
    //                                              AND Name =: lAnoFiscal];

    //  return lLstMeta.isEmpty() ? null : lLstMeta[0];         
    // }

    // Nova estrutura buscar Metas Participante
    @AuraEnabled
    public static VN_MetaParticipante__c getMetaParticipante(String aIdMember){

        String lAnoFiscal = loadAnoFiscalVigente();
        if(String.isEmpty(lAnoFiscal)) return null;

        List<VN_MetaParticipante__c> lLstMeta = [SELECT Id, V_ScoreSuperacaoQ1__c, V_PotencialCarteira__c, V_ScoreAtingimentoFY__c,
                V_ScoreSuperacaoFY__c, V_ScoreElite__c, V_ScorePotencialCarteira__c, V_UltimoMesAtualizado__c,
                V_TotalMetas1Semestre__c, V_Participante__r.V_NovoContratado__c, V_Ano__c, V_AnoFiscal__r.V_PeriodoAF__c
                FROM VN_MetaParticipante__c 
                WHERE V_Participante__c =: aIdMember 
                AND Name =:lAnoFiscal];

        return lLstMeta.isEmpty() ? null : lLstMeta[0]; 
    }
    
    // @AuraEnabled
    // public static List<Posicao> getRanking(String aIdMember, String aCargo) {

    //  String lAnoFiscal = loadAnoFiscalVigente();
    //  if(String.isEmpty(lAnoFiscal)) return null;

    //  List<String> lLstRanking = new List<String>();

    //  Integer lTotalRanking = aCargo == 'DIRETOR' ? Integer.valueOf(Label.V_RankingDiretor)
    //                          : aCargo == 'LÍDER' ? Integer.valueOf(Label.V_RankingLider)
    //                          : aCargo == 'GERENTE DE CONTAS' ? Integer.valueOf(Label.V_RankingGerenteDeContas)
    //                          : Integer.valueOf(Label.V_RankingCoordenador_GerenteRegional); 

    //  Map<Integer, Integer> lMapRanking = new Map<Integer, Integer>();
    //  for(Integer i = lTotalRanking; i > 0; i--){
    //      lMapRanking.put(i, 0);
    //  }

    //  Integer lTamanhoCarteira = 9999;
    //  for(VN_MetasParticipantes__c metas: [SELECT V_Participante__c, V_ScoreEliteAF__c, V_ScorePotencialCarteira__c, V_Participante__r.V_NovoContratado__c,
    //                                       V_ScoreEliteHoje__c, V_Participante__r.V_Cargo__c, V_ParticRankingElite__c 
    //                                          FROM VN_MetasParticipantes__c
    //                                          WHERE V_Participante__r.V_Cargo__c =: aCargo
    //                                          //AND V_ParticRankingElite__c = true
    //                                          AND Name =: lAnoFiscal]){

    //      if(metas.V_Participante__c == aIdMember){
    //          lTamanhoCarteira = calculateElegivel(Integer.valueOf(metas.V_ScorePotencialCarteira__c), aCargo);
    //      }

    //      if(!metas.V_ParticRankingElite__c || metas.V_Participante__r.V_NovoContratado__c == 'Sim') continue; // incluido 23/11/2018 (pedido do atendimento)

    //      Integer lScore = Integer.valueOf(metas.V_ScoreEliteHoje__c);

    //      Integer lTotalMembers = lMapRanking.get(lScore); 
    //      if(lTotalMembers == null) continue;

    //      lTotalMembers ++;
    //      lMapRanking.put(lScore, lTotalMembers);
    //  }

    //  List<Posicao> lLstPos = new List<Posicao>();
    //  for(Integer lKey: lMapRanking.keySet()){

    //      Integer lTotal = lMapRanking.get(lKey);
    //      if(lTotal == null) continue;

    //      Posicao lPos = new Posicao();
    //      lPos.wScore = lKey;
    //      lPos.wTotalMembers = lTotal;

    //      String lKeyStr = lKey < 10 ? '0'+String.valueOf(lKey) : String.valueOf(lKey);
    //      lPos.wScoreStr = lKeyStr;

    //      lPos.wPosicaoElegivel = lTamanhoCarteira == lKey;

    //      lLstPos.add(lPos);
    //  }
    //  return lLstPos;         
    // }

    @AuraEnabled
    public static List<Posicao> getRankingNovaEstrutura(String aIdMember, String aCargo) {

        String lAnoFiscal = loadAnoFiscalVigente();
        if(String.isEmpty(lAnoFiscal)) return null;

        List<String> lLstRanking = new List<String>();

        Integer lTotalRanking = aCargo == 'DIRETORES' ? Integer.valueOf(Label.V_RankingDiretor)
                                : aCargo == 'LÍDERES' ? Integer.valueOf(Label.V_RankingLider)
                                : aCargo == 'GERENTES DE CONTAS' ? Integer.valueOf(Label.V_RankingGerenteDeContas)
                                : Integer.valueOf(Label.V_RankingCoordenador_GerenteRegional); 

        Map<Integer, Integer> lMapRanking = new Map<Integer, Integer>();
        for(Integer i = lTotalRanking; i > 0; i--){
            lMapRanking.put(i, 0);
        }

        Integer lTamanhoCarteira = 9999;
        for(VN_MetaParticipante__c metas: [SELECT V_Participante__c, V_ScorePotencialCarteira__c, V_Participante__r.V_NovoContratado__c,
                                             V_ScoreElite__c, V_PapelElite__c, V_ParticRankingElite__c
                                                FROM VN_MetaParticipante__c
                                                WHERE V_PapelElite__c =: aCargo
                                                AND (NOT V_Participante__r.Name like '%VAGO_%')
                                                AND (NOT V_Participante__r.Name like '%CARTEIRA_AFASTADO_%') // add 30/10 task #17394
                                                AND V_ParticRankingElite__c = true
                                                AND Name =: lAnoFiscal]){

            if(metas.V_Participante__c == aIdMember){
                lTamanhoCarteira = calculateElegivel(Integer.valueOf(metas.V_ScorePotencialCarteira__c), aCargo);
            }

            if(!metas.V_ParticRankingElite__c || metas.V_Participante__r.V_NovoContratado__c == 'Sim') continue; // incluido 23/11/2018 (pedido do atendimento)

            Integer lScore = Integer.valueOf(metas.V_ScoreElite__c);

            Integer lTotalMembers = lMapRanking.get(lScore); 
            if(lTotalMembers == null) continue;

            lTotalMembers ++;
            lMapRanking.put(lScore, lTotalMembers);
        }

        List<Posicao> lLstPos = new List<Posicao>();
        for(Integer lKey: lMapRanking.keySet()){

            Integer lTotal = lMapRanking.get(lKey);
            if(lTotal == null) continue;

            Posicao lPos = new Posicao();
            lPos.wScore = lKey;
            lPos.wTotalMembers = lTotal;

            String lKeyStr = lKey < 10 ? '0'+String.valueOf(lKey) : String.valueOf(lKey);
            lPos.wScoreStr = lKeyStr;

            lPos.wPosicaoElegivel = lTamanhoCarteira == lKey;

            lLstPos.add(lPos);
        }
        System.debug(lLstPos);
        return lLstPos;         
    } 


    // @AuraEnabled
    // public static String getVagas(String aIdMember, String aCargo) {

    //  String lAnoFiscal = loadAnoFiscalVigente();
    //  if(String.isEmpty(lAnoFiscal)) return null;

    //  Integer lTotalVagas = aCargo == 'DIRETOR' ? Integer.valueOf(Label.V_VagasDiretor)
    //                          : aCargo == 'LÍDER' ? Integer.valueOf(Label.V_VagasLider)
    //                          : aCargo == 'GERENTE DE CONTAS' ? Integer.valueOf(Label.V_VagasGerenteDeContas)
    //                          : Integer.valueOf(Label.V_VagasCordenador_GerenteRegional); 

    //  system.debug('##lTotalVagas ' + lTotalVagas);

    //  List<AggregateResult> lLstAgg = [SELECT COUNT(Id)total FROM VN_MetasParticipantes__c
    //          WHERE V_Participante__r.V_Cargo__c =: aCargo AND Name =: lAnoFiscal AND V_ElegivelAoElite__c = true];

    //  Integer lTotalMembers = !lLstAgg.isEmpty() ? Integer.valueOf(lLstAgg[0].get('total')) : 0;
    //  system.debug('##lTotalMembers ' + lTotalMembers);

    //  Integer lVagas = lTotalMembers >= lTotalVagas ? 0 : (lTotalVagas - lTotalMembers); 

    //  system.debug('##lVagas ' + lVagas);

    //  //return lVagas < 10 ? '0'+String.valueOf(lVagas) : String.valueOf(lVagas);
    //  return lTotalVagas < 10 ? '0'+String.valueOf(lTotalVagas) : String.valueOf(lTotalVagas);
    // }

    @AuraEnabled
    public static String getVagasNovaEstrutura(String aIdMember, String aCargo) {

        String lAnoFiscal = loadAnoFiscalVigente();
        if(String.isEmpty(lAnoFiscal)) return null;

        Integer lTotalVagas = aCargo == 'NÃO ELEGÍVEL' ? 0
                                : aCargo == 'DIRETORES' ? Integer.valueOf(Label.V_VagasDiretor)
                                : aCargo == 'LÍDERES' ? Integer.valueOf(Label.V_VagasLider)
                                : aCargo == 'GERENTES DE CONTAS' ? Integer.valueOf(Label.V_VagasGerenteDeContas)
                                : Integer.valueOf(Label.V_VagasCordenador_GerenteRegional); 

        system.debug('##lTotalVagas ' + lTotalVagas);

        return lTotalVagas < 10 ? '0'+String.valueOf(lTotalVagas) : String.valueOf(lTotalVagas);
    }

    @AuraEnabled
    public static Integer getPosicaoRanking(String aIdMember, String aCargo){

        String lAnoFiscal = loadAnoFiscalVigente();
        if(String.isEmpty(lAnoFiscal)) return null;

    // critério de desempate alterado 06/08/19 - #task 16632
         return Integer.valueOf(SX_HomeCardController.getRanking(aIdMember, aCargo));
        
        // List<VN_MetaParticipante__c> lstMetas = new List<VN_MetaParticipante__c>();
        // lstMetas = [SELECT V_Participante__c, V_Nome__c, V_ScoreElite__c 
        //         FROM VN_MetaParticipante__c 
        //         WHERE Name =: lAnoFiscal 
        //         AND V_Participante__r.V_PapelElite__c =: aCargo
        //         AND V_ParticRankingElite__c = true
        //         ORDER BY V_ScoreElite__c DESC,  V_ScoreSuperacaoFY__c DESC];

        // if(!lstMetas.isEmpty()){
        //     Integer lPosicao = 1;
        //     for(VN_MetaParticipante__c lMeta : lstMetas){
        //         System.debug('*** '+lMeta.V_Participante__c);
        //         if(lMeta.V_Participante__c == aIdMember)
        //             return lPosicao;
        //         lPosicao++; 
        //     }
        // }

        // return 0;
    }

    private static String loadAnoFiscalVigente(){

        List<VN_GerenciadorMetaParticipanteAF__c> lLstGeren = [SELECT V_AnoFiscal__c 
                                                                FROM VN_GerenciadorMetaParticipanteAF__c
                                                                WHERE V_Vigente__c = true];
        return lLstGeren.isEmpty() ? '' : lLstGeren[0].V_AnoFiscal__c;
    }   

    public class Posicao{

        @AuraEnabled public Integer wScore {get; set;}
        @AuraEnabled public String wScoreStr {get; set;}
        @AuraEnabled public Integer wTotalMembers {get; set;}
        @AuraEnabled public Integer wTotalEquipe {get; set;}
        @AuraEnabled public Boolean wPosicaoElegivel {get; set;}
    }

    private static Integer calculateElegivel(Integer lTamanhoCarteira, String aCargo){

        Integer lNumElegivel = 9999;

        //Gerentes de Conta - Carteira 1: Elegibilidade 7
        //Gerentes de Conta - Carteira 2: Elegibilidade 8
        //Gerentes de Conta - Carteira 3: Elegibilidade 9
        //Líder - Carteira 1: Elegibilidade 7 
        //Líder - Carteira 2: Elegibilidade 8
        //Diretor: Elegibilidade 7
        //Coordenador | Gerente Regional VIP: Elegibilidade 7
        if(aCargo == 'GERENTE DE CONTAS'){

            lNumElegivel = lTamanhoCarteira == 1 ? 7
                           : lTamanhoCarteira == 2 ? 8
                           : lTamanhoCarteira == 3 ? 9
                           : 9999;

        }else if(aCargo == 'LÍDER'){

            lNumElegivel = lTamanhoCarteira == 1 ? 7
                           : lTamanhoCarteira == 2 ? 8
                           : 9999;

        } else if(aCargo == 'DIRETOR'){
            lNumElegivel = 7;
        } else {
            lNumElegivel = 7;
        }

        return lNumElegivel;
    }

}