force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_NovoContratado__c.field-meta.xml
<CustomField>
    <fullName>V_NovoContratado__c</fullName>
    <description>Indica se o participante é um novo contratado ou não.</description>
    <inlineHelpText>Indica se o participante é um novo contratado ou não.</inlineHelpText>
    <label>Novo Contratado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_PapelElite__c.field-meta.xml
<CustomField>
    <fullName>V_PapelElite__c</fullName>
    <label>Papel Elite</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DIRETORES</fullName>
            </value>
            <value>
                <fullName>GERENTES DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDERES</fullName>
            </value>
            <value>
                <fullName>LÍDERES (COORDENADORES) E GERENTE REGIONAIS</fullName>
            </value>
            <value>
                <fullName>NÃO ELEGÍVEL</fullName>
                <default>true</default>
                <label>NÃO ELEGÍVEL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_ScoreElite__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreElite__c</fullName>
    <description>Score Elite do ano fiscal vigente.</description>
    <formula>V_MetasAnoFiscalVigenteNovo__r.V_ScoreElite__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Score Elite do ano fiscal vigente.</inlineHelpText>
    <label>Score Elite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PapelElite__c.field-meta.xml
<CustomField>
    <fullName>V_PapelElite__c</fullName>
    <formula>TEXT(V_Participante__r.V_PapelElite__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Papel Elite</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Participante__c.field-meta.xml
<CustomField>
    <fullName>V_Participante__c</fullName>
    <description>Participante relacionado à meta.</description>
    <inlineHelpText>Participante relacionado à meta.</inlineHelpText>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ParticRankingElite__c.field-meta.xml
<CustomField>
    <fullName>V_ParticRankingElite__c</fullName>
    <formula>AND(TEXT( V_Participante__r.FieloPLT__Status__c ) = &apos;Active&apos;,
TEXT( V_Participante__r.V_NovoContratado__c) = &apos;Não&apos;,
NOT(CONTAINS( UPPER( V_Participante__r.Name), &apos;TESTE&apos;)),
(V_PapelElite__c &lt;&gt; &apos;NÃO ELEGÍVEL&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Participa Ranking Elite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualMetaYTD__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualMetaYTD__c</fullName>
    <formula>V_AMYTD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% Meta YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PosicaoRankingElite__c.field-meta.xml
<CustomField>
    <fullName>V_PosicaoRankingElite__c</fullName>
    <label>Posição Ranking Elite</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ScoreElite__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreElite__c</fullName>
    <formula>V_ScoreAtingimentoFY__c + V_ScoreSuperacaoFY__c + V_ScoreSuperacaoQ1__c + V_ScorePotencialCarteira__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score Elite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_TotalVendasYTD__c.field-meta.xml
<CustomField>
    <fullName>V_TotalVendasYTD__c</fullName>
    <label>Total de Vendas -YTD</label>
    <summarizedField>VN_Sumarizador__c.V_Valor__c</summarizedField>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_ProcessarMecanicas__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>VN_Sumarizador__c.V_MetaDoParticipante__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/SX_BatchAtualizarRankingNaMeta.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 09/08/2019
* 
* Name: SX_BatchAtualizarRankingNaMeta.cls
* 
* Batch para atualizar o campo V_PosicaoRankingElite__c na VN_MetaParticipante__c
*******************************************************************************/
global class SX_BatchAtualizarRankingNaMeta implements Database.Batchable<sObject>, Database.Stateful,Schedulable {
    
    global Set<String> fSetAnoFiscal;
    global String DIRETOR = 'DIRETORES'; 
    global String LIDER = 'LÍDERES'; 
    global String GERENTE = 'GERENTES DE CONTAS'; 
    global String COORD_GER_REGIONAL = 'LÍDERES (COORDENADORES) E GERENTE REGIONAIS'; 
    global Integer lPosicaoDiretor;
    global Integer lPosicaoLider;
    global Integer lPosicaoGerente;
    global Integer lPosicaoCoordGerenteReg;
    global Integer lPosicaoRanking;

    global void execute(SchedulableContext sc) {
        Database.executeBatch(this, 200);
    }
    
    global SX_BatchAtualizarRankingNaMeta(Set<String> aSetAnoFiscal) {

        if(SX_Utils.batchIsProcessing('SX_BatchAtualizarRankingNaMeta')) return;
        fSetAnoFiscal = aSetAnoFiscal;
        lPosicaoDiretor = 1;
		lPosicaoLider = 1;
		lPosicaoGerente = 1;
		lPosicaoCoordGerenteReg = 1;
        lPosicaoRanking = 0;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        // critério de desempate alterado 06/08/19 - #task 16632
        return Database.getQueryLocator([SELECT Id, V_Participante__r.V_NovoContratado__c, V_PosicaoRankingElite__c,
                                         V_ParticRankingElite__c, V_PapelElite__c
                                        FROM VN_MetaParticipante__c
                                        WHERE  Name =: fSetAnoFiscal
										AND (NOT V_Participante__r.Name like '%VAGO_%') // add 10/10 task #17343
										AND (NOT V_Participante__r.Name like '%CARTEIRA_AFASTADO_%') // add 30/10 task #17394
                                        ORDER BY V_ScoreElite__c DESC, V_PercentualMetaYTD__c DESC, V_TotalVendasYTD__c DESC, V_Participante__r.Name ASC]);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {

		if ( scope == null || scope.isEmpty()) return;
		List<VN_MetaParticipante__c> lLstMetaToUpdate = new List<VN_MetaParticipante__c>();

		for(VN_MetaParticipante__c meta: (List<VN_MetaParticipante__c>) scope){

			if( !meta.V_ParticRankingElite__c || meta.V_Participante__r.V_NovoContratado__c == 'Sim' 
				|| meta.V_PapelElite__c == 'NÃO ELEGÍVEL') {

		        lPosicaoRanking = 0;

			} else {

				if(meta.V_PapelElite__c == DIRETOR){

					lPosicaoRanking = lPosicaoDiretor;
					lPosicaoDiretor ++;

				} else if(meta.V_PapelElite__c == LIDER){

					lPosicaoRanking = lPosicaoLider;
					lPosicaoLider ++;

				} else if(meta.V_PapelElite__c == GERENTE){

					lPosicaoRanking = lPosicaoGerente;
					lPosicaoGerente ++;

				} else if(meta.V_PapelElite__c == COORD_GER_REGIONAL){

					lPosicaoRanking = lPosicaoCoordGerenteReg;
					lPosicaoCoordGerenteReg ++;
				}
			}

			if(lPosicaoRanking != null){
				lLstMetaToUpdate.add(
                    new VN_MetaParticipante__c(
						Id = meta.Id,
						V_PosicaoRankingElite__c = lPosicaoRanking
					)
				);
			}
		}

		if(!lLstMetaToUpdate.isEmpty()) update lLstMetaToUpdate;      
    }
    
    global void finish(Database.BatchableContext BC) {
    }

}