force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_CodigoCarteira__c.field-meta.xml
<CustomField>
    <fullName>V_CodigoCarteira__c</fullName>
    <description>Código de carteira atual do participante.</description>
    <externalId>true</externalId>
    <inlineHelpText>Código de carteira atual do participante.</inlineHelpText>
    <label>Código Carteira</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_CodigoLeaderSetor__c.field-meta.xml
<CustomField>
    <fullName>V_CodigoLeaderSetor__c</fullName>
    <label>Código Leader Setor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/VN_CargasDadosTemp__c.object-meta.xml
<CustomObject>
    <description>Utilizado para receber as cargas de dados temporária das integrações com o Fielo.</description>
    <label>Carga de Dados Temp</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>No. Carga Dados</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargas de Dados Temp</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <description>Ano fiscal relacionado ao registro da carga de dados.</description>
    <inlineHelpText>Ano fiscal relacionado ao registro da carga de dados.</inlineHelpText>
    <label>Ano Fiscal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_CodigoCoordenadorVenda1__c.field-meta.xml
<CustomField>
    <fullName>V_CodigoCoordenadorVenda1__c</fullName>
    <label>Cod Coordenador Vendas 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_CodigoCoordenadorVendas2__c.field-meta.xml
<CustomField>
    <fullName>V_CodigoCoordenadorVendas2__c</fullName>
    <label>Cód Coordenador Vendas 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_CodigodoResponsavel3__c.field-meta.xml
<CustomField>
    <fullName>V_CodigodoResponsavel3__c</fullName>
    <label>Cod do Responsavel 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_CodigoGerentedeVendas__c.field-meta.xml
<CustomField>
    <fullName>V_CodigoGerentedeVendas__c</fullName>
    <label>Cod  Gerente de Vendas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_CodigoLeaderSetor__c.field-meta.xml
<CustomField>
    <fullName>V_CodigoLeaderSetor__c</fullName>
    <label>Cod Leader Setor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_CodigoLideranca__c.field-meta.xml
<CustomField>
    <fullName>V_CodigoLideranca__c</fullName>
    <description>Liderança do participante responsável pelo resultado do período. Para efeito de histórico.</description>
    <inlineHelpText>Liderança do participante responsável pelo resultado do período. Para efeito de histórico.</inlineHelpText>
    <label>Cod Dir Liderança</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_Mes__c.field-meta.xml
<CustomField>
    <fullName>V_Mes__c</fullName>
    <label>Mês</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_Meta__c.field-meta.xml
<CustomField>
    <fullName>V_Meta__c</fullName>
    <label>Meta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_SumarizadorCoordVendas1__c.field-meta.xml
<CustomField>
    <fullName>V_SumarizadorCoordVendas1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sumarizador Coordenador Vendas 1</label>
    <referenceTo>VN_Sumarizador__c</referenceTo>
    <relationshipLabel>Cargas de Dados Temp (Sumarizador Coordenador Vendas 1)</relationshipLabel>
    <relationshipName>Cargas_de_Dados_Temp3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_SumarizadorCoordVendas2__c.field-meta.xml
<CustomField>
    <fullName>V_SumarizadorCoordVendas2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sumarizador Coordenador Vendas 2</label>
    <referenceTo>VN_Sumarizador__c</referenceTo>
    <relationshipLabel>Cargas de Dados Temp (Sumarizador Coordenador Vendas 2)</relationshipLabel>
    <relationshipName>Cargas_de_Dados_Temp4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_SumarizadorDirLideranca__c.field-meta.xml
<CustomField>
    <fullName>V_SumarizadorDirLideranca__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sumarizador Dir Liderança</label>
    <referenceTo>VN_Sumarizador__c</referenceTo>
    <relationshipLabel>Cargas de Dados Temp (Sumarizador Dir Liderança)</relationshipLabel>
    <relationshipName>Cargas_de_Dados_Temp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_SumarizadorGerenteVendas__c.field-meta.xml
<CustomField>
    <fullName>V_SumarizadorGerenteVendas__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sumarizador Gerente Vendas</label>
    <referenceTo>VN_Sumarizador__c</referenceTo>
    <relationshipLabel>Cargas de Dados Temp (Sumarizador Gerente Vendas)</relationshipLabel>
    <relationshipName>Cargas_de_Dados_Temp2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_SumarizadorLeaderSetor__c.field-meta.xml
<CustomField>
    <fullName>V_SumarizadorLeaderSetor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sumarizador Leader Setor</label>
    <referenceTo>VN_Sumarizador__c</referenceTo>
    <relationshipLabel>Cargas de Dados Temp (Sumarizador Leader Setor)</relationshipLabel>
    <relationshipName>Cargas_de_Dados_Temp1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/VN_GerenciadorMetaParticipanteAF__c.object-meta.xml
<CustomObject>
    <description>Gerenciador dos registros de metas dos participantes por Ano Fiscal.</description>
    <label>Gerenciador Meta Participante AF</label>
    <nameField>
        <displayFormat>GMAF-{000000}</displayFormat>
        <label>No. Gerenciador Ano Fiscal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gerenciador Metas Participantes AF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <description>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</description>
    <inlineHelpText>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</inlineHelpText>
    <label>Ano Fiscal</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_DataFim__c.field-meta.xml
<CustomField>
    <fullName>V_DataFim__c</fullName>
    <description>Data final do ano fiscal.</description>
    <inlineHelpText>Data final do ano fiscal.</inlineHelpText>
    <label>Data Fim</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_DataInicio__c.field-meta.xml
<CustomField>
    <fullName>V_DataInicio__c</fullName>
    <description>Data de início do ano fiscal.</description>
    <inlineHelpText>Data de início do ano fiscal.</inlineHelpText>
    <label>Data Início</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sinaliza se o gerenciador é o que está em vigência.</description>
    <inlineHelpText>Sinaliza se o gerenciador é o que está em vigência.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ano fiscal da Meta do participante do participante</description>
    <label>Gerenciador Meta Participante AF</label>
    <referenceTo>VN_GerenciadorMetaParticipanteAF__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Meta__c.field-meta.xml
<CustomField>
    <fullName>V_Meta__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Meta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Participante__c.field-meta.xml
<CustomField>
    <fullName>V_Participante__c</fullName>
    <description>Participante relacionado à meta.</description>
    <inlineHelpText>Participante relacionado à meta.</inlineHelpText>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ResultadoSE__c.field-meta.xml
<CustomField>
    <fullName>V_ResultadoSE__c</fullName>
    <label>Resultado SE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Valor__c.field-meta.xml
<CustomField>
    <fullName>V_Valor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <description>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</description>
    <formula>V_AnoFiscal__r.V_Vigente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/VN_Sumarizador__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por sumarizar as metas, resultados e ponderados das informações carregas ou atualizadas.</description>
    <label>Sumarizador</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Código do Sumarizador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sumarizadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_Sumarizador__c/fields/Participante__c.field-meta.xml
<CustomField>
    <fullName>Participante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relacionamento entre o participante e o sumarizador para poder gerar a pontuação</description>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Sumarizadores</relationshipLabel>
    <relationshipName>Sumarizadores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Mes__c.field-meta.xml
<CustomField>
    <fullName>V_Mes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Faz referência ao mês corrente da meta</description>
    <label>Mês Meta</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Meta__c.field-meta.xml
<CustomField>
    <fullName>V_Meta__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Meta Mensal, sumarização da meta da carga por participante</description>
    <inlineHelpText>Faz referência a Meta mensal do Participante.</inlineHelpText>
    <label>Meta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_MetaDoParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_MetaDoParticipante__c</fullName>
    <description>Meta dos participantes</description>
    <label>Meta do Participante</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipName>VN_SumarizadoresDosObjetivos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ProcessarCalculos__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarCalculos__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Ao ser assinalado esse campo, os workflows de cálculo do registro serão acionados.</description>
    <inlineHelpText>Ao ser assinalado esse campo, os workflows de cálculo do registro serão acionados.</inlineHelpText>
    <label>Processar Cálculos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ResultadoSE__c.field-meta.xml
<CustomField>
    <fullName>V_ResultadoSE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Resultado SE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Valor__c.field-meta.xml
<CustomField>
    <fullName>V_Valor__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Sumarizador que faz referência ao resultado atingido pelo participante</description>
    <inlineHelpText>Faz referência ao resultado atingido pelo participante</inlineHelpText>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/VN_CargaDadosTempHandler.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: PV                                           date: 28/06/2019
* 
* Name: VN_CargaDadosTempHandler.cls
* 
* Handler trigger de VN_CargasDadosTemp__c
*******************************************************************************/
public with sharing class VN_CargaDadosTempHandler {

    private static Map<String, Id> fMapCodCarteiraMemberId;
    private static Map<Id, Map<Integer, VN_Sumarizador__c>> fMapMemberIdMapMesSum;
    private static Map<Id, VN_GerenciadorMetaParticipanteAF__c> fMapMemberIdGerenciadorMeta;

    private static Map<Id, VN_Sumarizador__c> fMapSumarizadorToUpdate;

    public static void updateSumarizador() {
        VN_TriggerCheck.assert();
		
        List<VN_CargasDadosTemp__c> lCargasDadosTempLst = (List<VN_CargasDadosTemp__c>)Trigger.new;
        
        //popula map codcarteira -> member
        fMapCodCarteiraMemberId = new Map<String, Id>();
        for(VN_CargasDadosTemp__c lCargasDadosTemp : lCargasDadosTempLst){
            initMapCarteira(lCargasDadosTemp, fMapCodCarteiraMemberId);
        }
        for(FieloPLT__Member__c lMember : [SELECT Id, V_CodigoCarteira__c FROM FieloPLT__Member__c 
                WHERE V_CodigoCarteira__c =:fMapCodCarteiraMemberId.keySet()]){
            fMapCodCarteiraMemberId.put(lMember.V_CodigoCarteira__c, lMember.Id);
        }
        System.debug(fMapCodCarteiraMemberId);

        //popula map member -> gerenciador meta
        fMapMemberIdGerenciadorMeta = new Map<Id, VN_GerenciadorMetaParticipanteAF__c>();
        for(VN_MetaParticipante__c lMetaParticipante : [SELECT V_Participante__c,
                V_AnoFiscal__r.V_DataInicio__c, V_AnoFiscal__r.V_DataFim__c 
                FROM VN_MetaParticipante__c WHERE V_Participante__c = :fMapCodCarteiraMemberId.values()
                AND V_AnoFiscal__r.V_Vigente__c = true]){
            if(!fMapMemberIdGerenciadorMeta.containsKey(lMetaParticipante.V_Participante__c)){
                fMapMemberIdGerenciadorMeta.put(lMetaParticipante.V_Participante__c, lMetaParticipante.V_AnoFiscal__r);
            }
        }
        System.debug(fMapMemberIdGerenciadorMeta);

        //popula map member/mes -> sumarizador
        fMapMemberIdMapMesSum = new Map<Id, Map<Integer, VN_Sumarizador__c>>();
        for(VN_Sumarizador__c lSumarizador : [SELECT Participante__c, V_Mes__c, V_Meta__c, V_Valor__c, V_ResultadoSE__c
                FROM VN_Sumarizador__c WHERE Participante__c = :fMapCodCarteiraMemberId.values()
                AND V_MetaDoParticipante__r.V_AnoFiscal__r.V_Vigente__c = true
                //AND V_ProcessarCalculos__c = false
                ]){
            
            if(!fMapMemberIdMapMesSum.containsKey(lSumarizador.Participante__c)){
                fMapMemberIdMapMesSum.put(lSumarizador.Participante__c, new Map<Integer, VN_Sumarizador__c>());
            }
            if(!fMapMemberIdMapMesSum.get(lSumarizador.Participante__c).containsKey(lSumarizador.V_Mes__c.intValue()) ){
                fMapMemberIdMapMesSum.get(lSumarizador.Participante__c).put(lSumarizador.V_Mes__c.intValue(), lSumarizador);
            }
        }
        System.debug(fMapMemberIdMapMesSum);

        //
        // Processa os registros
        //

        fMapSumarizadorToUpdate = new Map<Id, VN_Sumarizador__c>();
        for(VN_CargasDadosTemp__c lCargasDadosTemp : lCargasDadosTempLst){
            processaItemCargaDados(lCargasDadosTemp);
        }

        if(!fMapSumarizadorToUpdate.isEmpty()){
            update fMapSumarizadorToUpdate.values();
        }
    }

    private static void processaItemCargaDados(VN_CargasDadosTemp__c aCargasDadosTemp){
        System.debug(aCargasDadosTemp);
        if(aCargasDadosTemp == null) return;

        Date lDate = Date.parse(aCargasDadosTemp.V_Mes__c);
        if(lDate != null){
            processaCampo(aCargasDadosTemp, 'V_CodigoLideranca__c', 'V_SumarizadorDirLideranca__c', lDate);
            processaCampo(aCargasDadosTemp, 'V_CodigoLeaderSetor__c', 'V_SumarizadorLeaderSetor__c', lDate);
            processaCampo(aCargasDadosTemp, 'V_CodigoGerentedeVendas__c', 'V_SumarizadorGerenteVendas__c', lDate);
            processaCampo(aCargasDadosTemp, 'V_CodigoCoordenadorVenda1__c', 'V_SumarizadorCoordVendas1__c', lDate);
            processaCampo(aCargasDadosTemp, 'V_CodigoCoordenadorVendas2__c', 'V_SumarizadorCoordVendas2__c', lDate);
            processaCampo(aCargasDadosTemp, 'V_CodigodoResponsavel3__c', 'V_SumarizadorResponsavel3__c', lDate);
            processaCampo(aCargasDadosTemp, 'V_CodigodoResponsavel2__c', 'V_SumarizadorResponsavel2__c', lDate);
            processaCampo(aCargasDadosTemp, 'V_CodigodoResponsavel1__c', 'V_SumarizadorResponsavel1__c', lDate);
            //processaCampo(aCargasDadosTemp, 'V_CodigoResponsavelCarteira__c', 'V_SumarizadorResponsavelCarteira__c', lDate);
        }
    }

    private static void processaCampo(SObject aCargasDadosTemp, String aFieldName, String aLookupSumarizadorFieldName, Date aDate){
        String lCod = (String)aCargasDadosTemp.get(aFieldName);
        if(String.isNotEmpty(lCod)) {
            Id lMemberId = fMapCodCarteiraMemberId.get(lCod);
            if(lMemberId != null){
                VN_GerenciadorMetaParticipanteAF__c lGm = fMapMemberIdGerenciadorMeta.get(lMemberId);
                if(lGm != null){
                    Integer lMesMeta = getMesMeta(lGm, aDate);
                    Map<Integer, VN_Sumarizador__c> lMapMesSum = fMapMemberIdMapMesSum.get(lMemberId);
                    if(lMapMesSum != null && !lMapMesSum.isEmpty() && lMapMesSum.containsKey(lMesMeta)){
                        VN_Sumarizador__c lSumarizador = lMapMesSum.get(lMesMeta);
                        if(lSumarizador != null){
                            updateValuesSumarizador((VN_CargasDadosTemp__c)aCargasDadosTemp, lSumarizador, aLookupSumarizadorFieldName);
                        }
                    }
                }
            }
        }
    }
    
    private static void updateValuesSumarizador(VN_CargasDadosTemp__c aCargasDadosTemp, VN_Sumarizador__c aSumarizador, String aLookupSumarizadorFieldName){
        if(aCargasDadosTemp == null || aSumarizador == null) return;

        //insert (soma)
        if(Trigger.isInsert){
            if(aSumarizador.V_Meta__c == null) aSumarizador.V_Meta__c = 0.0;
            aSumarizador.V_Meta__c += String.isEmpty(aCargasDadosTemp.V_Meta__c) ? 0.0 : Double.valueOf(aCargasDadosTemp.V_Meta__c);
            
            if(aSumarizador.V_Valor__c == null) aSumarizador.V_Valor__c = 0.0;
            aSumarizador.V_Valor__c += String.isEmpty(aCargasDadosTemp.V_ResultadoTotal__c) ? 0.0 : Double.valueOf(aCargasDadosTemp.V_ResultadoTotal__c);
            
            if(aSumarizador.V_ResultadoSE__c == null) aSumarizador.V_ResultadoSE__c = 0.0;
            aSumarizador.V_ResultadoSE__c += String.isEmpty(aCargasDadosTemp.V_ProdutosEstrategicos__c) ? 0.0 : Double.valueOf(aCargasDadosTemp.V_ProdutosEstrategicos__c);

            fMapSumarizadorToUpdate.put(aSumarizador.Id, aSumarizador);
        } 
        //update (subtrai o valor antigo e soma o novo)
        else if(Trigger.isUpdate) { 
            VN_CargasDadosTemp__c lCargasDadosTempOld = (VN_CargasDadosTemp__c)Trigger.oldMap.get(aCargasDadosTemp.Id);
            if(aSumarizador.V_Meta__c == null) aSumarizador.V_Meta__c = 0.0;
            aSumarizador.V_Meta__c -= String.isEmpty(lCargasDadosTempOld.V_Meta__c) ? 0.0 : Double.valueOf(lCargasDadosTempOld.V_Meta__c);
            
            if(aSumarizador.V_Valor__c == null) aSumarizador.V_Valor__c = 0.0;
            aSumarizador.V_Valor__c -= String.isEmpty(lCargasDadosTempOld.V_ResultadoTotal__c) ? 0.0 : Double.valueOf(lCargasDadosTempOld.V_ResultadoTotal__c);
            
            if(aSumarizador.V_ResultadoSE__c == null) aSumarizador.V_ResultadoSE__c = 0.0;
            aSumarizador.V_ResultadoSE__c -= String.isEmpty(lCargasDadosTempOld.V_ProdutosEstrategicos__c) ? 0.0 : Double.valueOf(lCargasDadosTempOld.V_ProdutosEstrategicos__c);

            aSumarizador.V_Meta__c += String.isEmpty(aCargasDadosTemp.V_Meta__c) ? 0.0 : Double.valueOf(aCargasDadosTemp.V_Meta__c);
            aSumarizador.V_Valor__c += String.isEmpty(aCargasDadosTemp.V_ResultadoTotal__c) ? 0.0 : Double.valueOf(aCargasDadosTemp.V_ResultadoTotal__c);
            aSumarizador.V_ResultadoSE__c += String.isEmpty(aCargasDadosTemp.V_ProdutosEstrategicos__c) ? 0.0 : Double.valueOf(aCargasDadosTemp.V_ProdutosEstrategicos__c);

            fMapSumarizadorToUpdate.put(aSumarizador.Id, aSumarizador);
        }

        //ajuste task #17172 - 27/09/2019
        //aCargasDadosTemp.V_Sumarizador__c = aSumarizador.Id;
        if(!String.isEmpty(aLookupSumarizadorFieldName)){
            aCargasDadosTemp.put(aLookupSumarizadorFieldName, aSumarizador.Id);
        }
        
    }

    private static void initMapCarteira(VN_CargasDadosTemp__c aCargasDadosTemp, Map<String, Id> aMapCodCarteiraMemberId){
        if(String.isNotEmpty(aCargasDadosTemp.V_CodigoLideranca__c)) aMapCodCarteiraMemberId.put(aCargasDadosTemp.V_CodigoLideranca__c, null);
        if(String.isNotEmpty(aCargasDadosTemp.V_CodigoLeaderSetor__c)) aMapCodCarteiraMemberId.put(aCargasDadosTemp.V_CodigoLeaderSetor__c, null);
        if(String.isNotEmpty(aCargasDadosTemp.V_CodigoGerentedeVendas__c)) aMapCodCarteiraMemberId.put(aCargasDadosTemp.V_CodigoGerentedeVendas__c, null);
        if(String.isNotEmpty(aCargasDadosTemp.V_CodigoCoordenadorVenda1__c)) aMapCodCarteiraMemberId.put(aCargasDadosTemp.V_CodigoCoordenadorVenda1__c, null);
        if(String.isNotEmpty(aCargasDadosTemp.V_CodigoCoordenadorVendas2__c)) aMapCodCarteiraMemberId.put(aCargasDadosTemp.V_CodigoCoordenadorVendas2__c, null);
        if(String.isNotEmpty(aCargasDadosTemp.V_CodigodoResponsavel3__c)) aMapCodCarteiraMemberId.put(aCargasDadosTemp.V_CodigodoResponsavel3__c, null);
        if(String.isNotEmpty(aCargasDadosTemp.V_CodigodoResponsavel2__c)) aMapCodCarteiraMemberId.put(aCargasDadosTemp.V_CodigodoResponsavel2__c, null);
        if(String.isNotEmpty(aCargasDadosTemp.V_CodigodoResponsavel1__c)) aMapCodCarteiraMemberId.put(aCargasDadosTemp.V_CodigodoResponsavel1__c, null);
        if(String.isNotEmpty(aCargasDadosTemp.V_CodigoResponsavelCarteira__c)) aMapCodCarteiraMemberId.put(aCargasDadosTemp.V_CodigoResponsavelCarteira__c, null);
    }

    public static Integer getMesMeta(VN_GerenciadorMetaParticipanteAF__c aGerenciadorMetaParticipanteAF, Date aDate){
        Date lDataIniGm = aGerenciadorMetaParticipanteAF.V_DataInicio__c;
        Integer lMonthRange = aGerenciadorMetaParticipanteAF.V_DataInicio__c.monthsBetween(aGerenciadorMetaParticipanteAF.V_DataFim__c)+1;
        for(Integer i = 1; i <= lMonthRange; i++){
            if(aDate.month() == lDataIniGm.month()){
                return i;
            } else {
                lDataIniGm = lDataIniGm.addMonths(1);
            }
        }
        return 0;
    }
}