force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program that the Member belongs to.</description>
    <inlineHelpText>The Program that the Member belongs to</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</description>
    <inlineHelpText>Choose Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Area__c.field-meta.xml
<CustomField>
    <fullName>V_Area__c</fullName>
    <description>Área do participante.</description>
    <inlineHelpText>Área do participante.</inlineHelpText>
    <label>Área</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VERTICAIS</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo atual do participante.</description>
    <inlineHelpText>Cargo atual do participante.</inlineHelpText>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COORDENADOR | GERENTE REGIONAL VIP</fullName>
            </value>
            <value>
                <fullName>DIRETOR</fullName>
            </value>
            <value>
                <fullName>GERENTE DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDER</fullName>
            </value>
            <value>
                <fullName>COORDENADOR II</fullName>
                <isActive>false</isActive>
                <label>COORDENADOR II</label>
            </value>
            <value>
                <fullName>GERENTE DE VENDAS</fullName>
                <isActive>false</isActive>
                <label>GERENTE DE VENDAS</label>
            </value>
            <value>
                <fullName>VICE-PRESIDENTE</fullName>
                <isActive>false</isActive>
                <label>VICE-PRESIDENTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Lideranca__c.field-meta.xml
<CustomField>
    <fullName>V_Lideranca__c</fullName>
    <description>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</description>
    <inlineHelpText>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</inlineHelpText>
    <label>Liderança</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>MULTI SECTOR</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
            <value>
                <fullName>VAREJO, CPG E PAGAMENTOS</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS</fullName>
            </value>
            <value>
                <fullName>SERASA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Setor__c.field-meta.xml
<CustomField>
    <fullName>V_Setor__c</fullName>
    <description>Campo dependente do campo &quot;Liderança&quot;.</description>
    <inlineHelpText>Campo dependente do campo &quot;Liderança&quot;.</inlineHelpText>
    <label>Setor</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>V_Lideranca__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BANCO DO BRASIL</fullName>
            </value>
            <value>
                <fullName>BRADESCO</fullName>
            </value>
            <value>
                <fullName>CAIXA ECONÔMICA</fullName>
            </value>
            <value>
                <fullName>ITAÚ</fullName>
            </value>
            <value>
                <fullName>SANTANDER</fullName>
            </value>
            <value>
                <fullName>BENS DURÁVEIS E SERVIÇOS</fullName>
            </value>
            <value>
                <fullName>COOPERATIVAS</fullName>
            </value>
            <value>
                <fullName>SETOR PÚBLICO</fullName>
            </value>
            <value>
                <fullName>TELECOM, MÍDIA E TECNOLOGIA</fullName>
            </value>
            <value>
                <fullName>UTILITIES</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS BR</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS SP</fullName>
            </value>
            <value>
                <fullName>SEGUROS</fullName>
            </value>
            <value>
                <fullName>CO, NO e NE</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>REGIÕES WINBACK</fullName>
            </value>
            <value>
                <fullName>RJ, MG e ES</fullName>
            </value>
            <value>
                <fullName>RS e SC</fullName>
            </value>
            <value>
                <fullName>SP I</fullName>
            </value>
            <value>
                <fullName>SP II</fullName>
            </value>
            <value>
                <fullName>SP INTERIOR</fullName>
            </value>
            <value>
                <fullName>CONVÊNIO SPC SERASA EXPERIAN</fullName>
            </value>
            <value>
                <fullName>DISTRIBUIDOR</fullName>
            </value>
            <value>
                <fullName>MULTICANAL WINBACK</fullName>
            </value>
            <value>
                <fullName>REMOTO</fullName>
            </value>
            <value>
                <fullName>VIP MG, CO e NO</fullName>
            </value>
            <value>
                <fullName>VIP RJ, ES e NE</fullName>
            </value>
            <value>
                <fullName>VIP SP I</fullName>
            </value>
            <value>
                <fullName>VIP SP II</fullName>
            </value>
            <value>
                <fullName>VIP SUL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/FieloPLT__Reward__c.object-meta.xml
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Reward__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Program that the Reward is associated with.</description>
    <inlineHelpText>The Program in which you&apos;ll use this Reward</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_AreaElegivelYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_AreaElegivelYoubet__c</fullName>
    <description>Área do participante elegível ao Youbet.</description>
    <inlineHelpText>Área do participante elegível ao Youbet.</inlineHelpText>
    <label>Área Elegível ao Youbet</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VERTICAIS</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
            <value>
                <fullName>SERASA</fullName>
                <isActive>false</isActive>
                <label>SERASA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_DataHoraFimYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_DataHoraFimYoubet__c</fullName>
    <description>Data e hora para finalizar a vigência do youbet.</description>
    <inlineHelpText>Data e hora para finalizar a vigência do youbet.</inlineHelpText>
    <label>Data/Hora Fim do Youbet</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_LiderancaElegivelYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_LiderancaElegivelYoubet__c</fullName>
    <description>Liderança do participante elegível ao Youbet.</description>
    <inlineHelpText>Liderança do participante elegível ao Youbet.</inlineHelpText>
    <label>Liderança Elegível ao Youbet</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MULTI SECTOR</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
            <value>
                <fullName>VAREJO, CPG E PAGAMENTOS</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS</fullName>
            </value>
            <value>
                <fullName>GRANDES BANCOS</fullName>
                <isActive>false</isActive>
                <label>GRANDES BANCOS</label>
            </value>
            <value>
                <fullName>NOVOS NEGÓCIOS</fullName>
                <isActive>false</isActive>
                <label>NOVOS NEGÓCIOS</label>
            </value>
            <value>
                <fullName>SERVIÇOS FINANCEIROS</fullName>
                <isActive>false</isActive>
                <label>SERVIÇOS FINANCEIROS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_YoubetCompleto__c.field-meta.xml
<CustomField>
    <fullName>V_YoubetCompleto__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se assinalado, indica que o cadastro do Youbet foi concluído e que a aplicação poderá relacionar os participantes que cumprirem os critérios desse Youbet para efeito de histórico e análises.</description>
    <inlineHelpText>Se assinalado, indica que o cadastro do Youbet foi concluído e que a aplicação poderá relacionar os participantes que cumprirem os critérios desse Youbet para efeito de histórico e análises.</inlineHelpText>
    <label>Youbet Completo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/VN_ParticipanteComPerfilCompativel__c.object-meta.xml
<CustomObject>
    <description>Lista relacionada do Youbet, participantes que possuem compatibilidade de cargo, área, liderança e elegibilidade no momento da criação do Youbet.</description>
    <label>Participante Com Perfil Compatível</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>No. Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes Com Perfis Compatíveis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Area__c.field-meta.xml
<CustomField>
    <fullName>V_Area__c</fullName>
    <description>Área do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Área do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Área</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Cargo do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Cargo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Lideranca__c.field-meta.xml
<CustomField>
    <fullName>V_Lideranca__c</fullName>
    <description>Liderança do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Liderança do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Liderança</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Setor__c.field-meta.xml
<CustomField>
    <fullName>V_Setor__c</fullName>
    <description>Setor do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Setor do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Setor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VN_BatchAtualizaPerfilCompativelTest.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: LK                          date: 02/12/2019
* 
* Name: VN_BatchAtualizaPerfilCompativelTest.cls
* 
* Classe de teste para VN_BatchAtualizaPerfilCompativel.cls
*******************************************************************************/
@isTest
public without sharing class VN_BatchAtualizaPerfilCompativelTest {

	static testMethod void atualizarPerfilCompativel(){
		FieloPLT__Program__c lProgram = SObjectForTest.getProgram('programName');
 		insert lProgram;

		List<FieloPLT__Member__c> lstMember = SObjectForTest.getMemberList(lProgram.Id);
		insert lstMember;
		List<FieloPLT__Member__c> lstMember2 = new List<FieloPLT__Member__c>();
 		for(FieloPLT__Member__c lMember: lstMember){
 			lMember.V_Setor__c = 'BANCOS E FINANCEIRAS BR';
 			lMember.V_Area__c = 'REGIÕES';
 			lMember.V_Lideranca__c = 'REGIÕES';
 			lMember.V_Cargo__c = 'DIRETOR';
 			lMember.FieloPLT__Status__c = Label.V_StatusAtivoMember;
 			lstMember2.add(lMember);
 		}
 		update lstMember2;

		FieloPLT__Reward__c lReward = SObjectForTest.getReward(lProgram.Id, Label.V_RecTypeLeiloes, 'Elite');
 		lReward.V_DataHoraFimYoubet__c = System.now().addDays(10);
 		lReward.V_YoubetCompleto__c = true;
 		lReward.V_AreaElegivelYoubet__c = 'REGIÕES';
 		lReward.V_LiderancaElegivelYoubet__c = 'REGIÕES';
 		lReward.V_CargoElegivelYoubet__c = 'DIRETOR';
        lReward.V_DataHoraInicioYoubet__c = System.now().addDays(1);
        insert lReward;

        List<VN_ParticipanteComPerfilCompativel__c> lstParticipanteComPerfilCompativel = new List<VN_ParticipanteComPerfilCompativel__c>();
 		lstParticipanteComPerfilCompativel = [SELECT Id FROM VN_ParticipanteComPerfilCompativel__c];
 		System.assertEquals(10, lstParticipanteComPerfilCompativel.size());

        //Dois Participantes não atendem mais o critério para participar do leilão
        lstMember2[0].V_PapelYoubet__c = 'LÍDERES';
        lstMember2[1].FieloPLT__Status__c = 'Inactive';
        update lstMember2;
        Date fData = System.today().addDays(1);
        System.assertEquals(1, [SELECT Id, 
                                        (SELECT V_Reward__r.V_PapelYoubet__c, V_Member__r.FieloPLT__Status__c,
                                        V_Member__r.V_PapelYoubet__c FROM ParticipantesPerfiCompativeis__r)   
                                        FROM FieloPLT__Reward__c 
                                        WHERE V_YoubetCompleto__c = true
                                        AND V_DataInicioYoubet__c =: fData
                                        ].size());

 		Test.startTest();
            Database.executeBatch(new VN_BatchAtualizaPerfilCompativel());

 		Test.stopTest();

        System.assertEquals(8, [SELECT Id FROM VN_ParticipanteComPerfilCompativel__c].size());
	}
}