force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_RegistroParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_RegistroParticipante__c</fullName>
    <description>Registro exclusivo do participante na Serasa Experian. Não aceita duplicidade de registros.</description>
    <externalId>true</externalId>
    <inlineHelpText>Registro exclusivo do participante na Serasa Experian. Não aceita duplicidade de registros.</inlineHelpText>
    <label>Login</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SX_ModalControllerTest.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: LK                date: 24/09/2018
*
* 
* Name: SX_ModalControllerTest.cls
* 
* Classe de testes para a classe SX_ModalController.cls
*******************************************************************************/
@isTest
public with sharing class SX_ModalControllerTest {
	static testMethod void SX_ModalControllerTest() {

		User lUser = SObjectForTest.loadUserLoggedMember();

		String lRegistro = 'test';

		FieloPLT__Member__c lMember = [select Id from FieloPLT__Member__c where FieloPLT__User__c =: lUser.Id limit 1];
		lMember.V_RegistroParticipante__c = lRegistro;
		update lMember;

 		Test.startTest();
 		System.runAs(lUser) {
 			String lNickname = SX_ModalController.setNickname1(lRegistro, 'test', 'test');
 			String lFgPass = SX_ModalController.doForgotPassword('test');
 		}	
 		Test.stopTest();
	}
}