force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Member&apos;s points.</description>
    <inlineHelpText>Member&apos;s points.</inlineHelpText>
    <label>Points</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program that the Member belongs to.</description>
    <inlineHelpText>The Program that the Member belongs to</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</description>
    <inlineHelpText>Choose Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Area__c.field-meta.xml
<CustomField>
    <fullName>V_Area__c</fullName>
    <description>Área do participante.</description>
    <inlineHelpText>Área do participante.</inlineHelpText>
    <label>Área</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VERTICAIS</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Saldo de betcoins (extras) do participante.Saldo de pontos gerado pela iniciativa Youbet Complementar.</description>
    <inlineHelpText>Saldo de betcoins (extras) do participante.Saldo de pontos gerado pela iniciativa Youbet Complementar.</inlineHelpText>
    <label>Betcoins - Extra</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo atual do participante.</description>
    <inlineHelpText>Cargo atual do participante.</inlineHelpText>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COORDENADOR | GERENTE REGIONAL VIP</fullName>
            </value>
            <value>
                <fullName>DIRETOR</fullName>
            </value>
            <value>
                <fullName>GERENTE DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDER</fullName>
            </value>
            <value>
                <fullName>COORDENADOR II</fullName>
                <isActive>false</isActive>
                <label>COORDENADOR II</label>
            </value>
            <value>
                <fullName>GERENTE DE VENDAS</fullName>
                <isActive>false</isActive>
                <label>GERENTE DE VENDAS</label>
            </value>
            <value>
                <fullName>VICE-PRESIDENTE</fullName>
                <isActive>false</isActive>
                <label>VICE-PRESIDENTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Lideranca__c.field-meta.xml
<CustomField>
    <fullName>V_Lideranca__c</fullName>
    <description>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</description>
    <inlineHelpText>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</inlineHelpText>
    <label>Liderança</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>MULTI SECTOR</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
            <value>
                <fullName>VAREJO, CPG E PAGAMENTOS</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS</fullName>
            </value>
            <value>
                <fullName>SERASA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_MetasAnoFiscalVigenteNovo__c.field-meta.xml
<CustomField>
    <fullName>V_MetasAnoFiscalVigenteNovo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Exibe a identificação do ano fiscal vigente do participante.</description>
    <inlineHelpText>Exibe a identificação do ano fiscal vigente do participante.</inlineHelpText>
    <label>Metas do Ano Fiscal Vigente</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipLabel>Participantes</relationshipLabel>
    <relationshipName>Participantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Setor__c.field-meta.xml
<CustomField>
    <fullName>V_Setor__c</fullName>
    <description>Campo dependente do campo &quot;Liderança&quot;.</description>
    <inlineHelpText>Campo dependente do campo &quot;Liderança&quot;.</inlineHelpText>
    <label>Setor</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>V_Lideranca__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BANCO DO BRASIL</fullName>
            </value>
            <value>
                <fullName>BRADESCO</fullName>
            </value>
            <value>
                <fullName>CAIXA ECONÔMICA</fullName>
            </value>
            <value>
                <fullName>ITAÚ</fullName>
            </value>
            <value>
                <fullName>SANTANDER</fullName>
            </value>
            <value>
                <fullName>BENS DURÁVEIS E SERVIÇOS</fullName>
            </value>
            <value>
                <fullName>COOPERATIVAS</fullName>
            </value>
            <value>
                <fullName>SETOR PÚBLICO</fullName>
            </value>
            <value>
                <fullName>TELECOM, MÍDIA E TECNOLOGIA</fullName>
            </value>
            <value>
                <fullName>UTILITIES</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS BR</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS SP</fullName>
            </value>
            <value>
                <fullName>SEGUROS</fullName>
            </value>
            <value>
                <fullName>CO, NO e NE</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>REGIÕES WINBACK</fullName>
            </value>
            <value>
                <fullName>RJ, MG e ES</fullName>
            </value>
            <value>
                <fullName>RS e SC</fullName>
            </value>
            <value>
                <fullName>SP I</fullName>
            </value>
            <value>
                <fullName>SP II</fullName>
            </value>
            <value>
                <fullName>SP INTERIOR</fullName>
            </value>
            <value>
                <fullName>CONVÊNIO SPC SERASA EXPERIAN</fullName>
            </value>
            <value>
                <fullName>DISTRIBUIDOR</fullName>
            </value>
            <value>
                <fullName>MULTICANAL WINBACK</fullName>
            </value>
            <value>
                <fullName>REMOTO</fullName>
            </value>
            <value>
                <fullName>VIP MG, CO e NO</fullName>
            </value>
            <value>
                <fullName>VIP RJ, ES e NE</fullName>
            </value>
            <value>
                <fullName>VIP SP I</fullName>
            </value>
            <value>
                <fullName>VIP SP II</fullName>
            </value>
            <value>
                <fullName>VIP SUL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/FieloPLT__Reward__c.object-meta.xml
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Reward__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Number of Points needed to redeem a Reward.</description>
    <inlineHelpText>Enter the number of Points needed to redeem this Reward.</inlineHelpText>
    <label>Points</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <description>Preencha com valor igual a 1 para Youbet Extra. E com 0 (zero) quando for Youbet Perene.</description>
    <inlineHelpText>Preencha com valor igual a 1 para Youbet Extra. E com 0 (zero) quando for Youbet Perene</inlineHelpText>
    <label>Betcoins - Extra</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/VN_ParticipanteComPerfilCompativel__c.object-meta.xml
<CustomObject>
    <description>Lista relacionada do Youbet, participantes que possuem compatibilidade de cargo, área, liderança e elegibilidade no momento da criação do Youbet.</description>
    <label>Participante Com Perfil Compatível</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>No. Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes Com Perfis Compatíveis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Area__c.field-meta.xml
<CustomField>
    <fullName>V_Area__c</fullName>
    <description>Área do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Área do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Área</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Cargo do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Cargo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Lideranca__c.field-meta.xml
<CustomField>
    <fullName>V_Lideranca__c</fullName>
    <description>Liderança do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Liderança do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Liderança</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Setor__c.field-meta.xml
<CustomField>
    <fullName>V_Setor__c</fullName>
    <description>Setor do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Setor do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Setor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SX_YoubetBetsControllerTest.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: LK                date: 24/09/2018
*
* 
* Name: SX_YoubetBetsControllerTest.cls
* 
* Classe de testes para a classe SX_YoubetBetsController.cls
*******************************************************************************/
@isTest
public with sharing class SX_YoubetBetsControllerTest {
	static testMethod void SX_YoubetBetsControllerTest() {

		User lUser = SObjectForTest.loadUserLoggedMember();

		VN_GerenciadorMetaParticipanteAF__c lGerenciador = SObjectForTest.getGerenciadorMetaParticipante();
 		insert lGerenciador;

 		FieloPLT__Member__c lMember = [select Id from FieloPLT__Member__c where FieloPLT__User__c =: lUser.Id limit 1];

 		VN_MetaParticipante__c lMeta = SObjectForTest.getMetasNovaEstrutura(lMember.Id, lGerenciador.Id, Label.V_AnoFiscal);
 		insert lMeta;

		lMember.V_Setor__c = 'BANCOS E FINANCEIRAS SP';
 		lMember.V_Area__c = 'VERTICAIS';
 		lMember.V_Lideranca__c = 'SERVIÇOS FINANCEIROS';
 		lMember.V_Cargo__c = 'DIRETOR';
 		lMember.FieloPLT__Status__c = Label.V_StatusAtivoMember;
 		lMember.V_MetasAnoFiscalVigenteNovo__c = lMeta.Id;
		FieloPLT.SobjectService.enableAdminPermission(true);
		lMember.V_BetcoinsComp__c = 11;
		lMember.FieloPLT__Points__c = 11;
		update lMember;
		FieloPLT.SobjectService.enableAdminPermission(false);	

 		FieloPLT__Program__c lProgram = [select Id, Name from FieloPLT__Program__c where Name =: 'programName' limit 1];

 		FieloPLT__Reward__c lReward = SObjectForTest.getReward(lProgram.Id, Label.V_RecTypeLeiloes, 'Elite');
 		lReward.V_YoubetCompleto__c = true;
 		lReward.V_AreaElegivelYoubet__c = 'VERTICAIS';
 		lReward.V_LiderancaElegivelYoubet__c = 'REGIÕES';
 		lReward.V_CargoElegivelYoubet__c = 'DIRETOR';
 		insert lReward;

 		Test.startTest();
 		System.runAs(lUser) {
 			FieloPLT__Member__C lMember1 = SX_YoubetBetsContoller.getMember(); 
 			Boolean lPodedarLance = SX_YoubetBetsContoller.podeDarLance(lReward.Id);
 			System.assertNotEquals(lMember1, null);
 		}
 		FieloPLT__Reward__c lReward1 = SX_YoubetBetsContoller.getReward(lMember.Id,'youbet');
 		FieloPLT__Reward__c lReward2 = SX_YoubetBetsContoller.youbetFuturo('test', lReward.Id);
 		System.assertEquals(lReward1, null);

 		lReward.Iniciativa__c = Label.V_IniciativaComplementar;
 		lReward.V_DataHoraFimYoubet__c = System.today().addDays(1);
 		lReward.FieloPLT__ExpirationDate__c = System.today().addDays(1);
 		lReward.FieloPLT__Points__c = 0;
 		lReward.V_BetcoinsComp__c = 1;
 		update lReward;

		FieloPLT__Reward__c lProximoReward = lReward.clone(false, false, false, false);
		lProximoReward.V_DataHoraInicioYoubet__c = System.today().addDays(10);
		lProximoReward.V_DataHoraFimYoubet__c = System.today().addDays(20);
		lProximoReward.Iniciativa__c = Label.V_IniciativaPerene;
		lProximoReward.FieloPLT__Points__c = 1;
 		lProximoReward.V_BetcoinsComp__c = 0;
		insert lProximoReward;

		insert new VN_ParticipanteComPerfilCompativel__c(V_Member__c = lMember.Id,
														V_Reward__c = lReward.Id);

		insert new VN_ParticipanteComPerfilCompativel__c(V_Member__c = lMember.Id,
														V_Reward__c = lProximoReward.Id);												
		

 		
 		lReward1 = SX_YoubetBetsContoller.getReward(lMember.Id,'youbet-extra');

 		//System.assertNotEquals(lReward1, null);

 		lReward1 = null;
 		System.runAs(lUser) {
 			lReward1 = SX_YoubetBetsContoller.proximoLance('youbet-extra',lReward.Id);
 			//System.assertNotEquals(lReward1, null);
 		
 		String lReposta = SX_YoubetBetsContoller.efetuarLance(lMember.Id, lReward.Id, 10);
 		System.assertEquals(Label.V_MsgLanceSucesso, lReposta);

		SX_YoubetBetsContoller.sumAccess(String.valueOf(lReward.Id), String.valueOf(lMember.Id));
		SX_YoubetBetsContoller.proximosPremios('youbet', lReward.Id);
		}

 		Test.stopTest();
	}
}