force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Member&apos;s points.</description>
    <inlineHelpText>Member&apos;s points.</inlineHelpText>
    <label>Points</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program that the Member belongs to.</description>
    <inlineHelpText>The Program that the Member belongs to</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</description>
    <inlineHelpText>Choose Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Saldo de betcoins (extras) do participante.Saldo de pontos gerado pela iniciativa Youbet Complementar.</description>
    <inlineHelpText>Saldo de betcoins (extras) do participante.Saldo de pontos gerado pela iniciativa Youbet Complementar.</inlineHelpText>
    <label>Betcoins - Extra</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_MetasAnoFiscalVigenteNovo__c.field-meta.xml
<CustomField>
    <fullName>V_MetasAnoFiscalVigenteNovo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Exibe a identificação do ano fiscal vigente do participante.</description>
    <inlineHelpText>Exibe a identificação do ano fiscal vigente do participante.</inlineHelpText>
    <label>Metas do Ano Fiscal Vigente</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipLabel>Participantes</relationshipLabel>
    <relationshipName>Participantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/FieloPLT__Redemption__c.object-meta.xml
<CustomObject>
    <description>Redemptions are the orders generated by Members when they redeem their available Points for Rewards. Redemptions may include as many &quot;Redemptions Items&quot; as Rewards redeemed, as each Redemption Item represents a particular redeemed Reward.</description>
    <label>Redemption</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/FieloPLT__Member__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member who performed the Redemption.</description>
    <inlineHelpText>Choose the Member for this Redemption.</inlineHelpText>
    <label>Member</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Redemptions</relationshipLabel>
    <relationshipName>Redemptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Points needed to redeem the Reward.</description>
    <inlineHelpText>Points needed to redeem the Reward.</inlineHelpText>
    <label>Points</label>
    <summarizedField>FieloPLT__RedemptionItem__c.FieloPLT__Points__c</summarizedField>
    <summaryFilterItems>
        <field>FieloPLT__RedemptionItem__c.FieloPLT__Status__c</field>
        <operation>notEqual</operation>
        <value>Reverted</value>
    </summaryFilterItems>
    <summaryForeignKey>FieloPLT__RedemptionItem__c.FieloPLT__Redemption__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <formula>CASESAFEID( FieloPLT__Member__r.FieloPLT__Program__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Redemption statuses. The available options are: Open, Closed, Pending and Rejected.</description>
    <inlineHelpText>Choose the Redemption status (Open, Closed, Pending or Rejected).</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Desqualificado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <description>Saldo de pontos gerado pela iniciativa Youbet Extra. Quando a iniciativa for criada, necessário renomear o rótulo do campo para &quot;Betcoins - Nome do Leilão&quot;.</description>
    <inlineHelpText>Saldo de pontos gerado pela iniciativa Youbet Extra. Quando a iniciativa for criada, necessário renomear o rótulo do campo para &quot;Betcoins - Nome do Leilão&quot;.</inlineHelpText>
    <label>Betcoins - Extra</label>
    <summarizedField>FieloPLT__RedemptionItem__c.V_BetcoinsComp__c</summarizedField>
    <summaryFilterItems>
        <field>FieloPLT__RedemptionItem__c.FieloPLT__Status__c</field>
        <operation>notEqual</operation>
        <value>Reverted</value>
    </summaryFilterItems>
    <summaryForeignKey>FieloPLT__RedemptionItem__c.FieloPLT__Redemption__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/FieloPLT__RedemptionItem__c.object-meta.xml
<CustomObject>
    <description>Redemption Items represent each item which is part of a Redemption order.</description>
    <label>Redemption Item</label>
    <nameField>
        <displayFormat>RI-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemption Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Points needed to redeem the Redemption item</description>
    <inlineHelpText>Points needed to redeem the Redemption item.</inlineHelpText>
    <label>Points</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Redemption__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Redemption__c</fullName>
    <description>The Redemption order that the Member has made.</description>
    <inlineHelpText>The Redemption order that the Member has made.</inlineHelpText>
    <label>Redemption</label>
    <referenceTo>FieloPLT__Redemption__c</referenceTo>
    <relationshipLabel>Redemption Items</relationshipLabel>
    <relationshipName>RedemptionItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Reward__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Reward that the Member has redeemed.</description>
    <inlineHelpText>The Reward that the Member has redeemed.</inlineHelpText>
    <label>Reward</label>
    <referenceTo>FieloPLT__Reward__c</referenceTo>
    <relationshipLabel>Redemption Items</relationshipLabel>
    <relationshipName>RedemptionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Where a Redemption Item is in the order process: Delivered, Open, Expired, Ready, Reverted or Pending</description>
    <inlineHelpText>Where this item is in the order process.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Reverted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <description>Saldo de pontos gerado pela iniciativa Youbet Extra. Quando a iniciativa for criada, necessário renomear o rótulo do campo para &quot;Betcoins - Nome do Leilão&quot;.</description>
    <inlineHelpText>Saldo de pontos gerado pela iniciativa Youbet Extra. Quando a iniciativa for criada, necessário renomear o rótulo do campo para &quot;Betcoins - Nome do Leilão&quot;.</inlineHelpText>
    <label>Betcoins - Extra</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/FieloPLT__Reward__c.object-meta.xml
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Reward__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Number of Points needed to redeem a Reward.</description>
    <inlineHelpText>Enter the number of Points needed to redeem this Reward.</inlineHelpText>
    <label>Points</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Program that the Reward is associated with.</description>
    <inlineHelpText>The Program in which you&apos;ll use this Reward</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <description>Preencha com valor igual a 1 para Youbet Extra. E com 0 (zero) quando for Youbet Perene.</description>
    <inlineHelpText>Preencha com valor igual a 1 para Youbet Extra. E com 0 (zero) quando for Youbet Perene</inlineHelpText>
    <label>Betcoins - Extra</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_LancesLeiloes__c.field-meta.xml
<CustomField>
    <fullName>V_LancesLeiloes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lances Leilões</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_LeiloesGanhos__c.field-meta.xml
<CustomField>
    <fullName>V_LeiloesGanhos__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Leilões Ganhos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SX_Redemption_AfterTest.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                date: 04/02/2019
*
* 
* Name: SX_Redemption_AfterTest.cls
* 
* Classe de testes para da SX_Redemption_After.cls
*******************************************************************************/

@isTest
public with sharing class SX_Redemption_AfterTest {

	final private static String TEST_UPDATE = 'update';
	final private static String TEST_DELETE = 'delete';

	private static VN_MetaParticipante__c lMeta;
	private static VN_MetaParticipante__c lMeta2;

	static testMethod void testInsert(){

		loadDados(null);

		Map<Id, VN_MetaParticipante__c> lMapMetaResult = new Map<Id, VN_MetaParticipante__c>([SELECT Id, 
        	V_LancesLeiloes__c, V_LeiloesGanhos__c FROM VN_MetaParticipante__c]);

        System.assertEquals(2, lMapMetaResult.get(lMeta.Id).V_LancesLeiloes__c); 
        System.assertEquals(0, lMapMetaResult.get(lMeta2.Id).V_LancesLeiloes__c); 

        //lance ganhador
        System.assertEquals(0, lMapMetaResult.get(lMeta.Id).V_LeiloesGanhos__c); 
        System.assertEquals(0, lMapMetaResult.get(lMeta2.Id).V_LeiloesGanhos__c); 
	}

	static testMethod void testUpdate(){

		loadDados(TEST_UPDATE);

        Map<Id, VN_MetaParticipante__c> lMapMetaResult = new Map<Id, VN_MetaParticipante__c>([SELECT Id, 
        	V_LancesLeiloes__c, V_LeiloesGanhos__c FROM VN_MetaParticipante__c]);

        System.assertEquals(1, lMapMetaResult.get(lMeta.Id).V_LancesLeiloes__c); 
        System.assertEquals(1, lMapMetaResult.get(lMeta2.Id).V_LancesLeiloes__c); 

        //lance ganhador
        System.assertEquals(0, lMapMetaResult.get(lMeta.Id).V_LeiloesGanhos__c); 
        System.assertEquals(1, lMapMetaResult.get(lMeta2.Id).V_LeiloesGanhos__c); 
	}

	static testMethod void testDelete(){

		loadDados(TEST_DELETE);

        Map<Id, VN_MetaParticipante__c> lMapMetaResult = new Map<Id, VN_MetaParticipante__c>([SELECT Id, 
        	V_LancesLeiloes__c, V_LeiloesGanhos__c FROM VN_MetaParticipante__c]);

        System.assertEquals(0, lMapMetaResult.get(lMeta.Id).V_LancesLeiloes__c); 
        System.assertEquals(0, lMapMetaResult.get(lMeta2.Id).V_LancesLeiloes__c); 

        //lance ganhador
        System.assertEquals(0, lMapMetaResult.get(lMeta.Id).V_LeiloesGanhos__c); 
        System.assertEquals(0, lMapMetaResult.get(lMeta2.Id).V_LeiloesGanhos__c); 
	}

	private static void loadDados(String aType){

		FieloPLT__Program__c lProg = SObjectForTest.getProgram('Test');
		insert lProg;

		FieloPLT__Member__c lMember = SObjectForTest.getMember(lProg.Id);
		lMember.FieloPLT__Points__c = 1000000;
		FieloPLT.SobjectService.enableAdminPermission(true);
        insert lMember;
        FieloPLT.SObjectService.enableAdminPermission(false);

		VN_GerenciadorMetaParticipanteAF__c lGerenciador = SObjectForTest.getGerenciadorMetaParticipante();
 		insert lGerenciador;

 		lMeta = SObjectForTest.getMetasNovaEstrutura(lMember.Id, lGerenciador.Id, 'FY19');
 		insert lMeta;

 		lMeta2 = SObjectForTest.getMetasNovaEstrutura(lMember.Id, lGerenciador.Id, 'FY20');
 		insert lMeta2;

 		lMember.V_MetasAnoFiscalVigenteNovo__c = lMeta.Id;
 		update lMember;

		List<FieloPLT__Reward__c> lLstReward = new List<FieloPLT__Reward__c>();
		FieloPLT__Reward__c lRewPerene = SObjectForTest.getReward(lProg.Id, Label.V_RecTypeLeiloes, 'Youbet Perene'); 
		lRewPerene.FieloPLT__Points__c = 1;
		lRewPerene.V_BetcoinsComp__c = 0;
		lLstReward.add(lRewPerene);

		insert lLstReward;

		String lOpen = 'Open';

		List<FieloPLT__Redemption__c> lLstRedemption = new List<FieloPLT__Redemption__c>();
		FieloPLT__Redemption__c lRedmp =  SObjectForTest.getRedemption(lMember.Id);
		lRedmp.FieloPLT__Status__c = lOpen;
		lRedmp.V_MetaParticipante__c = lMeta.Id;
		lLstRedemption.add(lRedmp);
		FieloPLT__Redemption__c lRedemp2 = SObjectForTest.getRedemption(lMember.Id);
		lRedemp2.FieloPLT__Status__c = lOpen;
		lRedemp2.V_MetaParticipante__c = lMeta.Id;
		lLstRedemption.add(lRedemp2);
		insert lLstRedemption;

		List<FieloPLT__RedemptionItem__c> lLstRdi = new List<FieloPLT__RedemptionItem__c>();
		FieloPLT__RedemptionItem__c lRdiPerene =  SObjectForTest.getRedemptionItem(lRewPerene.Id, lRedmp.Id);
		lRdiPerene.FieloPLT__Points__c = 10;
		lLstRdi.add(lRdiPerene);
		FieloPLT__RedemptionItem__c lRdiPerene2 =  SObjectForTest.getRedemptionItem(lRewPerene.Id, lRedemp2.Id);
		lRdiPerene2.FieloPLT__Points__c = 10;
		lLstRdi.add(lRdiPerene2);

		insert lLstRdi;

		Test.startTest();

			lRedmp.FieloPLT__Status__c = SX_Redemption_After.CLOSED; 
			lRedemp2.FieloPLT__Status__c = SX_Redemption_After.CLOSED;

		    update lLstRedemption;

			if(aType == TEST_UPDATE){
				FieloPLT.SobjectService.enableAdminPermission(true);
		        lRedemp2.V_MetaParticipante__c = lMeta2.Id;
		        lRedemp2.V_LanceGanhador__c = true;
		        update lRedemp2;
			}

			if(aType == TEST_DELETE){
				delete lLstRedemption; 
			}
                
        Test.stopTest();
	}
}