force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/FieloPLT__Reward__c.object-meta.xml
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Reward__c/fields/Iniciativa__c.field-meta.xml
<CustomField>
    <fullName>Iniciativa__c</fullName>
    <description>Tipos de iniciativa do incentivo.</description>
    <inlineHelpText>Tipos de iniciativa do incentivo.</inlineHelpText>
    <label>Iniciativa</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Youbet Perene</fullName>
            </value>
            <value>
                <fullName>Youbet Extra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_DataFimTexto__c.field-meta.xml
<CustomField>
    <fullName>V_DataFimTexto__c</fullName>
    <formula>TEXT(DAY( DATEVALUE( V_DataHoraFimYoubet__c ) ))+&apos;/&apos;+ TEXT(MONTH(DATEVALUE(V_DataHoraFimYoubet__c )))+&apos;/&apos; + TEXT(YEAR(DATEVALUE(V_DataHoraFimYoubet__c )))</formula>
    <label>Data Fim Texto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_DatafinalYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_DatafinalYoubet__c</fullName>
    <description>Data final do Youbet para ser utilizado em filtros do site.</description>
    <formula>DATEVALUE( V_DataHoraFimYoubet__c )</formula>
    <inlineHelpText>Data final do Youbet para ser utilizado em filtros do site.</inlineHelpText>
    <label>Data final Youbet</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_DataHoraFimYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_DataHoraFimYoubet__c</fullName>
    <description>Data e hora para finalizar a vigência do youbet.</description>
    <inlineHelpText>Data e hora para finalizar a vigência do youbet.</inlineHelpText>
    <label>Data/Hora Fim do Youbet</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_DataInicioTexto__c.field-meta.xml
<CustomField>
    <fullName>V_DataInicioTexto__c</fullName>
    <formula>TEXT(DAY( DATEVALUE(V_DataHoraInicioYoubet__c) ))+&apos;/&apos;+ TEXT(MONTH(DATEVALUE(V_DataHoraInicioYoubet__c)))+&apos;/&apos; + TEXT(YEAR(DATEVALUE(V_DataHoraInicioYoubet__c)))</formula>
    <label>Data Inicio Texto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_DataInicioYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_DataInicioYoubet__c</fullName>
    <description>Data de início do Youbet para ser utilizado em filtros do site.</description>
    <formula>DateValue(V_DataHoraInicioYoubet__c)</formula>
    <inlineHelpText>Data de início do Youbet para ser utilizado em filtros do site.</inlineHelpText>
    <label>Data de Início Youbet</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_IsActive__c.field-meta.xml
<CustomField>
    <fullName>V_IsActive__c</fullName>
    <formula>AND(V_YoubetCompleto__c,
				RecordType.Name = &apos;Leilões&apos;,
				OR (ISBLANK(V_DataHoraInicioYoubet__c),
								V_DataHoraInicioYoubet__c &lt;= NOW()),
				V_DataHoraFimYoubet__c &gt;= NOW())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_NomeVencedor__c.field-meta.xml
<CustomField>
    <fullName>V_NomeVencedor__c</fullName>
    <label>Nome do Vencedor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_RegulamentoYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_RegulamentoYoubet__c</fullName>
    <description>Utilizado para a inclusão do texto de regulamento do Youbet Perene ou Complementar.</description>
    <inlineHelpText>Utilizado para a inclusão do texto de regulamento do Youbet Perene ou Complementar.</inlineHelpText>
    <label>Regulamento Youbet</label>
    <length>100768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_ValorLanceGanhador__c.field-meta.xml
<CustomField>
    <fullName>V_ValorLanceGanhador__c</fullName>
    <description>Valor de betcoins do lance ganhador. Atualizado por process builder.</description>
    <inlineHelpText>Valor de betcoins do lance ganhador.</inlineHelpText>
    <label>Valor do Lance Ganhador</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_YoubetCompleto__c.field-meta.xml
<CustomField>
    <fullName>V_YoubetCompleto__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se assinalado, indica que o cadastro do Youbet foi concluído e que a aplicação poderá relacionar os participantes que cumprirem os critérios desse Youbet para efeito de histórico e análises.</description>
    <inlineHelpText>Se assinalado, indica que o cadastro do Youbet foi concluído e que a aplicação poderá relacionar os participantes que cumprirem os critérios desse Youbet para efeito de histórico e análises.</inlineHelpText>
    <label>Youbet Completo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_YoubetProcessado__c.field-meta.xml
<CustomField>
    <fullName>V_YoubetProcessado__c</fullName>
    <description>Campo atualizado com data e hora após processamento do batch para indicar o lance vencedor após a vigência do Youbet. Se assinalado, indica que o Youbet encerrado já teve a indicação do lance ganhador.</description>
    <inlineHelpText>Campo atualizado com data e hora após processamento do batch para indicar o lance vencedor após a vigência do Youbet. Se assinalado, indica que o Youbet encerrado já teve a indicação do lance ganhador.</inlineHelpText>
    <label>Youbet Processado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/VN_ParticipanteComPerfilCompativel__c.object-meta.xml
<CustomObject>
    <description>Lista relacionada do Youbet, participantes que possuem compatibilidade de cargo, área, liderança e elegibilidade no momento da criação do Youbet.</description>
    <label>Participante Com Perfil Compatível</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>No. Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes Com Perfis Compatíveis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Member__c.field-meta.xml
<CustomField>
    <fullName>V_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Participante relacionado ao youbet de compatibilidade.</description>
    <inlineHelpText>Participante relacionado ao youbet de compatibilidade.</inlineHelpText>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Youbets Compatíveis</relationshipLabel>
    <relationshipName>V_RewardsCompativeis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Reward__c.field-meta.xml
<CustomField>
    <fullName>V_Reward__c</fullName>
    <description>Youbet relacionado ao participante com compatibilidade de critérios (Cargo, Área, Liderança e Elegibilidade).</description>
    <inlineHelpText>Youbet relacionado ao participante com compatibilidade de critérios (Cargo, Área, Liderança e Elegibilidade).</inlineHelpText>
    <label>Youbet</label>
    <referenceTo>FieloPLT__Reward__c</referenceTo>
    <relationshipLabel>Participantes Com Perfis Compatíveis</relationshipLabel>
    <relationshipName>ParticipantesPerfiCompativeis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_ValorLanceGanhador__c.field-meta.xml
<CustomField>
    <fullName>V_ValorLanceGanhador__c</fullName>
    <description>Indica o valor do lance ganhador do Youbet.</description>
    <formula>V_Reward__r.V_ValorLanceGanhador__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indica o valor do lance ganhador do Youbet.</inlineHelpText>
    <label>Valor do Lance Ganhador</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_YoubetProcessado__c.field-meta.xml
<CustomField>
    <fullName>V_YoubetProcessado__c</fullName>
    <formula>V_Reward__r.V_YoubetProcessado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Youbet Processado</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SX_YoubetsPerfomedController.cls
public with sharing class SX_YoubetsPerfomedController {

	@AuraEnabled
    public static FieloPLT__Member__c getMember() {
        List<FieloPLT__Member__c> lMemberLst = [SELECT Id
								                FROM FieloPLT__Member__c
								                WHERE FieloPLT__User__c =: UserInfo.getUserId()];
	    return lMemberLst.isEmpty() ? null : lMemberLst[0];         
    }

   	@AuraEnabled
    public static FieloPLT__Reward__c getAgreement(String aIdReward) {
        List<FieloPLT__Reward__c> lRewardLst = [SELECT Name, V_RegulamentoYoubet__c
								                FROM FieloPLT__Reward__c
								                WHERE Id =: aIdReward];
	    return !lRewardLst.isEmpty() ? lRewardLst[0] : null;         
    }

	@AuraEnabled
    public static List<FieloPLT__Reward__c> getYoubets(String aDe, String aAte, String aPalavraChave, String aTipo, String aIdMember){

    	String lIniciativa = aTipo == 'youbet' ? Label.V_IniciativaPerene 
        						: aTipo == 'youbet-extra' ? Label.V_IniciativaComplementar
        						: Label.V_IniciativaElite;

        Set<Id> lSetReward = idsRewardsCompativeis();

    	String lQuery = 'SELECT Id, Name, V_RegulamentoYoubet__c, V_DataInicioTexto__c, V_DataFimTexto__c, V_NomeVencedor__c, V_ValorLanceGanhador__c' +
					 	' FROM FieloPLT__Reward__c' +
					 	' WHERE Id IN :lSetReward' +
					 	' AND RecordTypeId = \'' + VN_RecType.getID('FieloPLT__Reward__c', Label.V_RecTypeLeiloes) + '\''+
					 	' AND V_YoubetCompleto__c = true '+
					 	' AND V_YoubetProcessado__c != null'+
					 	' AND V_DataHoraFimYoubet__c <= TODAY'+ 
					 	' AND V_IsActive__c = false'+ 
					 	' AND Iniciativa__c = \''+ lIniciativa + '\'';

		if(String.isNotEmpty(aPalavraChave)){
			lQuery += ' AND (Name like \'%' + aPalavraChave + '%\'';
			lQuery += ' OR V_NomeVencedor__c like \'%' + aPalavraChave + '%\')';
		}

		if(aDe != null){
			Date lDe = date.valueOf(aDe);
			lQuery += ' AND V_DataInicioYoubet__c >= :lDe';
		}
		if(aAte != null){
			Date lAte = date.valueOf(aAte);
			lQuery += ' AND V_DatafinalYoubet__c <= :lAte';
		}

		lQuery +=' ORDER BY V_DataHoraFimYoubet__c';

		system.debug('### '+lQuery);

		List<FieloPLT__Reward__c> lLstRewards = database.query(lQuery);
		return lLstRewards;
	}

	private static Set<Id> idsRewardsCompativeis(){

        Set<Id> lSetReward = new Set<Id>();
        for(VN_ParticipanteComPerfilCompativel__c perfilCompativel: [SELECT V_Reward__c 
                                                                     FROM VN_ParticipanteComPerfilCompativel__c
                                                                    WHERE V_Member__r.FieloPLT__User__c =: UserInfo.getUserId()]){
            if(perfilCompativel.V_Reward__c != null)
                lSetReward.add(perfilCompativel.V_Reward__c);
        }
        return lSetReward;
    }
}