force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_DataSumarizador__c.field-meta.xml
<CustomField>
    <fullName>V_DataSumarizador__c</fullName>
    <description>Campo utilizado para mostrar a partir de qual data deve-se criar o sumarizador do participante.</description>
    <label>Data Sumarizador</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_MetasAnoFiscalVigenteNovo__c.field-meta.xml
<CustomField>
    <fullName>V_MetasAnoFiscalVigenteNovo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Exibe a identificação do ano fiscal vigente do participante.</description>
    <inlineHelpText>Exibe a identificação do ano fiscal vigente do participante.</inlineHelpText>
    <label>Metas do Ano Fiscal Vigente</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipLabel>Participantes</relationshipLabel>
    <relationshipName>Participantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/VN_GerenciadorMetaParticipanteAF__c.object-meta.xml
<CustomObject>
    <description>Gerenciador dos registros de metas dos participantes por Ano Fiscal.</description>
    <label>Gerenciador Meta Participante AF</label>
    <nameField>
        <displayFormat>GMAF-{000000}</displayFormat>
        <label>No. Gerenciador Ano Fiscal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gerenciador Metas Participantes AF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <description>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</description>
    <inlineHelpText>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</inlineHelpText>
    <label>Ano Fiscal</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_DataFim__c.field-meta.xml
<CustomField>
    <fullName>V_DataFim__c</fullName>
    <description>Data final do ano fiscal.</description>
    <inlineHelpText>Data final do ano fiscal.</inlineHelpText>
    <label>Data Fim</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_DataInicio__c.field-meta.xml
<CustomField>
    <fullName>V_DataInicio__c</fullName>
    <description>Data de início do ano fiscal.</description>
    <inlineHelpText>Data de início do ano fiscal.</inlineHelpText>
    <label>Data Início</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sinaliza se o gerenciador é o que está em vigência.</description>
    <inlineHelpText>Sinaliza se o gerenciador é o que está em vigência.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ano fiscal da Meta do participante do participante</description>
    <label>Gerenciador Meta Participante AF</label>
    <referenceTo>VN_GerenciadorMetaParticipanteAF__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Participante__c.field-meta.xml
<CustomField>
    <fullName>V_Participante__c</fullName>
    <description>Participante relacionado à meta.</description>
    <inlineHelpText>Participante relacionado à meta.</inlineHelpText>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <description>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</description>
    <formula>V_AnoFiscal__r.V_Vigente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/VN_Sumarizador__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por sumarizar as metas, resultados e ponderados das informações carregas ou atualizadas.</description>
    <label>Sumarizador</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Código do Sumarizador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sumarizadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_Sumarizador__c/fields/Participante__c.field-meta.xml
<CustomField>
    <fullName>Participante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relacionamento entre o participante e o sumarizador para poder gerar a pontuação</description>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Sumarizadores</relationshipLabel>
    <relationshipName>Sumarizadores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Mes__c.field-meta.xml
<CustomField>
    <fullName>V_Mes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Faz referência ao mês corrente da meta</description>
    <label>Mês Meta</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_MetaDoParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_MetaDoParticipante__c</fullName>
    <description>Meta dos participantes</description>
    <label>Meta do Participante</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipName>VN_SumarizadoresDosObjetivos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SX_BatchCriarMetas.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 14/09/2018
* 
* Name: SX_BatchCriarMetas.cls
* 
* Batch para criar e metas nos Members
*******************************************************************************/
global class SX_BatchCriarMetas implements Database.Batchable<sObject>, Database.Stateful {
    
    global Map<Id, VN_GerenciadorMetaParticipanteAF__c>  fMapGerenciador; 
    
    global SX_BatchCriarMetas(Map<Id, VN_GerenciadorMetaParticipanteAF__c>  aMapGerenciador) {

        if(SX_Utils.batchIsProcessing('SX_BatchCriarMetas')) return;
        fMapGerenciador = aMapGerenciador;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        return Database.getQueryLocator([SELECT Id, V_MetasAnoFiscalVigenteNovo__c FROM FieloPLT__Member__c]);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        System.debug('>>> SX_BatchCriarMetas.execute()');
        System.debug(scope);
        if ( scope == null || scope.isEmpty()) return; 

        List<FieloPLT__Member__c> lListMember = ( List<FieloPLT__Member__c> ) scope;

        Set<Id> lSetMeta = new Set<Id>();
        for(VN_MetaParticipante__c meta: [SELECT V_Participante__c 
	                                        FROM VN_MetaParticipante__c 
	                                        WHERE V_AnoFiscal__c =: fMapGerenciador.keySet()
	                                        AND V_Participante__c =: lListMember]){
            lSetMeta.add(meta.V_Participante__c);
        }

        List<VN_MetaParticipante__c> lLstMeta = new List<VN_MetaParticipante__c>();
        for(FieloPLT__Member__c member: lListMember){

        	if(lSetMeta.contains(member.Id)) continue;

        	for(VN_GerenciadorMetaParticipanteAF__c lGerenciador: fMapGerenciador.values()){

        		 lLstMeta.add(new VN_MetaParticipante__c(
						Name = lGerenciador.V_AnoFiscal__c,
						V_AnoFiscal__c  = lGerenciador.Id,
						V_Participante__c = member.Id
					)
				);
        	}
        }

        if(!lLstMeta.isEmpty()) {

            Database.SaveResult[] lLstResult = Database.insert(lLstMeta, false);
            for(integer i=0; i < lLstResult.size(); i++) {
            
                Database.SaveResult lResult = lLstResult[i];
                VN_MetaParticipante__c lMeta = lLstMeta[i];      
                if(lMeta == null) continue;
                
                if (!lResult.isSuccess()){
                     system.debug('### SX_BatchCriarMetas error insert metas '+' { ' + lMeta.V_Participante__c +' }: ');

                    for(Database.Error err : lResult.getErrors()) {
                        system.debug(err.getMessage());
                    }
                }
            }
            associarMetaNoMember(lLstMeta); 
            gerarSumarizador(lLstMeta, null);
        }          
    }
    
    global void finish(Database.BatchableContext BC) {
    }

    public static void associarMetaNoMember(List<VN_MetaParticipante__c> aLstMeta){

        Map<Id,VN_MetaParticipante__c> lMapMemberMetas = new Map<Id,VN_MetaParticipante__c>();
        for(VN_MetaParticipante__c meta: [SELECT Id, V_Participante__c FROM VN_MetaParticipante__c 
        									 WHERE Id =: aLstMeta
        									 AND V_Vigente__c = true]){
            lMapMemberMetas.put(Meta.V_Participante__c, meta);
        }

        List<FieloPLT__Member__c> lLstMember = [SELECT Id, V_MetasAnoFiscalVigenteNovo__c FROM FieloPLT__Member__c WHERE Id =: lMapMemberMetas.keySet()];
        for(FieloPLT__Member__c member: lLstMember){

            VN_MetaParticipante__c lMeta = lMapMemberMetas.get(member.Id);
            if(lMeta == null) continue;

            member.V_MetasAnoFiscalVigenteNovo__c = lMeta.Id;
        }

        if(!lLstMember.isEmpty()) {

            Database.SaveResult[] lLstResult = Database.update(lLstMember, false);
            for(integer i=0; i < lLstResult.size(); i++) {
            
                Database.SaveResult lResult = lLstResult[i];
                FieloPLT__Member__c lMember = lLstMember[i];      
                if(lMember == null) continue;
                
                if (!lResult.isSuccess()){
                     system.debug('### SX_BatchCriarMetas erro update member'+' { ' + lMember.Id +' }: ');

                    for(Database.Error err : lResult.getErrors()) {
                        system.debug(err.getMessage());
                    }
                }
            }
        } 
    }

    public static void gerarSumarizador(List<VN_MetaParticipante__c> aLstMeta, Date data){
        List<VN_Sumarizador__c> lLstSumarizador  = new List<VN_Sumarizador__c>();

        Set<Id> lSetSumarizador = new Set<Id>();
        for(VN_Sumarizador__c sumarizador: [SELECT Participante__c  
	                                   FROM VN_Sumarizador__c 
	                                  WHERE V_MetaDoParticipante__c =: aLstMeta]){
            lSetSumarizador.add(sumarizador.Participante__c);
        }
            
        for(VN_MetaParticipante__c meta: [SELECT Id, V_Participante__c, V_AnoFiscal__r.V_DataInicio__c, V_AnoFiscal__r.V_DataFim__c,
                                                V_Participante__r.V_DataSumarizador__c 
                                                FROM VN_MetaParticipante__c 
                                                WHERE Id =: aLstMeta
                                                AND V_Vigente__c = true]){
            
            // task #17414
            // Date dataIni = data == null ? meta.V_AnoFiscal__r.V_DataInicio__c : data;
            Date dataIni = data == null ? System.now().date() : data;
            if(meta.V_Participante__c != null && meta.V_Participante__r.V_DataSumarizador__c != null){
                dataIni = meta.V_Participante__r.V_DataSumarizador__c;
            }
            Integer month = dataIni.monthsBetween(meta.V_AnoFiscal__r.V_DataFim__c) + 1;

            if(lSetSumarizador.contains(meta.V_Participante__c)) continue;

            for(Integer i = 1; i <= month; i++){
                VN_Sumarizador__c lSumarizador  = new VN_Sumarizador__c();
                lSumarizador.V_MetaDoParticipante__c = meta.Id;
                lSumarizador.Participante__c = meta.V_Participante__c;
                //lSumarizador.V_Mes__c = dataIni.month();
                lSumarizador.V_Mes__c = VN_CargaDadosTempHandler.getMesMeta(meta.V_AnoFiscal__r, dataIni);

                lLstSumarizador.add(lSumarizador);
                dataIni = dataIni.addMonths(1);
            }
        }
        
        if (!lLstSumarizador.isEmpty()){
            system.debug('Sumarizador: ' + lLstSumarizador);
            Database.SaveResult[] lLstResult = Database.insert(lLstSumarizador, false);
            for(integer i=0; i < lLstResult.size(); i++) {
                    
                Database.SaveResult lResult = lLstResult[i];
                VN_Sumarizador__c lSumarizador = lLstSumarizador[i];      
                if(lSumarizador == null) continue;
                        
                if (!lResult.isSuccess()){
                    system.debug('### SX_BatchCriarMetas error insert sumarizador '+' { ' + lSumarizador.Participante__c +' }: ');

                    for(Database.Error err : lResult.getErrors()) {
                        system.debug(err.getMessage());
                    }
                }
            }
        }
    }
}