force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Member&apos;s points.</description>
    <inlineHelpText>Member&apos;s points.</inlineHelpText>
    <label>Points</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Status__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Status__c</fullName>
    <description>Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</description>
    <inlineHelpText>Choose Member&apos;s status: Active, Blocked, Pending or Submitted for Approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Area__c.field-meta.xml
<CustomField>
    <fullName>V_Area__c</fullName>
    <description>Área do participante.</description>
    <inlineHelpText>Área do participante.</inlineHelpText>
    <label>Área</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VERTICAIS</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Saldo de betcoins (extras) do participante.Saldo de pontos gerado pela iniciativa Youbet Complementar.</description>
    <inlineHelpText>Saldo de betcoins (extras) do participante.Saldo de pontos gerado pela iniciativa Youbet Complementar.</inlineHelpText>
    <label>Betcoins - Extra</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo atual do participante.</description>
    <inlineHelpText>Cargo atual do participante.</inlineHelpText>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COORDENADOR | GERENTE REGIONAL VIP</fullName>
            </value>
            <value>
                <fullName>DIRETOR</fullName>
            </value>
            <value>
                <fullName>GERENTE DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDER</fullName>
            </value>
            <value>
                <fullName>COORDENADOR II</fullName>
                <isActive>false</isActive>
                <label>COORDENADOR II</label>
            </value>
            <value>
                <fullName>GERENTE DE VENDAS</fullName>
                <isActive>false</isActive>
                <label>GERENTE DE VENDAS</label>
            </value>
            <value>
                <fullName>VICE-PRESIDENTE</fullName>
                <isActive>false</isActive>
                <label>VICE-PRESIDENTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Lideranca__c.field-meta.xml
<CustomField>
    <fullName>V_Lideranca__c</fullName>
    <description>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</description>
    <inlineHelpText>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</inlineHelpText>
    <label>Liderança</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>MULTI SECTOR</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
            <value>
                <fullName>VAREJO, CPG E PAGAMENTOS</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS</fullName>
            </value>
            <value>
                <fullName>SERASA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_PapelYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_PapelYoubet__c</fullName>
    <label>Papel Youbet</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GERENTES DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDERES</fullName>
            </value>
            <value>
                <fullName>LÍDERES (COORDENADORES) E GERENTE REGIONAIS</fullName>
            </value>
            <value>
                <fullName>NÃO ELEGÍVEL</fullName>
                <default>true</default>
                <label>NÃO ELEGÍVEL</label>
            </value>
            <value>
                <fullName>DIRETORES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/FieloPLT__Reward__c.object-meta.xml
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Reward__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Number of Points needed to redeem a Reward.</description>
    <inlineHelpText>Enter the number of Points needed to redeem this Reward.</inlineHelpText>
    <label>Points</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/Iniciativa__c.field-meta.xml
<CustomField>
    <fullName>Iniciativa__c</fullName>
    <description>Tipos de iniciativa do incentivo.</description>
    <inlineHelpText>Tipos de iniciativa do incentivo.</inlineHelpText>
    <label>Iniciativa</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Youbet Perene</fullName>
            </value>
            <value>
                <fullName>Youbet Extra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <description>Preencha com valor igual a 1 para Youbet Extra. E com 0 (zero) quando for Youbet Perene.</description>
    <inlineHelpText>Preencha com valor igual a 1 para Youbet Extra. E com 0 (zero) quando for Youbet Perene</inlineHelpText>
    <label>Betcoins - Extra</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_DataInicioYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_DataInicioYoubet__c</fullName>
    <description>Data de início do Youbet para ser utilizado em filtros do site.</description>
    <formula>DateValue(V_DataHoraInicioYoubet__c)</formula>
    <inlineHelpText>Data de início do Youbet para ser utilizado em filtros do site.</inlineHelpText>
    <label>Data de Início Youbet</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_PapelYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_PapelYoubet__c</fullName>
    <label>Papel Youbet</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GERENTES DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDERES</fullName>
            </value>
            <value>
                <fullName>LÍDERES (COORDENADORES) E GERENTE REGIONAIS</fullName>
            </value>
            <value>
                <fullName>NÃO ELEGÍVEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_YoubetCompleto__c.field-meta.xml
<CustomField>
    <fullName>V_YoubetCompleto__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se assinalado, indica que o cadastro do Youbet foi concluído e que a aplicação poderá relacionar os participantes que cumprirem os critérios desse Youbet para efeito de histórico e análises.</description>
    <inlineHelpText>Se assinalado, indica que o cadastro do Youbet foi concluído e que a aplicação poderá relacionar os participantes que cumprirem os critérios desse Youbet para efeito de histórico e análises.</inlineHelpText>
    <label>Youbet Completo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/VN_ParticipanteComPerfilCompativel__c.object-meta.xml
<CustomObject>
    <description>Lista relacionada do Youbet, participantes que possuem compatibilidade de cargo, área, liderança e elegibilidade no momento da criação do Youbet.</description>
    <label>Participante Com Perfil Compatível</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>No. Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes Com Perfis Compatíveis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Area__c.field-meta.xml
<CustomField>
    <fullName>V_Area__c</fullName>
    <description>Área do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Área do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Área</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Cargo do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Cargo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Lideranca__c.field-meta.xml
<CustomField>
    <fullName>V_Lideranca__c</fullName>
    <description>Liderança do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Liderança do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Liderança</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Member__c.field-meta.xml
<CustomField>
    <fullName>V_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Participante relacionado ao youbet de compatibilidade.</description>
    <inlineHelpText>Participante relacionado ao youbet de compatibilidade.</inlineHelpText>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Youbets Compatíveis</relationshipLabel>
    <relationshipName>V_RewardsCompativeis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Reward__c.field-meta.xml
<CustomField>
    <fullName>V_Reward__c</fullName>
    <description>Youbet relacionado ao participante com compatibilidade de critérios (Cargo, Área, Liderança e Elegibilidade).</description>
    <inlineHelpText>Youbet relacionado ao participante com compatibilidade de critérios (Cargo, Área, Liderança e Elegibilidade).</inlineHelpText>
    <label>Youbet</label>
    <referenceTo>FieloPLT__Reward__c</referenceTo>
    <relationshipLabel>Participantes Com Perfis Compatíveis</relationshipLabel>
    <relationshipName>ParticipantesPerfiCompativeis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VN_BatchAtualizaPerfilCompativel.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: LK                          date: 02/12/2019
* 
* Name: VN_BatchAtualizaPerfilCompativel.cls
* 
* Batch para atualizar lista de perfis compatíveis no prêmio
*******************************************************************************/
global without sharing class VN_BatchAtualizaPerfilCompativel implements Database.Batchable<sObject>, Schedulable{
    Date fData;
    global void execute(SchedulableContext sc) {
        Database.executeBatch(this, 5);
    }

    global VN_BatchAtualizaPerfilCompativel() {
        fData = System.today().addDays(1);
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        //Seleciona leilões que começam amanhã
        return Database.getQueryLocator([SELECT Id, V_PapelYoubet__c, Iniciativa__c, 
                                        (SELECT V_Reward__r.V_PapelYoubet__c, V_Member__r.FieloPLT__Status__c,
                                        V_Member__r.V_PapelYoubet__c FROM ParticipantesPerfiCompativeis__r)   
                                        FROM FieloPLT__Reward__c 
                                        WHERE V_YoubetCompleto__c = true
                                        AND V_DataInicioYoubet__c =: fData]);
    }

    global void execute(Database.BatchableContext BC, List<FieloPLT__Reward__c> scope) {
        if ( scope == null || scope.isEmpty()) return;

        Set<String> lSetPapel = new Set<String>();
        Map<Id, Map<Id, VN_ParticipanteComPerfilCompativel__c>> lMapRewardParticipanteCompativel = new Map<Id, Map<Id, VN_ParticipanteComPerfilCompativel__c>>();
        List<FieloPLT__Reward__c> lstReward = new List<FieloPLT__Reward__c>();
        List<VN_ParticipanteComPerfilCompativel__c> lstParticipanteComPerfilCompativelToDelete = new List<VN_ParticipanteComPerfilCompativel__c>();
        List<VN_ParticipanteComPerfilCompativel__c> lstParticipanteComPerfilCompativelToUpsert = new List<VN_ParticipanteComPerfilCompativel__c>();
        
        // Para cada leilão, pega a lista de Participantes com Perfil Compatível e verifica se o Participante está ativo
        // e se o papel do Participante é igual ao papel do Leilão. Se o Participante não é mais elegível, adiciona o 
        // registro ParticipanteComPerfilCompativel numa lista para deletar; caso contrário adiciona num mapa com
        // Id do Leilão e mapa, Id do Member e ParticipanteComPerfilCompativel
        for(FieloPLT__Reward__c lReward : scope){
            if(lReward.V_PapelYoubet__c != null) {
                lSetPapel.add(lReward.V_PapelYoubet__c);
                lstReward.add(lReward);
                Map<Id, VN_ParticipanteComPerfilCompativel__c> lMapParticipanteComPerfilCompativel = new Map<Id, VN_ParticipanteComPerfilCompativel__c>();

                for(VN_ParticipanteComPerfilCompativel__c lParticipantePerfilCompativel : lReward.ParticipantesPerfiCompativeis__r){
                    if(lParticipantePerfilCompativel.V_Member__r.FieloPLT__Status__c != Label.V_StatusAtivoMember
                            || (lParticipantePerfilCompativel.V_Member__r.V_PapelYoubet__c != lParticipantePerfilCompativel.V_Reward__r.V_PapelYoubet__c)){
                        lstParticipanteComPerfilCompativelToDelete.add(lParticipantePerfilCompativel);
                    } else{
                      lMapParticipanteComPerfilCompativel.put(lParticipantePerfilCompativel.V_Member__c, lParticipantePerfilCompativel);  
                    }
                }
                if(!lMapParticipanteComPerfilCompativel.isEmpty())
                    lMapRewardParticipanteCompativel.put(lReward.Id, lMapParticipanteComPerfilCompativel);
            }
        }

        List<FieloPLT__Member__c> lstMember = [SELECT V_BetcoinsComp__c, FieloPLT__Points__c, V_PapelYoubet__c, V_Area__c, V_Lideranca__c, V_Cargo__c, V_Setor__c
                                FROM FieloPLT__Member__c WHERE V_PapelYoubet__c =: lSetPapel AND FieloPLT__Status__c =: Label.V_StatusAtivoMember];

        // Para cada Leilão, pega o mapa de Id de Participante e registro de ParticipanteComPerfilCompatviel,
        //Itera pela lista de Members, verifica se Papel é o mesmo do Leilão, caso sim, adiciona na lista para upsert.
        for(FieloPLT__Reward__c lReward : lstReward){
            
            Map<Id, VN_ParticipanteComPerfilCompativel__c> lMapParticipanteComPerfilCompativel = new Map<Id, VN_ParticipanteComPerfilCompativel__c>();
            
            if(!lMapRewardParticipanteCompativel.isEmpty() && lMapRewardParticipanteCompativel.containsKey(lReward.Id)){
                lMapParticipanteComPerfilCompativel = lMapRewardParticipanteCompativel.get(lReward.Id);
            }
            for(FieloPLT__Member__c lMember : lstMember){
                if(lReward.V_PapelYoubet__c == lMember.V_PapelYoubet__c){
                    Decimal lSaldoMember = lReward.Iniciativa__c == Label.V_IniciativaComplementar ? lMember.V_BetcoinsComp__c : lMember.FieloPLT__Points__c;
                    
                    VN_ParticipanteComPerfilCompativel__c lParticipantePerfilCompativel = new VN_ParticipanteComPerfilCompativel__c(
                        V_Member__c = lMember.Id,
                        V_Reward__c = lReward.Id,
                        V_Saldo__c = lSaldoMember,
                        V_Area__c = lMember.V_Area__c,
                        V_Lideranca__c = lMember.V_Lideranca__c,
                        V_Cargo__c = lMember.V_Cargo__c,
                        V_Setor__c = lMember.V_Setor__c.left(255)
                    );

                    if(lMapParticipanteComPerfilCompativel.containsKey(lMember.Id))
                        lParticipantePerfilCompativel.Id = lMapParticipanteComPerfilCompativel.get(lMember.Id).Id;
                    
                    lstParticipanteComPerfilCompativelToUpsert.add(lParticipantePerfilCompativel);
                }
            }
        }

        if(!lstParticipanteComPerfilCompativelToDelete.isEmpty())
            delete lstParticipanteComPerfilCompativelToDelete;
        
        if(!lstParticipanteComPerfilCompativelToUpsert.isEmpty())
            upsert lstParticipanteComPerfilCompativelToUpsert;
    }

    global void finish(Database.BatchableContext BC){}
}