force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program that the Member belongs to.</description>
    <inlineHelpText>The Program that the Member belongs to</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Program__c/FieloPLT__Program__c.object-meta.xml
<CustomObject>
    <description>Programs establish the general operation settings for your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/VN_GerenciadorMetaParticipanteAF__c.object-meta.xml
<CustomObject>
    <description>Gerenciador dos registros de metas dos participantes por Ano Fiscal.</description>
    <label>Gerenciador Meta Participante AF</label>
    <nameField>
        <displayFormat>GMAF-{000000}</displayFormat>
        <label>No. Gerenciador Ano Fiscal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gerenciador Metas Participantes AF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetasParticipantes__c/VN_MetasParticipantes__c.object-meta.xml
<CustomObject>
    <description>Cadastro de metas mês a mês do ano fiscal dos participantes.</description>
    <label>Meta do Participante - OLD</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes - OLD</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ProcessarMecanicasDecimoMesAF__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarMecanicasDecimoMesAF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</description>
    <inlineHelpText>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</inlineHelpText>
    <label>Processar Mecânicas - Mês 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ProcessarMecanicasDecimoPrimeiroAF__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarMecanicasDecimoPrimeiroAF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</description>
    <inlineHelpText>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</inlineHelpText>
    <label>Processar Mecânicas - Mês 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ProcessarMecanicasDecimoSegundoAF__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarMecanicasDecimoSegundoAF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</description>
    <inlineHelpText>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</inlineHelpText>
    <label>Processar Mecânicas - Mês 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ProcessarMecanicasNonoMesAF__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarMecanicasNonoMesAF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</description>
    <inlineHelpText>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</inlineHelpText>
    <label>Processar Mecânicas - Mês 12</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ProcessarMecanicasOitavoMesAF__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarMecanicasOitavoMesAF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</description>
    <inlineHelpText>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</inlineHelpText>
    <label>Processar Mecânicas - Mês 11</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ProcessarMecanicasPrimeiroMesAF__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarMecanicasPrimeiroMesAF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</description>
    <inlineHelpText>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</inlineHelpText>
    <label>Processar Mecânicas - Mês 4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ProcessarMecanicasQuartoMesAF__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarMecanicasQuartoMesAF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</description>
    <inlineHelpText>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</inlineHelpText>
    <label>Processar Mecânicas - Mês 7</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ProcessarMecanicasQuintoMesAF__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarMecanicasQuintoMesAF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</description>
    <inlineHelpText>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</inlineHelpText>
    <label>Processar Mecânicas - Mês 8</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ProcessarMecanicasSegundoMesAF__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarMecanicasSegundoMesAF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</description>
    <inlineHelpText>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</inlineHelpText>
    <label>Processar Mecânicas - Mês 5</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ProcessarMecanicasSetimoMesAF__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarMecanicasSetimoMesAF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</description>
    <inlineHelpText>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</inlineHelpText>
    <label>Processar Mecânicas - Mês 10</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ProcessarMecanicasSextoMesAF__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarMecanicasSextoMesAF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</description>
    <inlineHelpText>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</inlineHelpText>
    <label>Processar Mecânicas - Mês 9</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetasParticipantes__c/fields/V_ProcessarMecanicasTerceiroMesAF__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarMecanicasTerceiroMesAF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</description>
    <inlineHelpText>As mecânicas de atribuição de betcoins ou badges do respectivo mês serão executadas pela aplicação somente após o preenchimento desse campo para Verdadeiro.</inlineHelpText>
    <label>Processar Mecânicas - Mês 6</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_Resultado__c/VN_Resultado__c.object-meta.xml
<CustomObject>
    <description>Armazena as vendas mês a mês por ano fiscal.</description>
    <label>Resultado</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>No. Resultado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resultados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SX_MetasParticipantes_BeforeTest.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                date: 26/10/2018
*
* 
* Name: SX_MetasParticipantes_BeforeTest.cls
* 
* Classe de testes para a classe SX_MetasParticipantes_Before.cls
*******************************************************************************/
@isTest
public with sharing class SX_MetasParticipantes_BeforeTest {

	static testMethod void atualizarPersona() {

		FieloPLT__Program__c lProgram = SObjectForTest.getProgram('testProgramName');
 		insert lProgram;

 		FieloPLT__Member__c lMember = SObjectForTest.getMember(lProgram.Id);
        insert lMember;

        VN_GerenciadorMetaParticipanteAF__c lGerenciadorMetaParticipanteAF = SObjectForTest.getGerenciadorMetaParticipante();
        insert lGerenciadorMetaParticipanteAF;

        VN_MetasParticipantes__c lMeta = SObjectForTest.getMetas(lMember.Id, lGerenciadorMetaParticipanteAF.Id);
    	lMeta.V_ProcessarMecanicasPrimeiroMesAF__c = false;
		lMeta.V_ProcessarMecanicasSegundoMesAF__c = false;
		lMeta.V_ProcessarMecanicasTerceiroMesAF__c = false;
		lMeta.V_ProcessarMecanicasQuartoMesAF__c = false;
		lMeta.V_ProcessarMecanicasQuintoMesAF__c = false;
		lMeta.V_ProcessarMecanicasSextoMesAF__c = false;
		lMeta.V_ProcessarMecanicasSetimoMesAF__c = false;
		lMeta.V_ProcessarMecanicasOitavoMesAF__c = false;
		lMeta.V_ProcessarMecanicasNonoMesAF__c = false;
		lMeta.V_ProcessarMecanicasDecimoMesAF__c = false;
		lMeta.V_ProcessarMecanicasDecimoPrimeiroAF__c = false;
		lMeta.V_ProcessarMecanicasDecimoSegundoAF__c = false;
     	insert lMeta;

        //VN_Resultado__c lRes = SObjectForTest.getResultado(lMeta.Id, lGerenciadorMetaParticipanteAF.Name, lMember.Id);
        //insert lRes;

		Test.startTest();

			lMeta.V_ProcessarMecanicasPrimeiroMesAF__c = true;
			update lMeta;
			lMeta.V_ProcessarMecanicasSegundoMesAF__c = true;
			update lMeta;
			lMeta.V_ProcessarMecanicasTerceiroMesAF__c = true;
			update lMeta;
			lMeta.V_ProcessarMecanicasQuartoMesAF__c = true;
			update lMeta;
			lMeta.V_ProcessarMecanicasQuintoMesAF__c = true;
			update lMeta;
			lMeta.V_ProcessarMecanicasSextoMesAF__c = true;
			update lMeta;
			lMeta.V_ProcessarMecanicasSetimoMesAF__c = true;
			update lMeta;
			lMeta.V_ProcessarMecanicasOitavoMesAF__c = true;
			update lMeta;
			lMeta.V_ProcessarMecanicasNonoMesAF__c = true;
			update lMeta;
			lMeta.V_ProcessarMecanicasDecimoMesAF__c = true;
			update lMeta;
			lMeta.V_ProcessarMecanicasDecimoPrimeiroAF__c = true;
			update lMeta;
			lMeta.V_ProcessarMecanicasDecimoSegundoAF__c = true;
			update lMeta;
            
        Test.stopTest();
	}
}