force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program that the Member belongs to.</description>
    <inlineHelpText>The Program that the Member belongs to</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_RegistroParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_RegistroParticipante__c</fullName>
    <description>Registro exclusivo do participante na Serasa Experian. Não aceita duplicidade de registros.</description>
    <externalId>true</externalId>
    <inlineHelpText>Registro exclusivo do participante na Serasa Experian. Não aceita duplicidade de registros.</inlineHelpText>
    <label>Login</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FieloPLT__Program__c/FieloPLT__Program__c.object-meta.xml
<CustomObject>
    <description>Programs establish the general operation settings for your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/VN_GerenciadorMetaParticipanteAF__c.object-meta.xml
<CustomObject>
    <description>Gerenciador dos registros de metas dos participantes por Ano Fiscal.</description>
    <label>Gerenciador Meta Participante AF</label>
    <nameField>
        <displayFormat>GMAF-{000000}</displayFormat>
        <label>No. Gerenciador Ano Fiscal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gerenciador Metas Participantes AF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <description>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</description>
    <inlineHelpText>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</inlineHelpText>
    <label>Ano Fiscal</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_DataInicio__c.field-meta.xml
<CustomField>
    <fullName>V_DataInicio__c</fullName>
    <description>Data de início do ano fiscal.</description>
    <inlineHelpText>Data de início do ano fiscal.</inlineHelpText>
    <label>Data Início</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ano fiscal da Meta do participante do participante</description>
    <label>Gerenciador Meta Participante AF</label>
    <referenceTo>VN_GerenciadorMetaParticipanteAF__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Meta__c.field-meta.xml
<CustomField>
    <fullName>V_Meta__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Meta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualAM1Semestre__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAM1Semestre__c</fullName>
    <label>% AM - 1º Semestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualAM2Semestre__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAM2Semestre__c</fullName>
    <label>% AM - 2º Semestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualAM2Trimestre__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAM2Trimestre__c</fullName>
    <label>% AM - 2º Trimestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualAM3Trimestre__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAM3Trimestre__c</fullName>
    <label>% AM - 3º Trimestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentualAM4Trimestre__c.field-meta.xml
<CustomField>
    <fullName>V_PercentualAM4Trimestre__c</fullName>
    <label>% AM - 4º Trimestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_QtdMesesComMetaRes2Semestre__c.field-meta.xml
<CustomField>
    <fullName>V_QtdMesesComMetaRes2Semestre__c</fullName>
    <label>Qtd Meses com Meta/Res. - 2º Semestre</label>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Mes__c</field>
        <operation>equals</operation>
        <value>7, 8, 9, 10, 11, 12</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Meta__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>VN_Sumarizador__c.V_Valor__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>VN_Sumarizador__c.V_MetaDoParticipante__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ResultadoSE__c.field-meta.xml
<CustomField>
    <fullName>V_ResultadoSE__c</fullName>
    <label>Resultado SE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_SuperacaoH2__c.field-meta.xml
<CustomField>
    <fullName>V_SuperacaoH2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Superação H2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_SuperacaoQ4__c.field-meta.xml
<CustomField>
    <fullName>V_SuperacaoQ4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Superação Q4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_UltimoMesAtualizado__c.field-meta.xml
<CustomField>
    <fullName>V_UltimoMesAtualizado__c</fullName>
    <label>Último Mês Atualizado</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Valor__c.field-meta.xml
<CustomField>
    <fullName>V_Valor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/VN_Sumarizador__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por sumarizar as metas, resultados e ponderados das informações carregas ou atualizadas.</description>
    <label>Sumarizador</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Código do Sumarizador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sumarizadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_IDXAnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_IDXAnoFiscal__c</fullName>
    <label>IDX Ano Fiscal</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_IDXTrimestrePeriodo__c.field-meta.xml
<CustomField>
    <fullName>V_IDXTrimestrePeriodo__c</fullName>
    <formula>IF( V_IDXTrimestre__c =0,0,
   IF( V_IDXTrimestre__c =1,1,
      IF( V_IDXTrimestre__c = V_IDXTrimestreAnterior__c , V_IDXTrimestrePeriodoAnterior__c ,
         IF( V_Ponderou__c =FALSE,1 + V_IDXTrimestrePeriodoAnterior__c ,1 ))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IDX Trimestre Período</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Mes__c.field-meta.xml
<CustomField>
    <fullName>V_Mes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Faz referência ao mês corrente da meta</description>
    <label>Mês Meta</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Meta__c.field-meta.xml
<CustomField>
    <fullName>V_Meta__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Meta Mensal, sumarização da meta da carga por participante</description>
    <inlineHelpText>Faz referência a Meta mensal do Participante.</inlineHelpText>
    <label>Meta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_MetaYTDPeriodo__c.field-meta.xml
<CustomField>
    <fullName>V_MetaYTDPeriodo__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Meta YTD Período</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_MetaYTDTrimestre__c.field-meta.xml
<CustomField>
    <fullName>V_MetaYTDTrimestre__c</fullName>
    <formula>IF(AND( V_IDXTrimestre__c  != V_IDXTrimestreAnterior__c , V_IDXTrimestre__c &lt;=1), V_Meta__c ,
   IF( V_IDXTrimestre__c = V_IDXTrimestreAnterior__c , V_MetaYTDTrimestreAnterior__c ,
 V_MetaYTDTrimestreAnterior__c + V_Meta__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Meta YTD Trimestre</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_MetaYTDTrimestrePeriodo__c.field-meta.xml
<CustomField>
    <fullName>V_MetaYTDTrimestrePeriodo__c</fullName>
    <formula>IF( V_IDXTrimestre__c =0,0,
   IF( V_IDXTrimestre__c =1, V_MetaYTDTrimestre__c ,
      IF( V_IDXTrimestre__c = V_IDXTrimestreAnterior__c , V_MetaYTDTrimestrePeriodoAnterior__c ,
         IF( V_IDXTrimestrePeriodo__c =1, V_MetaYTDTrimestre__c - V_MetaYTDTrimestreAnterior__c , V_MetaYTDTrimestrePeriodoAnterior__c + V_Meta__c ))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Meta YTD Trimestre Período</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ProcessarCalculos__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarCalculos__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Ao ser assinalado esse campo, os workflows de cálculo do registro serão acionados.</description>
    <inlineHelpText>Ao ser assinalado esse campo, os workflows de cálculo do registro serão acionados.</inlineHelpText>
    <label>Processar Cálculos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ReferenciaMesAnterior__c.field-meta.xml
<CustomField>
    <fullName>V_ReferenciaMesAnterior__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que faz referência ao mês anterior do sumarizador.</description>
    <inlineHelpText>Faz referência ao registro do mês anterior no sumarizador.</inlineHelpText>
    <label>Referência ao Mês Anterior</label>
    <referenceTo>VN_Sumarizador__c</referenceTo>
    <relationshipName>VN_SumarizadoresDosObjetivos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ResultadoSE__c.field-meta.xml
<CustomField>
    <fullName>V_ResultadoSE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Resultado SE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Valor__c.field-meta.xml
<CustomField>
    <fullName>V_Valor__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Sumarizador que faz referência ao resultado atingido pelo participante</description>
    <inlineHelpText>Faz referência ao resultado atingido pelo participante</inlineHelpText>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ValorYTDTrimestrePeriodo__c.field-meta.xml
<CustomField>
    <fullName>V_ValorYTDTrimestrePeriodo__c</fullName>
    <formula>IF( V_IDXTrimestre__c =0,0,
   IF( V_IDXTrimestre__c =1, V_ValorYTDTrimestre__c ,
      IF( V_IDXTrimestre__c = V_IDXTrimestreAnterior__c , V_ValorYTDTrimestrePeriodoAnterior__c ,
         IF( V_IDXTrimestrePeriodo__c =1, V_ValorYTDTrimestre__c - V_ValorYTDTrimestreAnterior__c , V_ValorYTDTrimestrePeriodoAnterior__c + V_Valor__c ))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor YTD Trimestre Período</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SX_BatchAtualizaSuperacaoMetaTest.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: LK                          date: 02/12/2019
* 
* Name: SX_BatchAtualizaSuperacaoMetaTest.cls
* 
* Classe de teste para SX_BatchAtualizaSuperacaoMetaTest
*******************************************************************************/
@isTest
public with sharing class SX_BatchAtualizaSuperacaoMetaTest {
   @IsTest
    static void atualizarSuperacaoMes12(){

        VN_GerenciadorMetaParticipanteAF__c lGerenciadorMetaParticipanteAF = criarDados();

		Test.startTest();

            for(Integer mesProcessado = 1; mesProcessado < 13; mesProcessado++){
                SX_BatchProcessarCalculos batchProcessarCalculos = new SX_BatchProcessarCalculos(
            	lGerenciadorMetaParticipanteAF.V_AnoFiscal__c, mesProcessado);
                DataBase.executeBatch(batchProcessarCalculos);

                SX_BatchProcessarMecanica batchProcessarMecaninca = new SX_BatchProcessarMecanica(
            	lGerenciadorMetaParticipanteAF.V_AnoFiscal__c, mesProcessado);
                DataBase.executeBatch(batchProcessarMecaninca);
            }
        Test.stopTest();

        System.assertEquals(120, [SELECT Id FROM VN_Sumarizador__c WHERE V_ProcessarCalculos__c = true].size());
        System.assertEquals(10, [SELECT Id FROM VN_MetaParticipante__c WHERE V_UltimoMesAtualizado__c = 'Março'].size());
        System.assertEquals(1, [SELECT V_IDXTrimestrePeriodo__c FROM VN_Sumarizador__c WHERE V_Mes__c = 1 LIMIT 1].V_IDXTrimestrePeriodo__c);
        System.assertEquals(4037061.84, [SELECT V_MetaYTDTrimestre__c FROM VN_Sumarizador__c WHERE V_Mes__c = 1 LIMIT 1].V_MetaYTDTrimestre__c);
        System.assertEquals(4037061.84, [SELECT V_MetaYTDTrimestrePeriodo__c FROM VN_Sumarizador__c WHERE V_Mes__c = 1 LIMIT 1].V_MetaYTDTrimestrePeriodo__c);
        System.assertEquals(4478412.08, [SELECT V_ValorYTDTrimestrePeriodo__c FROM VN_Sumarizador__c WHERE V_Mes__c = 1 LIMIT 1].V_ValorYTDTrimestrePeriodo__c);
        System.assertEquals(110, [SELECT Id FROM VN_Sumarizador__c WHERE V_ReferenciaMesAnterior__c != null].size());
        System.assertEquals(6, [SELECT V_QtdMesesComMetaRes2Semestre__c FROM VN_MetaParticipante__c LIMIT 1].V_QtdMesesComMetaRes2Semestre__c);
        
        SX_BatchAtualizaSuperacaoMeta batchSuperacaoMeta = new SX_BatchAtualizaSuperacaoMeta();
        DataBase.executeBatch(batchSuperacaoMeta);
        
        //Este assert falha pois roda antes do Batch ter finalizado
        //System.assertEquals(10, [SELECT Id FROM VN_MetaParticipante__c WHERE V_SuperacaoQ4__c = true].size());
        //System.assertEquals(10, [SELECT Id FROM VN_MetaParticipante__c WHERE V_SuperacaoH2__c = true].size());
    }

    @IsTest
    static void atualizarSuperacao(){
        criarDados();
        List<VN_MetaParticipante__c> lstMetas = [SELECT V_PercentualAM2Trimestre__c, V_PercentualAM3Trimestre__c,
                V_PercentualAM4Trimestre__c, V_PercentualAM1Semestre__c, V_PercentualAM2Semestre__c FROM VN_MetaParticipante__c];
        for(VN_MetaParticipante__c lMeta : lstMetas){
            lMeta.V_PercentualAM2Trimestre__c = 110; 
            lMeta.V_PercentualAM3Trimestre__c = 110; 
            lMeta.V_PercentualAM4Trimestre__c = 110;
		    lMeta.V_PercentualAM1Semestre__c = 110; 
            lMeta.V_PercentualAM2Semestre__c = 110;
        }
        update lstMetas;

        Test.startTest();
            SX_BatchAtualizaSuperacaoMeta batchSuperacaoMeta = new SX_BatchAtualizaSuperacaoMeta();
            DataBase.executeBatch(batchSuperacaoMeta);
        Test.stopTest();

        System.assertEquals(10, [SELECT Id FROM VN_MetaParticipante__c WHERE V_SuperacaoQ4__c = true].size());
        System.assertEquals(10, [SELECT Id FROM VN_MetaParticipante__c WHERE V_SuperacaoH2__c = true].size());     
    }

    public static void criarSumarizador(VN_Sumarizador__c aSumarizador){
        aSumarizador.V_Valor__c = 4478412.08;
        aSumarizador.V_Meta__c = 4037061.84;
        aSumarizador.V_IDXAnoFiscal__c = 1;
        aSumarizador.V_MetaYTDPeriodo__c = 4037061.84;
        aSumarizador.V_ResultadoSE__c = 970697.95;
    }

    public static void criarSumarizadorZerado(VN_Sumarizador__c aSumarizador){
        aSumarizador.V_Valor__c = 0;
        aSumarizador.V_Meta__c = 0;
        aSumarizador.V_IDXAnoFiscal__c = 0;
        aSumarizador.V_MetaYTDPeriodo__c = 0;
        aSumarizador.V_ResultadoSE__c = 0;
    }
  
    public static VN_GerenciadorMetaParticipanteAF__c criarDados(){
        FieloPLT__Program__c lProgram = SObjectForTest.getProgram('testProgramName');
 		insert lProgram;

 		List<FieloPLT__Member__c> lstMember = SObjectForTest.getMemberList(lProgram.Id);
        lstMember[0].V_RegistroParticipante__c = 'SSK3473';
        insert lstMember;
        
        VN_GerenciadorMetaParticipanteAF__c lGerenciadorMetaParticipanteAF = SObjectForTest.getGerenciadorMetaParticipante();
        insert lGerenciadorMetaParticipanteAF;

		List<VN_MetaParticipante__c> lstMetas = SObjectForTest.getMetasNovaEstruturaLst(lstMember, lGerenciadorMetaParticipanteAF.Id, lGerenciadorMetaParticipanteAF.V_AnoFiscal__c);
        insert lstMetas;
		System.assertEquals(10, lstMetas.size());

		SX_BatchCriarMetas.gerarSumarizador(lstMetas, lGerenciadorMetaParticipanteAF.V_DataInicio__c);
        System.assertEquals(120, [SELECT Id FROM VN_Sumarizador__c].size());

        List<VN_Sumarizador__c> lstSumarizador = new List<VN_Sumarizador__c>();
        for(VN_Sumarizador__c lSumarizador : [SELECT V_Valor__c, V_Meta__c, V_IDXAnoFiscal__c, V_MetaYTDPeriodo__c, V_ResultadoSE__c
                    FROM VN_Sumarizador__c]){
            criarSumarizador(lSumarizador);
            lstSumarizador.add(lSumarizador); 
        }
        if(!lstSumarizador.isEmpty())
            update lstSumarizador;

        System.assertEquals(120, [SELECT Id FROM VN_Sumarizador__c].size());

        return lGerenciadorMetaParticipanteAF;
    }
}