force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Area__c.field-meta.xml
<CustomField>
    <fullName>V_Area__c</fullName>
    <description>Área do participante.</description>
    <inlineHelpText>Área do participante.</inlineHelpText>
    <label>Área</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VERTICAIS</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo atual do participante.</description>
    <inlineHelpText>Cargo atual do participante.</inlineHelpText>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COORDENADOR | GERENTE REGIONAL VIP</fullName>
            </value>
            <value>
                <fullName>DIRETOR</fullName>
            </value>
            <value>
                <fullName>GERENTE DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDER</fullName>
            </value>
            <value>
                <fullName>COORDENADOR II</fullName>
                <isActive>false</isActive>
                <label>COORDENADOR II</label>
            </value>
            <value>
                <fullName>GERENTE DE VENDAS</fullName>
                <isActive>false</isActive>
                <label>GERENTE DE VENDAS</label>
            </value>
            <value>
                <fullName>VICE-PRESIDENTE</fullName>
                <isActive>false</isActive>
                <label>VICE-PRESIDENTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Lideranca__c.field-meta.xml
<CustomField>
    <fullName>V_Lideranca__c</fullName>
    <description>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</description>
    <inlineHelpText>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</inlineHelpText>
    <label>Liderança</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>MULTI SECTOR</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
            <value>
                <fullName>VAREJO, CPG E PAGAMENTOS</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS</fullName>
            </value>
            <value>
                <fullName>SERASA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_LiderImediato__c.field-meta.xml
<CustomField>
    <fullName>V_LiderImediato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Líder imediato atual do participante.</description>
    <inlineHelpText>Líder imediato atual do participante.</inlineHelpText>
    <label>Líder Imediato</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Liderados Imediatos</relationshipLabel>
    <relationshipName>Lider_Imediato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_PapelElite__c.field-meta.xml
<CustomField>
    <fullName>V_PapelElite__c</fullName>
    <label>Papel Elite</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DIRETORES</fullName>
            </value>
            <value>
                <fullName>GERENTES DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDERES</fullName>
            </value>
            <value>
                <fullName>LÍDERES (COORDENADORES) E GERENTE REGIONAIS</fullName>
            </value>
            <value>
                <fullName>NÃO ELEGÍVEL</fullName>
                <default>true</default>
                <label>NÃO ELEGÍVEL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_ScoreElite__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreElite__c</fullName>
    <description>Score Elite do ano fiscal vigente.</description>
    <formula>V_MetasAnoFiscalVigenteNovo__r.V_ScoreElite__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Score Elite do ano fiscal vigente.</inlineHelpText>
    <label>Score Elite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/VN_GerenciadorMetaParticipanteAF__c.object-meta.xml
<CustomObject>
    <description>Gerenciador dos registros de metas dos participantes por Ano Fiscal.</description>
    <label>Gerenciador Meta Participante AF</label>
    <nameField>
        <displayFormat>GMAF-{000000}</displayFormat>
        <label>No. Gerenciador Ano Fiscal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gerenciador Metas Participantes AF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <description>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</description>
    <inlineHelpText>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</inlineHelpText>
    <label>Ano Fiscal</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sinaliza se o gerenciador é o que está em vigência.</description>
    <inlineHelpText>Sinaliza se o gerenciador é o que está em vigência.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ano fiscal da Meta do participante do participante</description>
    <label>Gerenciador Meta Participante AF</label>
    <referenceTo>VN_GerenciadorMetaParticipanteAF__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Nome__c.field-meta.xml
<CustomField>
    <fullName>V_Nome__c</fullName>
    <formula>V_Participante__r.V_NomeTratamento__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primeiro nome / Nome de Tratamento</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PapelElite__c.field-meta.xml
<CustomField>
    <fullName>V_PapelElite__c</fullName>
    <formula>TEXT(V_Participante__r.V_PapelElite__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Papel Elite</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Participante__c.field-meta.xml
<CustomField>
    <fullName>V_Participante__c</fullName>
    <description>Participante relacionado à meta.</description>
    <inlineHelpText>Participante relacionado à meta.</inlineHelpText>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ParticRankingElite__c.field-meta.xml
<CustomField>
    <fullName>V_ParticRankingElite__c</fullName>
    <formula>AND(TEXT( V_Participante__r.FieloPLT__Status__c ) = &apos;Active&apos;,
TEXT( V_Participante__r.V_NovoContratado__c) = &apos;Não&apos;,
NOT(CONTAINS( UPPER( V_Participante__r.Name), &apos;TESTE&apos;)),
(V_PapelElite__c &lt;&gt; &apos;NÃO ELEGÍVEL&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Participa Ranking Elite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ScoreElite__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreElite__c</fullName>
    <formula>V_ScoreAtingimentoFY__c + V_ScoreSuperacaoFY__c + V_ScoreSuperacaoQ1__c + V_ScorePotencialCarteira__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score Elite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <description>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</description>
    <formula>V_AnoFiscal__r.V_Vigente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SX_EliteTeamPerfomanceController.cls
public with sharing class SX_EliteTeamPerfomanceController {
	
	@AuraEnabled
    public static FieloPLT__Member__c getMember() {
        List<FieloPLT__Member__c> lMemberLst = [SELECT Id, V_PapelElite__c
								                FROM FieloPLT__Member__c
								                WHERE FieloPLT__User__c =: UserInfo.getUserId()];

	    return lMemberLst.isEmpty() ? null : lMemberLst[0];         
    }

	@AuraEnabled
	public static List<Map<String, String>> getPapel(String aIdMember) {

	    Map<String, Map<String, String>> lMapPapel = new Map<String, Map<String, String>>();

        Schema.DescribeFieldResult fieldResult = FieloPLT__Member__c.V_PapelElite__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
			if(pickListVal.getValue() == 'NÃO ELEGÍVEL') continue;
	        lMapPapel.put(pickListVal.getValue() , new Map<String, String>{'value' => pickListVal.getValue() , 'label' => pickListVal.getLabel() });
        } 

	    // for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
		// 	if(member.V_PapelElite__c == 'NÃO ELEGÍVEL') continue;
	    //     lMapPapel.put(member.V_PapelElite__c, new Map<String, String>{'value' => member.V_PapelElite__c, 'label' => member.V_PapelElite__c});
	    // }
	    return lMapPapel.values();
	}

    @AuraEnabled
	public static List<Map<String, String>> getArea(String aIdMember) {

	    Map<String, Map<String, String>> lMapArea = new Map<String, Map<String, String>>();
	    for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
	        lMapArea.put(member.V_Area__c, new Map<String, String>{'value' => member.V_Area__c, 'label' => member.V_Area__c});
	    }

	    system.debug('##lMapArea '+lMapArea);
	    return lMapArea.values();
	}
	@AuraEnabled
	public static List<Map<String, String>> getSubArea(String aIdMember) {

	    Map<String, Map<String, String>> lMapSubArea = new Map<String, Map<String, String>>();
	    for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
	        lMapSubArea.put(member.V_Lideranca__c, new Map<String, String>{'value' => member.V_Lideranca__c, 'label' => member.V_Lideranca__c});
	    }
	    system.debug('##lMapSubArea '+lMapSubArea);
	    return lMapSubArea.values();
	}

	@AuraEnabled
	public static List<Map<String, String>> getCargo(String aIdMember) {

	    Map<String, Map<String, String>> lMapCargo = new Map<String, Map<String, String>>();
	    for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
	    	if(member.Id == aIdMember) continue;
	        lMapCargo.put(member.V_Cargo__c, new Map<String, String>{'value' => member.V_Cargo__c, 'label' => member.V_Cargo__c});
	    }
	    system.debug('##lMapCargo '+lMapCargo);
	    return lMapCargo.values();
	}

	@AuraEnabled
    public static List<VN_MetaParticipante__c> getMetas(String aArea, String aLideranca, String aCargo, String aIdMember, String aPapel){

    	system.debug('##### ');

    	String lAnoFiscal = loadAnoFiscalVigente();
    	if(String.isEmpty(lAnoFiscal)) return null;

    	Set<Id> lSetMember = new Set<Id>();
        for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
        	lSetMember.add(member.Id);
        }

		List<VN_MetaParticipante__c> lLstMeta = loadMetas(aIdMember, lAnoFiscal, aArea, aLideranca, aCargo, lSetMember, aPapel);
		return lLstMeta;
	}

	@AuraEnabled
    public static List<Posicao> getRanking(String aIdMember, String aArea, String aLideranca, String aCargo, String aPapel) {

    	String lAnoFiscal = loadAnoFiscalVigente();
    	if(String.isEmpty(lAnoFiscal)) return null;

    	Set<Id> lSetMember = new Set<Id>();
        for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
        	lSetMember.add(member.Id);
        }

		Integer lTotalRanking = aPapel == 'DIRETORES' ? Integer.valueOf(Label.V_RankingDiretor)
								: aPapel == 'LÍDERES' ? Integer.valueOf(Label.V_RankingLider)
								: aPapel == 'GERENTES DE CONTAS' ? Integer.valueOf(Label.V_RankingGerenteDeContas)
								: Integer.valueOf(Label.V_RankingCoordenador_GerenteRegional); 

		Map<Integer, Integer> lMapRanking = new Map<Integer, Integer>();
		Map<Integer, Integer> lMapEquipe = new Map<Integer, Integer>();
		for(Integer i = lTotalRanking; i > 0; i--){
			lMapRanking.put(i, 0);
			lMapEquipe.put(i, 0);
		}

		List<VN_MetaParticipante__c> lLstMeta = loadMetas(aIdMember, lAnoFiscal, aArea, aLideranca, aCargo, null, aPapel);

        for(VN_MetaParticipante__c metas: lLstMeta){
        	Integer lScore = Integer.valueOf(metas.V_ScoreElite__c);

        	Integer lTotalMembers = lMapRanking.get(lScore);
        	if(lTotalMembers == null) continue;

        	lTotalMembers ++;
        	lMapRanking.put(lScore, lTotalMembers);

        	if(lSetMember.contains(metas.V_Participante__c)){
        		Integer lTotalEquipe = lMapEquipe.get(lScore);
        		if(lTotalEquipe == null) continue;
        		lTotalEquipe ++;
        		lMapEquipe.put(lScore, lTotalEquipe);
        	}
        }

        List<Posicao> lLstPos = new List<Posicao>();
        for(Integer lKey: lMapRanking.keySet()){

        	Integer lTotal = lMapRanking.get(lKey);
        	Integer lTotalEquipe = lMapEquipe.get(lKey);
        	if(lTotal == null || lTotalEquipe == null) continue;

        	Posicao lPos = new Posicao();
        	lPos.wScore = lKey;
        	lPos.wTotalMembers = lTotal;
        	lPos.wTotalEquipe = lTotalEquipe;

        	String lKeyStr = lKey < 10 ? '0'+String.valueOf(lKey) : String.valueOf(lKey);
        	lPos.wScoreStr = lKeyStr; 

        	lLstPos.add(lPos);
        }
	    return lLstPos;         
    } 

    private static List<VN_MetaParticipante__c> loadMetas(String aIdMember, String aAnoFiscal, String aArea, String aLideranca, String aCargo, Set<Id> aSetMember, String aPapel){

    	String lQuery = 'SELECT V_Participante__c, V_Nome__c, V_ScoreElite__c, V_PapelElite__c' +
					 	' FROM VN_MetaParticipante__c' +
					 	' WHERE Name = \''+ aAnoFiscal + '\''+
					 	' AND V_ParticRankingElite__c = true'+
					 	' AND V_PapelElite__c != \'NÃO ELEGÍVEL\'';

		if(aSetMember != null){
			lQuery += ' AND V_Participante__c = :aSetMember';
		}

		if(String.isNotEmpty(aPapel)){
			lQuery += ' AND V_Participante__r.V_PapelElite__c = \'' + aPapel + '\'';
		}

		if(String.isNotEmpty(aArea)){
			lQuery += ' AND V_Participante__r.V_Area__c = \'' + aArea + '\'';
		}

		if(String.isNotEmpty(aLideranca)){
			lQuery += ' AND V_Participante__r.V_Lideranca__c = \'' + aLideranca + '\'';
		}

		if(String.isNotEmpty(aCargo)){
			lQuery += ' AND V_Participante__r.V_Cargo__c = \'' + aCargo + '\'';
		}

		lQuery +=' ORDER BY V_ScoreElite__c DESC';

		List<VN_MetaParticipante__c> lLstMeta = database.query(lQuery);

		return lLstMeta;
    }

    private static String loadAnoFiscalVigente(){

    	List<VN_GerenciadorMetaParticipanteAF__c> lLstGeren = [SELECT V_AnoFiscal__c 
																FROM VN_GerenciadorMetaParticipanteAF__c
																WHERE V_Vigente__c = true];
		return lLstGeren.isEmpty() ? '' : lLstGeren[0].V_AnoFiscal__c;
    }  	

    public class Posicao{

    	@AuraEnabled public Integer wScore {get; set;}
    	@AuraEnabled public String wScoreStr {get; set;}
		@AuraEnabled public Integer wTotalMembers {get; set;}
		@AuraEnabled public Integer wTotalEquipe {get; set;}
    }

	private static List<FieloPLT__Member__c> loadMembers(String aIdMember){
		return [SELECT Id, V_Cargo__c, V_Area__c, V_Lideranca__c
	            FROM FieloPLT__Member__c
	            WHERE (V_LiderImediato__c  =: aIdMember
	             OR V_LiderImediato__r.V_LiderImediato__c =: aIdMember
	             OR V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__c =: aIdMember
	             OR V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__c =: aIdMember
	             OR V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__c =: aIdMember)
				AND V_PapelElite__c != 'NÃO ELEGÍVEL'];
	}
}