force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_PapelElite__c.field-meta.xml
<CustomField>
    <fullName>V_PapelElite__c</fullName>
    <label>Papel Elite</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DIRETORES</fullName>
            </value>
            <value>
                <fullName>GERENTES DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDERES</fullName>
            </value>
            <value>
                <fullName>LÍDERES (COORDENADORES) E GERENTE REGIONAIS</fullName>
            </value>
            <value>
                <fullName>NÃO ELEGÍVEL</fullName>
                <default>true</default>
                <label>NÃO ELEGÍVEL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VN_MemberServiceTest.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: LK                date: 22/09/2018
*
* 
* Name: VN_MemberServiceTest.cls
* 
* Classe de testes para a classe VN_MemberService.cls
*******************************************************************************/
@isTest
public with sharing class VN_MemberServiceTest {
	static testMethod void memberServices(){

		User lUser = SObjectForTest.loadUserLoggedMember();

		String lCargo = 'LÍDER';
		FieloPLT__Member__c lMember = [select Id from FieloPLT__Member__c where FieloPLT__User__c =: lUser.Id limit 1];
		lMember.V_PapelElite__c = VN_MemberService.PAPEL_COORDENADOR_GERENTE;
		update lMember;

		Test.startTest();
			System.runAs(lUser) {

				FieloPLT__Member__c lMember1 = VN_MemberService.getAllFieldsLoggedMember();
				VN_MemberService.getQuantidadeVagas(lMember.V_PapelElite__c);
				FieloPLT__Member__c lMember2 = VN_MemberService.loggedMember;
			}	
		Test.stopTest();
 	}
}