force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_BadgeEliteCongelado__c.field-meta.xml
<CustomField>
    <fullName>V_BadgeEliteCongelado__c</fullName>
    <description>Congela as badges do participante</description>
    <label>Badges Elite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_BadgeEngajamentoCongelado__c.field-meta.xml
<CustomField>
    <fullName>V_BadgeEngajamentoCongelado__c</fullName>
    <description>Congela as bafge engajamento do participante</description>
    <label>Badges Engajamento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_BadgeYouBetCongelado__c.field-meta.xml
<CustomField>
    <fullName>V_BadgeYouBetCongelado__c</fullName>
    <description>Congela as youbets do badge do participante</description>
    <label>Badges Youbet</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo atual do participante.</description>
    <inlineHelpText>Cargo atual do participante.</inlineHelpText>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COORDENADOR | GERENTE REGIONAL VIP</fullName>
            </value>
            <value>
                <fullName>DIRETOR</fullName>
            </value>
            <value>
                <fullName>GERENTE DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDER</fullName>
            </value>
            <value>
                <fullName>COORDENADOR II</fullName>
                <isActive>false</isActive>
                <label>COORDENADOR II</label>
            </value>
            <value>
                <fullName>GERENTE DE VENDAS</fullName>
                <isActive>false</isActive>
                <label>GERENTE DE VENDAS</label>
            </value>
            <value>
                <fullName>VICE-PRESIDENTE</fullName>
                <isActive>false</isActive>
                <label>VICE-PRESIDENTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_MetaScoreEliteAFCongelado__c.field-meta.xml
<CustomField>
    <fullName>V_MetaScoreEliteAFCongelado__c</fullName>
    <description>Pega o score atual do participante para congelar o site.</description>
    <label>Score Atual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_MetaScoreEliteAFProjetadoCongelado__c.field-meta.xml
<CustomField>
    <fullName>V_MetaScoreEliteAFProjetadoCongelado__c</fullName>
    <label>Score Projetado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_PosicaoRankingCongelado__c.field-meta.xml
<CustomField>
    <fullName>V_PosicaoRankingCongelado__c</fullName>
    <description>Grava a posição do ranking congelado</description>
    <label>Posição no Ranking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_ScoreElite__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreElite__c</fullName>
    <description>Score Elite do ano fiscal vigente.</description>
    <formula>V_MetasAnoFiscalVigenteNovo__r.V_ScoreElite__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Score Elite do ano fiscal vigente.</inlineHelpText>
    <label>Score Elite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ScoreElite__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreElite__c</fullName>
    <formula>V_ScoreAtingimentoFY__c + V_ScoreSuperacaoFY__c + V_ScoreSuperacaoQ1__c + V_ScorePotencialCarteira__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score Elite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ScoreEliteAFProjetado__c.field-meta.xml
<CustomField>
    <fullName>V_ScoreEliteAFProjetado__c</fullName>
    <formula>IF(

OR(
ISNULL(V_MetaAF__c), V_MetaAF__c = 0), 0,

IF(
V_TotalVendasYTD__c / V_MetaAF__c &lt;= 0.8, 1 ,

IF(
AND(
V_TotalVendasYTD__c / V_MetaAF__c &gt; 0.8, V_TotalVendasYTD__c / V_MetaAF__c &lt;= 0.9), 
2 ,

IF(
AND(
V_TotalVendasYTD__c / V_MetaAF__c &gt; 0.9, V_TotalVendasYTD__c / V_MetaAF__c &lt;= 0.95), 
3 ,

IF(
AND(
V_TotalVendasYTD__c / V_MetaAF__c &gt; 0.95, V_TotalVendasYTD__c / V_MetaAF__c &lt;= 1), 
4 ,

IF(
V_TotalVendasYTD__c / V_MetaAF__c &gt; 1, 5 , 0

))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score Elite AF - Projetado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SX_BatchSnapshotMember.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: PT                                                    date: 13/03/2019
* 
* Name: SX_BatchSnapshotMember.cls
* 
* Batch pra criar um snapshot com os dados do member
*******************************************************************************/
global with sharing class SX_BatchSnapshotMember implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT V_Cargo__c FROM FieloPLT__Member__c]);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<FieloPLT__Member__c> lstMeember = (List<FieloPLT__Member__c>) scope;
        for (FieloPLT__Member__c lMember : lstMeember) {
            VN_MetaParticipante__c lMeta = SX_HomeCardController.getMetaScore(lMember.Id);
           lMember.V_MetaScoreEliteAFCongelado__c = lMeta.V_ScoreElite__c; //Score Atual
           lMember.V_MetaScoreEliteAFProjetadoCongelado__c = lMeta.V_ScoreEliteAFProjetado__c; //Score Projetado
           lMember.V_PosicaoRankingCongelado__c = Decimal.valueOf(SX_HomeCardController.getRanking(lMember.Id, lMember.V_Cargo__c)); //Posição no ranking
           SX_HomeCardController.Badge lBadge = SX_HomeCardController.getNumBadges(lMember.Id);
           lMember.V_BadgeEliteCongelado__c = Decimal.valueOf(lBadge.wBadgeElite);
           lMember.V_BadgeYoubetCongelado__c = Decimal.valueOf(lBadge.wBadgeYoubet);
           lMember.V_BadgeEngajamentoCongelado__c = Decimal.valueOf(lBadge.wBadgeEngajamento);
        }
        update lstMeember;
    }
    
    global void finish(Database.BatchableContext BC) {

    }
}