force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Point__c/FieloPLT__Point__c.object-meta.xml
<CustomObject>
    <description>Points granted to Members as a result of performing a specific Action.</description>
    <label>Point</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Point</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Point__c/fields/FieloPLT__Member__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Member who obtained the Points.</description>
    <inlineHelpText>Member who obtained the Points.</inlineHelpText>
    <label>Member</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Points</relationshipLabel>
    <relationshipName>Points</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Point__c/fields/FieloPLT__PointType__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__PointType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Specific Point Type for a particular Point.</description>
    <inlineHelpText>Choose the specific Point Type for this Point.</inlineHelpText>
    <label>Point Type</label>
    <referenceTo>FieloPLT__PointType__c</referenceTo>
    <relationshipLabel>Points</relationshipLabel>
    <relationshipName>Points</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Point__c/fields/FieloPLT__TotalPoints__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__TotalPoints__c</fullName>
    <description>Total number of Points.</description>
    <inlineHelpText>Total number of Points.</inlineHelpText>
    <label>Total Points</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Point__c/fields/V_DataCriacao__c.field-meta.xml
<CustomField>
    <fullName>V_DataCriacao__c</fullName>
    <formula>DATEVALUE(CreatedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data de criação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Point__c/fields/V_DataTexto__c.field-meta.xml
<CustomField>
    <fullName>V_DataTexto__c</fullName>
    <formula>TEXT(DAY(V_DataCriacao__c))+&apos;/&apos;+ TEXT(MONTH(V_DataCriacao__c))+&apos;/&apos; + TEXT(YEAR(V_DataCriacao__c))</formula>
    <label>Data Texto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Point__c/fields/V_Origem__c.field-meta.xml
<CustomField>
    <fullName>V_Origem__c</fullName>
    <formula>IF( FieloPLT__Rule__c != null,  FieloPLT__Rule__r.Name, 

IF( FieloPLT__Transaction__c != null,  TEXT(FieloPLT__Transaction__r.FieloPLT__Type__c), 

IF( FieloPLT__Redemption__c != null,&apos;Lance&apos; , &apos;-&apos;)) )</formula>
    <label>Origem</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__PointType__c/FieloPLT__PointType__c.object-meta.xml
<CustomObject>
    <description>Point Types comprise different kind of  non-monetary Points. They enable to create exchange units based on distance, time, currency, etc. instead of regular numeral Points.</description>
    <label>Point Type</label>
    <nameField>
        <label>Point Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Point Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SX_ExtractController.cls
public with sharing class SX_ExtractController {


	@AuraEnabled
    public static FieloPLT__Member__c getMember() {
        List<FieloPLT__Member__c> lMemberLst = [SELECT Id
	                FROM FieloPLT__Member__c
	                WHERE FieloPLT__User__c =: UserInfo.getUserId()];

	    return lMemberLst.isEmpty() ? null : lMemberLst[0];         
    }

	@AuraEnabled
    public static List<FieloPLT__Point__c> getPoints(String aDe, String aAte, String aPalavraChave, String aTipo, String aIdMember){
    	String lTipo = aTipo == 'youbet-extra' ? 'Betcoins-Extra' : 'Betcoins';

    	String lQuery = 'SELECT Id, FieloPLT__TotalPoints__c, V_DataTexto__c, V_DataCriacao__c, V_Origem__c' +
					 	' FROM FieloPLT__Point__c' +
					 	' WHERE FieloPLT__Member__c = \'' + aIdMember + '\''+
					 	' AND FieloPLT__PointType__r.Name = \'' + lTipo + '\'';

		if(String.isNotEmpty(aPalavraChave)){
			lQuery += ' AND V_Origem__c like \'%' + aPalavraChave + '%\'';
		}
		if(aDe != null){
			Date lDe = date.valueOf(aDe);
			lQuery += ' AND V_DataCriacao__c >= :lDe';
		}
		if(aAte != null){
			Date lAte = date.valueOf(aAte);
			lQuery += ' AND V_DataCriacao__c <= :lAte';
		}

		lQuery += ' ORDER BY CreatedDate';
		
		List<FieloPLT__Point__c> lLstPoints = database.query(lQuery);
		return lLstPoints;
	}
}