force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_NomeTratamento__c.field-meta.xml
<CustomField>
    <fullName>V_NomeTratamento__c</fullName>
    <description>Nome que o participante prefere ser chamado. Campo a ser utilizado em comunicações com o participante. Esse campo será preenchido no momento do primeiro acesso do participante no portal.</description>
    <inlineHelpText>Nome que o participante prefere ser chamado. Campo a ser utilizado em comunicações com o participante. Esse campo será preenchido no momento do primeiro acesso do participante no portal.</inlineHelpText>
    <label>Nome de Tratamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_RegistroParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_RegistroParticipante__c</fullName>
    <description>Registro exclusivo do participante na Serasa Experian. Não aceita duplicidade de registros.</description>
    <externalId>true</externalId>
    <inlineHelpText>Registro exclusivo do participante na Serasa Experian. Não aceita duplicidade de registros.</inlineHelpText>
    <label>Login</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SX_ModalController.cls
public with sharing class SX_ModalController {

    @Future
    private static void updateNickname(Id aMemberId, String aNickname) {
    	FieloPLT__Member__c member = [SELECT V_NomeTratamento__c FROM FieloPLT__Member__c WHERE Id =: aMemberId];
    	member.V_NomeTratamento__c = aNickname;
    	update member;
    }

	@AuraEnabled
    public static String setNickname1(String numeroRegistro, String password, String nickname) {
    	List<FieloPLT__Member__c> lstMember = [SELECT FieloPLT__User__c, FieloPLT__User__r.Username
    			FROM FieloPLT__Member__c WHERE V_RegistroParticipante__c =: numeroRegistro];
    	if (lstMember.isEmpty()) return null;

    	FieloPLT__Member__c member = lstMember[0];
    	try {
    		System.setPassword(member.FieloPLT__User__c, password);
    		updateNickname(member.Id, nickname);
        	ApexPages.PageReference login = Site.login(member.FieloPLT__User__r.Username, password, '');
            aura.redirect(login);
            return null;
        }
        catch (Exception ex) {
            return ex.getMessage();            
        }
        return null;
    }

    @AuraEnabled
    public static String doForgotPassword(String numeroRegistro) {
    	List<FieloPLT__Member__c> lstMember = [SELECT FieloPLT__User__r.Username FROM FieloPLT__Member__c
    			WHERE V_RegistroParticipante__c =: numeroRegistro];
    	if (lstMember.isEmpty()) {
    		return 'Member not found';
    	}
    	Site.forgotPassword(lstMember[0].FieloPLT__User__r.Username);
    	return null;
    }

}