force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program that the Member belongs to.</description>
    <inlineHelpText>The Program that the Member belongs to</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Program__c/FieloPLT__Program__c.object-meta.xml
<CustomObject>
    <description>Programs establish the general operation settings for your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/V_HomeSSoController.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                                 date: 14/06/2018
* 
* Name: V_HomeSSoController.cls
* 
* Controller da página Home da Comunidade 
*******************************************************************************/
public class V_HomeSSoController {
    
    public String fMsg {get; set;}
    public FieloPLT__Member__c fMember {get; set;}
    
    public V_HomeSSoController() {

        fMsg = '';

        List<FieloPLT__Member__c> lstMember = [SELECT id, Name, FieloPLT__Program__c, FieloPLT__User__c
                                                FROM FieloPLT__Member__c 
                                                WHERE FieloPLT__User__c =: UserInfo.getUserId()];

        if(!lstMember.isEmpty()){
            fMember = lstMember[0];
        } else fMsg = 'Não encontramos member associado à Usuário com esse Id de Federação';
    }
}