force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Member&apos;s points.</description>
    <inlineHelpText>Member&apos;s points.</inlineHelpText>
    <label>Points</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Area__c.field-meta.xml
<CustomField>
    <fullName>V_Area__c</fullName>
    <description>Área do participante.</description>
    <inlineHelpText>Área do participante.</inlineHelpText>
    <label>Área</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VERTICAIS</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo atual do participante.</description>
    <inlineHelpText>Cargo atual do participante.</inlineHelpText>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COORDENADOR | GERENTE REGIONAL VIP</fullName>
            </value>
            <value>
                <fullName>DIRETOR</fullName>
            </value>
            <value>
                <fullName>GERENTE DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDER</fullName>
            </value>
            <value>
                <fullName>COORDENADOR II</fullName>
                <isActive>false</isActive>
                <label>COORDENADOR II</label>
            </value>
            <value>
                <fullName>GERENTE DE VENDAS</fullName>
                <isActive>false</isActive>
                <label>GERENTE DE VENDAS</label>
            </value>
            <value>
                <fullName>VICE-PRESIDENTE</fullName>
                <isActive>false</isActive>
                <label>VICE-PRESIDENTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Lideranca__c.field-meta.xml
<CustomField>
    <fullName>V_Lideranca__c</fullName>
    <description>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</description>
    <inlineHelpText>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</inlineHelpText>
    <label>Liderança</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>MULTI SECTOR</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
            <value>
                <fullName>VAREJO, CPG E PAGAMENTOS</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS</fullName>
            </value>
            <value>
                <fullName>SERASA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_LiderImediato__c.field-meta.xml
<CustomField>
    <fullName>V_LiderImediato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Líder imediato atual do participante.</description>
    <inlineHelpText>Líder imediato atual do participante.</inlineHelpText>
    <label>Líder Imediato</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Liderados Imediatos</relationshipLabel>
    <relationshipName>Lider_Imediato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/FieloPLT__Redemption__c.object-meta.xml
<CustomObject>
    <description>Redemptions are the orders generated by Members when they redeem their available Points for Rewards. Redemptions may include as many &quot;Redemptions Items&quot; as Rewards redeemed, as each Redemption Item represents a particular redeemed Reward.</description>
    <label>Redemption</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/FieloPLT__Member__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member who performed the Redemption.</description>
    <inlineHelpText>Choose the Member for this Redemption.</inlineHelpText>
    <label>Member</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Redemptions</relationshipLabel>
    <relationshipName>Redemptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Points needed to redeem the Reward.</description>
    <inlineHelpText>Points needed to redeem the Reward.</inlineHelpText>
    <label>Points</label>
    <summarizedField>FieloPLT__RedemptionItem__c.FieloPLT__Points__c</summarizedField>
    <summaryFilterItems>
        <field>FieloPLT__RedemptionItem__c.FieloPLT__Status__c</field>
        <operation>notEqual</operation>
        <value>Reverted</value>
    </summaryFilterItems>
    <summaryForeignKey>FieloPLT__RedemptionItem__c.FieloPLT__Redemption__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/V_BetcoinsInvestidos__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsInvestidos__c</fullName>
    <description>Betcoins consolidados em um único ponto (perene ou complementar). Campo a ser utilizado em front ends.</description>
    <formula>IF(
 FieloPLT__Points__c &gt; 0, FieloPLT__Points__c, V_BetcoinsComp__c 

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Betcoins consolidados em um único ponto (perene ou complementar). Campo a ser utilizado em front ends.</inlineHelpText>
    <label>Betcoins Investidos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/FieloPLT__RedemptionItem__c.object-meta.xml
<CustomObject>
    <description>Redemption Items represent each item which is part of a Redemption order.</description>
    <label>Redemption Item</label>
    <nameField>
        <displayFormat>RI-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemption Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Points needed to redeem the Redemption item</description>
    <inlineHelpText>Points needed to redeem the Redemption item.</inlineHelpText>
    <label>Points</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Redemption__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Redemption__c</fullName>
    <description>The Redemption order that the Member has made.</description>
    <inlineHelpText>The Redemption order that the Member has made.</inlineHelpText>
    <label>Redemption</label>
    <referenceTo>FieloPLT__Redemption__c</referenceTo>
    <relationshipLabel>Redemption Items</relationshipLabel>
    <relationshipName>RedemptionItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Reward__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Reward that the Member has redeemed.</description>
    <inlineHelpText>The Reward that the Member has redeemed.</inlineHelpText>
    <label>Reward</label>
    <referenceTo>FieloPLT__Reward__c</referenceTo>
    <relationshipLabel>Redemption Items</relationshipLabel>
    <relationshipName>RedemptionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/V_BetcoinsInvestidos__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsInvestidos__c</fullName>
    <description>Campo para consolidar o total de betcoins utilizados em perene ou complementar para ser usado em telas do Front End.</description>
    <formula>IF(

 FieloPLT__Points__c &gt; 0, FieloPLT__Points__c, V_BetcoinsComp__c 

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Campo para consolidar o total de betcoins utilizados em perene ou complementar para ser usado em telas do Front End.</inlineHelpText>
    <label>Betcoins Investidos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/V_NomePremio__c.field-meta.xml
<CustomField>
    <fullName>V_NomePremio__c</fullName>
    <formula>FieloPLT__Reward__r.Name</formula>
    <label>Nome do Prêmio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/V_Participante__c.field-meta.xml
<CustomField>
    <fullName>V_Participante__c</fullName>
    <description>Nome completo do participante envolvido no resgate/lance.</description>
    <formula>FieloPLT__Redemption__r.FieloPLT__Member__r.Name</formula>
    <inlineHelpText>Nome completo do participante envolvido no resgate/lance.</inlineHelpText>
    <label>Participante</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/FieloPLT__Reward__c.object-meta.xml
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Reward__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Number of Points needed to redeem a Reward.</description>
    <inlineHelpText>Enter the number of Points needed to redeem this Reward.</inlineHelpText>
    <label>Points</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/Iniciativa__c.field-meta.xml
<CustomField>
    <fullName>Iniciativa__c</fullName>
    <description>Tipos de iniciativa do incentivo.</description>
    <inlineHelpText>Tipos de iniciativa do incentivo.</inlineHelpText>
    <label>Iniciativa</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Youbet Perene</fullName>
            </value>
            <value>
                <fullName>Youbet Extra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SX_TeamPerformanceController.cls
public without sharing class SX_TeamPerformanceController {
	
	@AuraEnabled
    public static FieloPLT__Member__c getMember() {
        List<FieloPLT__Member__c> lMemberLst = [SELECT Id
								                FROM FieloPLT__Member__c
								                WHERE FieloPLT__User__c =: UserInfo.getUserId()];

	    return lMemberLst.isEmpty() ? null : lMemberLst[0];         
    }

    @AuraEnabled
	public static List<Map<String, String>> getArea(String aIdMember) {

	    Map<String, Map<String, String>> lMapArea = new Map<String, Map<String, String>>();
	    for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
	        lMapArea.put(member.V_Area__c, new Map<String, String>{'value' => member.V_Area__c, 'label' => member.V_Area__c});
	    }
	    return lMapArea.values();
	}
	@AuraEnabled
	public static List<Map<String, String>> getSubArea(String aIdMember) {

	    Map<String, Map<String, String>> lMapSubArea = new Map<String, Map<String, String>>();
	    for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
	        lMapSubArea.put(member.V_Lideranca__c, new Map<String, String>{'value' => member.V_Lideranca__c, 'label' => member.V_Lideranca__c});
	    }
	    return lMapSubArea.values();
	}

	@AuraEnabled
	public static List<Map<String, String>> getCargo(String aIdMember) {

	    Map<String, Map<String, String>> lMapCargo = new Map<String, Map<String, String>>();
	    for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
	    	if(member.Id == aIdMember) continue;
	        lMapCargo.put(member.V_Cargo__c, new Map<String, String>{'value' => member.V_Cargo__c, 'label' => member.V_Cargo__c});
	    }
	    return lMapCargo.values();
	}

    @AuraEnabled
    public static List<FieloPLT__RedemptionItem__c> getLances(String aArea, String aLideranca, String aCargo, String aPalavraChave, String aTipo, String aIdMember){

    	String lIniciativa = aTipo == 'youbet' ? Label.V_IniciativaPerene 
        						: aTipo == 'youbet-extra' ? Label.V_IniciativaComplementar
        						: Label.V_IniciativaElite;

        Set<Id> lSetMember = new Set<Id>();
        for (FieloPLT__Member__c member : loadMembers(aIdMember)) {
        	lSetMember.add(member.Id);
        }

    	String lQuery = 'SELECT Id, Name, V_DataTexto__c, FieloPLT__Points__c, V_NomePremio__c, V_BetcoinsInvestidos__c,' +
						' V_Participante__c, FieloPLT__Redemption__r.FieloPLT__Member__r.V_Area__c,' +
						' FieloPLT__Redemption__r.FieloPLT__Member__r.V_Lideranca__c, FieloPLT__Redemption__r.FieloPLT__Member__r.V_Cargo__c' +
					 	' FROM FieloPLT__RedemptionItem__c' +
					 	' WHERE FieloPLT__Redemption__r.FieloPLT__Member__c = :lSetMember'+
					 	' AND FieloPLT__Reward__r.Iniciativa__c = \''+ lIniciativa + '\'';

		if(String.isNotEmpty(aPalavraChave)){
			lQuery += ' AND (FieloPLT__Redemption__r.FieloPLT__Member__r.Name like \'%' + aPalavraChave + '%\'';
			lQuery += ' OR FieloPLT__Reward__r.Name like \'%' + aPalavraChave + '%\')';
		}

		if(String.isNotEmpty(aArea)){
			lQuery += ' AND FieloPLT__Redemption__r.FieloPLT__Member__r.V_Area__c = \'' + aArea + '\'';
		}

		if(String.isNotEmpty(aLideranca)){
			lQuery += ' AND FieloPLT__Redemption__r.FieloPLT__Member__r.V_Lideranca__c = \'' + aLideranca + '\'';
		}

		if(String.isNotEmpty(aCargo)){
			lQuery += ' AND FieloPLT__Redemption__r.FieloPLT__Member__r.V_Cargo__c = \'' + aCargo + '\'';
		}

		lQuery +=' ORDER BY CreatedDate';

		List<FieloPLT__RedemptionItem__c> lLstRdi = database.query(lQuery);
		return lLstRdi;
	}

	private static List<FieloPLT__Member__c> loadMembers(String aIdMember){
		return [SELECT Id, V_Cargo__c, V_Area__c, V_Lideranca__c
	            FROM FieloPLT__Member__c
	            WHERE (V_LiderImediato__c  =: aIdMember
	             OR V_LiderImediato__r.V_LiderImediato__c =: aIdMember
	             OR V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__c =: aIdMember
	             OR V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__c =: aIdMember
	             OR V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__r.V_LiderImediato__c =: aIdMember)];
	}
}