force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Member&apos;s points.</description>
    <inlineHelpText>Member&apos;s points.</inlineHelpText>
    <label>Points</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Area__c.field-meta.xml
<CustomField>
    <fullName>V_Area__c</fullName>
    <description>Área do participante.</description>
    <inlineHelpText>Área do participante.</inlineHelpText>
    <label>Área</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VERTICAIS</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Saldo de betcoins (extras) do participante.Saldo de pontos gerado pela iniciativa Youbet Complementar.</description>
    <inlineHelpText>Saldo de betcoins (extras) do participante.Saldo de pontos gerado pela iniciativa Youbet Complementar.</inlineHelpText>
    <label>Betcoins - Extra</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo atual do participante.</description>
    <inlineHelpText>Cargo atual do participante.</inlineHelpText>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COORDENADOR | GERENTE REGIONAL VIP</fullName>
            </value>
            <value>
                <fullName>DIRETOR</fullName>
            </value>
            <value>
                <fullName>GERENTE DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDER</fullName>
            </value>
            <value>
                <fullName>COORDENADOR II</fullName>
                <isActive>false</isActive>
                <label>COORDENADOR II</label>
            </value>
            <value>
                <fullName>GERENTE DE VENDAS</fullName>
                <isActive>false</isActive>
                <label>GERENTE DE VENDAS</label>
            </value>
            <value>
                <fullName>VICE-PRESIDENTE</fullName>
                <isActive>false</isActive>
                <label>VICE-PRESIDENTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Lideranca__c.field-meta.xml
<CustomField>
    <fullName>V_Lideranca__c</fullName>
    <description>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</description>
    <inlineHelpText>Liderança do participante. Campo dependente do campo &quot;Área&quot;.</inlineHelpText>
    <label>Liderança</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>V_Area__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>MULTI SECTOR</fullName>
            </value>
            <value>
                <fullName>REGIÕES</fullName>
            </value>
            <value>
                <fullName>MULTI CANAL</fullName>
            </value>
            <value>
                <fullName>VAREJO, CPG E PAGAMENTOS</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS</fullName>
            </value>
            <value>
                <fullName>SERASA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_PapelYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_PapelYoubet__c</fullName>
    <label>Papel Youbet</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GERENTES DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDERES</fullName>
            </value>
            <value>
                <fullName>LÍDERES (COORDENADORES) E GERENTE REGIONAIS</fullName>
            </value>
            <value>
                <fullName>NÃO ELEGÍVEL</fullName>
                <default>true</default>
                <label>NÃO ELEGÍVEL</label>
            </value>
            <value>
                <fullName>DIRETORES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_Setor__c.field-meta.xml
<CustomField>
    <fullName>V_Setor__c</fullName>
    <description>Campo dependente do campo &quot;Liderança&quot;.</description>
    <inlineHelpText>Campo dependente do campo &quot;Liderança&quot;.</inlineHelpText>
    <label>Setor</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>V_Lideranca__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BANCO DO BRASIL</fullName>
            </value>
            <value>
                <fullName>BRADESCO</fullName>
            </value>
            <value>
                <fullName>CAIXA ECONÔMICA</fullName>
            </value>
            <value>
                <fullName>ITAÚ</fullName>
            </value>
            <value>
                <fullName>SANTANDER</fullName>
            </value>
            <value>
                <fullName>BENS DURÁVEIS E SERVIÇOS</fullName>
            </value>
            <value>
                <fullName>COOPERATIVAS</fullName>
            </value>
            <value>
                <fullName>SETOR PÚBLICO</fullName>
            </value>
            <value>
                <fullName>TELECOM, MÍDIA E TECNOLOGIA</fullName>
            </value>
            <value>
                <fullName>UTILITIES</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS BR</fullName>
            </value>
            <value>
                <fullName>BANCOS E FINANCEIRAS SP</fullName>
            </value>
            <value>
                <fullName>SEGUROS</fullName>
            </value>
            <value>
                <fullName>CO, NO e NE</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>REGIÕES WINBACK</fullName>
            </value>
            <value>
                <fullName>RJ, MG e ES</fullName>
            </value>
            <value>
                <fullName>RS e SC</fullName>
            </value>
            <value>
                <fullName>SP I</fullName>
            </value>
            <value>
                <fullName>SP II</fullName>
            </value>
            <value>
                <fullName>SP INTERIOR</fullName>
            </value>
            <value>
                <fullName>CONVÊNIO SPC SERASA EXPERIAN</fullName>
            </value>
            <value>
                <fullName>DISTRIBUIDOR</fullName>
            </value>
            <value>
                <fullName>MULTICANAL WINBACK</fullName>
            </value>
            <value>
                <fullName>REMOTO</fullName>
            </value>
            <value>
                <fullName>VIP MG, CO e NO</fullName>
            </value>
            <value>
                <fullName>VIP RJ, ES e NE</fullName>
            </value>
            <value>
                <fullName>VIP SP I</fullName>
            </value>
            <value>
                <fullName>VIP SP II</fullName>
            </value>
            <value>
                <fullName>VIP SUL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/FieloPLT__Reward__c.object-meta.xml
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Reward__c/fields/FieloPLT__Points__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Points__c</fullName>
    <description>Number of Points needed to redeem a Reward.</description>
    <inlineHelpText>Enter the number of Points needed to redeem this Reward.</inlineHelpText>
    <label>Points</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/Iniciativa__c.field-meta.xml
<CustomField>
    <fullName>Iniciativa__c</fullName>
    <description>Tipos de iniciativa do incentivo.</description>
    <inlineHelpText>Tipos de iniciativa do incentivo.</inlineHelpText>
    <label>Iniciativa</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Youbet Perene</fullName>
            </value>
            <value>
                <fullName>Youbet Extra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_BetcoinsComp__c.field-meta.xml
<CustomField>
    <fullName>V_BetcoinsComp__c</fullName>
    <description>Preencha com valor igual a 1 para Youbet Extra. E com 0 (zero) quando for Youbet Perene.</description>
    <inlineHelpText>Preencha com valor igual a 1 para Youbet Extra. E com 0 (zero) quando for Youbet Perene</inlineHelpText>
    <label>Betcoins - Extra</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_PapelYoubet__c.field-meta.xml
<CustomField>
    <fullName>V_PapelYoubet__c</fullName>
    <label>Papel Youbet</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GERENTES DE CONTAS</fullName>
            </value>
            <value>
                <fullName>LÍDERES</fullName>
            </value>
            <value>
                <fullName>LÍDERES (COORDENADORES) E GERENTE REGIONAIS</fullName>
            </value>
            <value>
                <fullName>NÃO ELEGÍVEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/fields/V_YoubetCompleto__c.field-meta.xml
<CustomField>
    <fullName>V_YoubetCompleto__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se assinalado, indica que o cadastro do Youbet foi concluído e que a aplicação poderá relacionar os participantes que cumprirem os critérios desse Youbet para efeito de histórico e análises.</description>
    <inlineHelpText>Se assinalado, indica que o cadastro do Youbet foi concluído e que a aplicação poderá relacionar os participantes que cumprirem os critérios desse Youbet para efeito de histórico e análises.</inlineHelpText>
    <label>Youbet Completo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/VN_ParticipanteComPerfilCompativel__c.object-meta.xml
<CustomObject>
    <description>Lista relacionada do Youbet, participantes que possuem compatibilidade de cargo, área, liderança e elegibilidade no momento da criação do Youbet.</description>
    <label>Participante Com Perfil Compatível</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>No. Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes Com Perfis Compatíveis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Area__c.field-meta.xml
<CustomField>
    <fullName>V_Area__c</fullName>
    <description>Área do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Área do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Área</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Cargo__c.field-meta.xml
<CustomField>
    <fullName>V_Cargo__c</fullName>
    <description>Cargo do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Cargo do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Cargo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Lideranca__c.field-meta.xml
<CustomField>
    <fullName>V_Lideranca__c</fullName>
    <description>Liderança do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Liderança do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Liderança</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Reward__c.field-meta.xml
<CustomField>
    <fullName>V_Reward__c</fullName>
    <description>Youbet relacionado ao participante com compatibilidade de critérios (Cargo, Área, Liderança e Elegibilidade).</description>
    <inlineHelpText>Youbet relacionado ao participante com compatibilidade de critérios (Cargo, Área, Liderança e Elegibilidade).</inlineHelpText>
    <label>Youbet</label>
    <referenceTo>FieloPLT__Reward__c</referenceTo>
    <relationshipLabel>Participantes Com Perfis Compatíveis</relationshipLabel>
    <relationshipName>ParticipantesPerfiCompativeis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_ParticipanteComPerfilCompativel__c/fields/V_Setor__c.field-meta.xml
<CustomField>
    <fullName>V_Setor__c</fullName>
    <description>Setor do participante no momento de criação do Youbet.</description>
    <inlineHelpText>Setor do participante no momento de criação do Youbet.</inlineHelpText>
    <label>Setor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SX_Reward_After.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 13/09/2018
* 
* Name: SX_Reward_After.cls
* 
* Classe para disparar ações after em FieloPLT__Reward__c
*******************************************************************************/
public with sharing class SX_Reward_After { 

	public static void criarPerfilCompativel() {

		VN_TriggerCheck.assert();

		Map<Id, FieloPLT__Reward__c> lMapReward = new Map<Id, FieloPLT__Reward__c>();

		Map<Id, String> lMapPapel = new Map<Id, String>(); //add 17/07/19 #16429

		for(FieloPLT__Reward__c rew: (List<FieloPLT__Reward__c>) trigger.new ){ 

			if(VN_TriggerCheck.isChangedTo(rew,  FieloPLT__Reward__c.V_YoubetCompleto__c, true)){

				//add 17/07/19 #16429
				if(rew.V_PapelYoubet__c != null) 
					lMapPapel.put(rew.Id, rew.V_PapelYoubet__c);

				lMapReward.put(rew.Id, rew);
			}
		}
		if(lMapReward.isEmpty()) return;


		List<VN_ParticipanteComPerfilCompativel__c> lLstPerfilCompativel = new List<VN_ParticipanteComPerfilCompativel__c>();
		for(FieloPLT__Member__c member: [SELECT Id, Name, V_PapelYoubet__c, FieloPLT__Points__c, V_BetcoinsComp__c, V_Setor__c, V_Area__c, V_Lideranca__c, V_Cargo__c,
											(SELECT Id, V_Reward__r.Name, V_Reward__r.Iniciativa__c, V_Reward__r.V_DataHoraFimYoubet__c
												FROM V_RewardsCompativeis__r WHERE V_Reward__r.V_IsActive__c = true)
											FROM FieloPLT__Member__c
											WHERE V_PapelYoubet__c =: lMapPapel.values()
											AND FieloPLT__Status__c =: Label.V_StatusAtivoMember]){

			for(FieloPLT__Reward__c rew: lMapReward.values()){

				Boolean lJaTemAtivo = false;
				for( VN_ParticipanteComPerfilCompativel__c lRewComp: member.V_RewardsCompativeis__r){
					if((rew.Iniciativa__c == Label.V_IniciativaPerene && lRewComp.V_Reward__r.Iniciativa__c == Label.V_IniciativaPerene)
						|| (rew.Iniciativa__c == Label.V_IniciativaComplementar && lRewComp.V_Reward__r.Iniciativa__c == Label.V_IniciativaComplementar)){

						if(lRewComp.V_Reward__r.V_DataHoraFimYoubet__c > rew.V_DataHoraInicioYoubet__c)
							lJaTemAtivo = true;
					}
				}
				if(lJaTemAtivo) continue;


				//verifica se valores são compatíveis com do reward
				if(lMapPapel.containsKey(rew.Id) && lMapPapel.get(rew.Id) == member.V_PapelYoubet__c){

					Decimal lSaldoMember = rew.Iniciativa__c == Label.V_IniciativaComplementar ? member.V_BetcoinsComp__c : member.FieloPLT__Points__c;

					lLstPerfilCompativel.add(new VN_ParticipanteComPerfilCompativel__c(
							V_Member__c = member.Id,
							V_Reward__c = rew.Id,
							V_Saldo__c = lSaldoMember,
							V_Area__c = member.V_Area__c,
							V_Lideranca__c = member.V_Lideranca__c,
							V_Cargo__c = member.V_Cargo__c,
							V_Setor__c = member.V_Setor__c.left(255)
						)
					);
				}
			}
		}
		if(!lLstPerfilCompativel.isEmpty()) insert lLstPerfilCompativel;
	}

	public static void atualizarSaldoPerfilCompativel() {

		VN_TriggerCheck.assert();


		Map<Id, FieloPLT__Reward__c> lMapReward = new Map<Id, FieloPLT__Reward__c>();
		for(FieloPLT__Reward__c rew: ((List<FieloPLT__Reward__c>) trigger.new) ){ 

			if(VN_TriggerCheck.isChanged(rew, FieloPLT__Reward__c.V_LanceMinimo__c) && rew.V_YoubetCompleto__c
				&& rew.V_YoubetProcessado__c == null){
				lMapReward.put(rew.id, rew);
			}
		}
		if(lMapReward.isEmpty()) return;

		List<VN_ParticipanteComPerfilCompativel__c> lLstPerfilCompativel = new List<VN_ParticipanteComPerfilCompativel__c>();
		for(VN_ParticipanteComPerfilCompativel__c perfilCompativel: [SELECT Id, V_Reward__c, V_Saldo__c, V_SaldoInsuficiente__c, 
						V_Member__r.FieloPLT__Points__c, V_Member__r.V_BetcoinsComp__c
						FROM VN_ParticipanteComPerfilCompativel__c
						WHERE V_Reward__c =: lMapReward.keySet()]){

			if(!lMapReward.containsKey(perfilCompativel.V_Reward__c)) continue;

			FieloPLT__Reward__c lReward = lMapReward.get(perfilCompativel.V_Reward__c); 
			Decimal lSaldoMember = lReward.Iniciativa__c == Label.V_IniciativaComplementar 
									? perfilCompativel.V_Member__r.V_BetcoinsComp__c 
									: perfilCompativel.V_Member__r.FieloPLT__Points__c;

			perfilCompativel.V_Saldo__c = lSaldoMember;
			perfilCompativel.V_SaldoInsuficiente__c = lReward.V_LanceMinimo__c != null && lReward.V_LanceMinimo__c > lSaldoMember ? true : false;
			
			lLstPerfilCompativel.add(perfilCompativel);
		}
		if(!lLstPerfilCompativel.isEmpty()) update lLstPerfilCompativel;
	}

	public static void excluirPerfilCompativel() {

		VN_TriggerCheck.assert();

		List<VN_ParticipanteComPerfilCompativel__c> lLstPerfilCompativel = new List<VN_ParticipanteComPerfilCompativel__c>();
		for(FieloPLT__Reward__c rew: [SELECT Id, V_YoubetCompleto__c, (SELECT Id FROM ParticipantesPerfiCompativeis__r)
										FROM FieloPLT__Reward__c
										WHERE Id =: (List<FieloPLT__Reward__c>) trigger.new]){ 

			if(VN_TriggerCheck.isChangedTo(rew, FieloPLT__Reward__c.V_YoubetCompleto__c, false)){

				for(VN_ParticipanteComPerfilCompativel__c perfilCompativel: rew.ParticipantesPerfiCompativeis__r){
					lLstPerfilCompativel.add(perfilCompativel);
				}
			}
		}
		if(!lLstPerfilCompativel.isEmpty()) delete lLstPerfilCompativel;
	}

    public static void atualizaFinalizadoPerfilCompativel(){
        VN_TriggerCheck.assert();

		Set<Id> lRewardIdSet = new Set<Id>();
		for(FieloPLT__Reward__c rew : (List<FieloPLT__Reward__c>)Trigger.new ){ 
			if(VN_TriggerCheck.isChanged(rew, FieloPLT__Reward__c.V_NomeVencedor__c)){
				lRewardIdSet.add(rew.id);
			}
		}
		if(lRewardIdSet.isEmpty()) return;

        List<VN_ParticipanteComPerfilCompativel__c> lLstPerfilCompativelToUpdate = new List<VN_ParticipanteComPerfilCompativel__c>();
		for(VN_ParticipanteComPerfilCompativel__c perfilCompativel: [SELECT V_Finalizado__c, V_Reward__r.V_ParticipanteUltimoLance__c, V_Member__c
                FROM VN_ParticipanteComPerfilCompativel__c
                WHERE V_Reward__c =: lRewardIdSet
                AND V_Finalizado__c = false
                ]){
            if(perfilCompativel.V_Reward__r != null && perfilCompativel.V_Member__c != null
                    && perfilCompativel.V_Reward__r.V_ParticipanteUltimoLance__c != null
                    && perfilCompativel.V_Member__c == perfilCompativel.V_Reward__r.V_ParticipanteUltimoLance__c) continue;
            perfilCompativel.V_Finalizado__c = true;
            lLstPerfilCompativelToUpdate.add(perfilCompativel);
        }

        if(!lLstPerfilCompativelToUpdate.isEmpty()) update lLstPerfilCompativelToUpdate;
    }
}