force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program that the Member belongs to.</description>
    <inlineHelpText>The Program that the Member belongs to</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_CodigoCarteira__c.field-meta.xml
<CustomField>
    <fullName>V_CodigoCarteira__c</fullName>
    <description>Código de carteira atual do participante.</description>
    <externalId>true</externalId>
    <inlineHelpText>Código de carteira atual do participante.</inlineHelpText>
    <label>Código Carteira</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FieloPLT__Program__c/FieloPLT__Program__c.object-meta.xml
<CustomObject>
    <description>Programs establish the general operation settings for your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_CargasDadosTemp__c/VN_CargasDadosTemp__c.object-meta.xml
<CustomObject>
    <description>Utilizado para receber as cargas de dados temporária das integrações com o Fielo.</description>
    <label>Carga de Dados Temp</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>No. Carga Dados</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargas de Dados Temp</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <description>Ano fiscal relacionado ao registro da carga de dados.</description>
    <inlineHelpText>Ano fiscal relacionado ao registro da carga de dados.</inlineHelpText>
    <label>Ano Fiscal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_Mes__c.field-meta.xml
<CustomField>
    <fullName>V_Mes__c</fullName>
    <label>Mês</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_CargasDadosTemp__c/fields/V_Meta__c.field-meta.xml
<CustomField>
    <fullName>V_Meta__c</fullName>
    <label>Meta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/VN_GerenciadorMetaParticipanteAF__c.object-meta.xml
<CustomObject>
    <description>Gerenciador dos registros de metas dos participantes por Ano Fiscal.</description>
    <label>Gerenciador Meta Participante AF</label>
    <nameField>
        <displayFormat>GMAF-{000000}</displayFormat>
        <label>No. Gerenciador Ano Fiscal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gerenciador Metas Participantes AF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <description>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</description>
    <inlineHelpText>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</inlineHelpText>
    <label>Ano Fiscal</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_DataInicio__c.field-meta.xml
<CustomField>
    <fullName>V_DataInicio__c</fullName>
    <description>Data de início do ano fiscal.</description>
    <inlineHelpText>Data de início do ano fiscal.</inlineHelpText>
    <label>Data Início</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ano fiscal da Meta do participante do participante</description>
    <label>Gerenciador Meta Participante AF</label>
    <referenceTo>VN_GerenciadorMetaParticipanteAF__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Meta__c.field-meta.xml
<CustomField>
    <fullName>V_Meta__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Meta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_ResultadoSE__c.field-meta.xml
<CustomField>
    <fullName>V_ResultadoSE__c</fullName>
    <label>Resultado SE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Valor__c.field-meta.xml
<CustomField>
    <fullName>V_Valor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_ResumoCargasDadosTemp__c/VN_ResumoCargasDadosTemp__c.object-meta.xml
<CustomObject>
    <description>Carga de dados temporária das integrações com o Fielo.</description>
    <label>Resumo Carga de Dados Temp</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>No. Resumo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resumos Cargas de Dados Temp</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_Sumarizador__c/VN_Sumarizador__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por sumarizar as metas, resultados e ponderados das informações carregas ou atualizadas.</description>
    <label>Sumarizador</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Código do Sumarizador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sumarizadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_Sumarizador__c/fields/Participante__c.field-meta.xml
<CustomField>
    <fullName>Participante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relacionamento entre o participante e o sumarizador para poder gerar a pontuação</description>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Sumarizadores</relationshipLabel>
    <relationshipName>Sumarizadores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Mes__c.field-meta.xml
<CustomField>
    <fullName>V_Mes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Faz referência ao mês corrente da meta</description>
    <label>Mês Meta</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Meta__c.field-meta.xml
<CustomField>
    <fullName>V_Meta__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Meta Mensal, sumarização da meta da carga por participante</description>
    <inlineHelpText>Faz referência a Meta mensal do Participante.</inlineHelpText>
    <label>Meta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ProcessarCalculos__c.field-meta.xml
<CustomField>
    <fullName>V_ProcessarCalculos__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Ao ser assinalado esse campo, os workflows de cálculo do registro serão acionados.</description>
    <inlineHelpText>Ao ser assinalado esse campo, os workflows de cálculo do registro serão acionados.</inlineHelpText>
    <label>Processar Cálculos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_ResultadoSE__c.field-meta.xml
<CustomField>
    <fullName>V_ResultadoSE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Resultado SE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VN_Sumarizador__c/fields/V_Valor__c.field-meta.xml
<CustomField>
    <fullName>V_Valor__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Sumarizador que faz referência ao resultado atingido pelo participante</description>
    <inlineHelpText>Faz referência ao resultado atingido pelo participante</inlineHelpText>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/VN_CargaDadosTempHandlerTest.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: PV                                                date: 23/07/2019
* 
* Name: VN_CargaDadosTempHandlerTest.cls
* 
* Classe de teste da VN_CargaDadosTempHandler.cls
*******************************************************************************/
@isTest
public with sharing class VN_CargaDadosTempHandlerTest {
    
    @isTest
    public static void executeTest(){
        // Criar participantes, gerenciador de meta, meta, sumarizador, preencher sumarizador
        FieloPLT__Program__c lProgram = SObjectForTest.getProgram('testProgramName');
 		insert lProgram;

 		List<FieloPLT__Member__c> lstMember = SObjectForTest.getMemberList(lProgram.Id);
        insert lstMember;

        VN_GerenciadorMetaParticipanteAF__c lGerenciadorMetaParticipanteAF = SObjectForTest.getGerenciadorMetaParticipante();
        insert lGerenciadorMetaParticipanteAF;

        List<VN_MetaParticipante__c> lstMetas = SObjectForTest.getMetasNovaEstruturaLst(lstMember, lGerenciadorMetaParticipanteAF.Id, lGerenciadorMetaParticipanteAF.V_AnoFiscal__c);
		insert lstMetas;
		System.assertEquals(10, lstMetas.size());

		SX_BatchCriarMetas.gerarSumarizador(lstMetas, lGerenciadorMetaParticipanteAF.V_DataInicio__c);

        List<VN_Sumarizador__c> lstSumarizador = new List<VN_Sumarizador__c>();
        lstSumarizador = [SELECT V_ProcessarCalculos__c
                    FROM VN_Sumarizador__c WHERE V_Mes__c = 1];

        for(VN_Sumarizador__c lSumarizador : lstSumarizador) {
            lSumarizador.V_ProcessarCalculos__c = true;          
        }
        update lstSumarizador;

        System.Test.startTest();
        FieloPLT__Member__c lMemberTest1 = lstMember[0];
        FieloPLT__Member__c lMemberTest2 = lstMember[1];

        VN_ResumoCargasDadosTemp__c lResumoCarga = SObjectForTest.getResumoCargaDadosTemp();
        insert lResumoCarga;

        List<VN_CargasDadosTemp__c> lCargaDadosLst = SObjectForTest.getCargaDadosTempList(
                lResumoCarga.Id, lMemberTest1.V_CodigoCarteira__c, lMemberTest2.V_CodigoCarteira__c);
        insert lCargaDadosLst;

        VN_CargasDadosTemp__c lCargaDadosUpdate = lCargaDadosLst[0];
        lCargaDadosUpdate.V_Meta__c = '2';
        update lCargaDadosUpdate;

        System.Test.stopTest();

        System.assertEquals(2, [SELECT Id FROM VN_Sumarizador__c WHERE V_Meta__c != 0].size());

        VN_Sumarizador__c lSumarizador1 = [SELECT V_Meta__c, V_Valor__c, V_ResultadoSE__c FROM VN_Sumarizador__c
                WHERE Participante__c = :lMemberTest1.Id AND V_Mes__c = 1 LIMIT 1];
        System.assertEquals(56, lSumarizador1.V_Meta__c);
        System.assertEquals(110, lSumarizador1.V_Valor__c);
        System.assertEquals(165, lSumarizador1.V_ResultadoSE__c);

        VN_Sumarizador__c lSumarizador2 = [SELECT V_Meta__c, V_Valor__c, V_ResultadoSE__c FROM VN_Sumarizador__c
                WHERE Participante__c = :lMemberTest2.Id AND V_Mes__c = 1 LIMIT 1];
        System.assertEquals(56, lSumarizador2.V_Meta__c);
        System.assertEquals(110, lSumarizador2.V_Valor__c);
        System.assertEquals(165, lSumarizador2.V_ResultadoSE__c);
    }
}