force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_IDAnoFiscalVigente__c.field-meta.xml
<CustomField>
    <fullName>V_IDAnoFiscalVigente__c</fullName>
    <description>Id do registro de metas do ano fiscal vigente. Utilizado em Process Builder.</description>
    <formula>V_MetasAnoFiscalVigenteNovo__r.Id</formula>
    <inlineHelpText>Id do registro de metas do ano fiscal vigente.</inlineHelpText>
    <label>ID Ano Fiscal Vigente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/FieloPLT__Redemption__c.object-meta.xml
<CustomObject>
    <description>Redemptions are the orders generated by Members when they redeem their available Points for Rewards. Redemptions may include as many &quot;Redemptions Items&quot; as Rewards redeemed, as each Redemption Item represents a particular redeemed Reward.</description>
    <label>Redemption</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/FieloPLT__Member__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member who performed the Redemption.</description>
    <inlineHelpText>Choose the Member for this Redemption.</inlineHelpText>
    <label>Member</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Redemptions</relationshipLabel>
    <relationshipName>Redemptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Redemption__c/fields/V_MetaParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_MetaParticipante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ano Fiscal</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipLabel>Resgates/Lances</relationshipLabel>
    <relationshipName>Resgates_Lances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SX_Redemption_Before.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 01/02/2019
* 
* Name: SX_Redemption_Before.cls
* 
* Classe para disparar ações before em FieloPLT__Redemption__c
*
* Ações:
* 1 - associa meta fiscal no resgate
*******************************************************************************/
public with sharing class SX_Redemption_Before {

	public static void execute() {

		VN_TriggerCheck.assert();

		List<FieloPLT__Redemption__c> lTriggerNew = (List<FieloPLT__Redemption__c>) trigger.new;

		Set<Id> lSetMember = new Set<Id>();
		for(FieloPLT__Redemption__c redemption: lTriggerNew){
			lSetMember.add(redemption.FieloPLT__Member__c);
		}

		/*********************  *********************/

		Map<Id, FieloPLT__Member__c> lMapMember = new Map<Id, FieloPLT__Member__c>();
		if(!lSetMember.isEmpty()){
			lMapMember = new Map<Id, FieloPLT__Member__c>([SELECT Id, V_IDAnoFiscalVigente__c FROM FieloPLT__Member__c 
				WHERE Id =:lSetMember AND V_IDAnoFiscalVigente__c != null]);
		}

		/*********************  *********************/

		for(FieloPLT__Redemption__c redemption: lTriggerNew){

			//associa meta fiscal
			if(lMapMember.containsKey(redemption.FieloPLT__Member__c)){
				redemption.V_MetaParticipante__c = lMapMember.get(redemption.FieloPLT__Member__c).V_IDAnoFiscalVigente__c;
			}
		}	
	}
}