force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Email__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Email__c</fullName>
    <description>Member&apos;s email address</description>
    <inlineHelpText>Enter the Member&apos;s email address.</inlineHelpText>
    <label>E-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Program__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program that the Member belongs to.</description>
    <inlineHelpText>The Program that the Member belongs to</inlineHelpText>
    <label>Program</label>
    <referenceTo>FieloPLT__Program__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Program__c/FieloPLT__Program__c.object-meta.xml
<CustomObject>
    <description>Programs establish the general operation settings for your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SX_Member_BeforeTest.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: LK                date: 24/09/2018
*
* 
* Name: SX_Member_BeforeTest.cls
* 
* Classe de testes para a classe SX_Member_Before.cls
*******************************************************************************/
@isTest
public with sharing class SX_Member_BeforeTest {
	static testMethod void SX_Member_BeforeTest() {

		FieloPLT__Program__c lProgram = SObjectForTest.getProgram('programName'); 
		insert lProgram;

		//SObjectForTest.setPublicSettings();

		FieloPLT__Member__c lMember = SObjectForTest.getMember(lProgram.Id);
		lMember.FieloPLT__User__c = null;
		

 		Test.startTest();
 		insert lMember;

		Profile lPerfil = SObjectForTest.getProfile('Fielo Partner Community');
                                
        Account lAccount = SObjectForTest.getAccount();
        insert lAccount;
        
        Contact lContact = SObjectForTest.getContact();
        lContact.AccountId = lAccount.Id;
        insert lContact;
        
        User lUser = SObjectForTest.getUser(lPerfil.Id);
        lUser.ContactId = lContact.Id;
        insert lUser;

		lMember.FieloPLT__Email__c = 'teste@teste.com';
		lMember.FieloPLT__User__c = lUser.Id;
 		update lMember;
 		Test.stopTest();
	}
}