force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__User__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member&apos;s User.</description>
    <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_FirstAccess__c.field-meta.xml
<CustomField>
    <fullName>V_FirstAccess__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Utilizado para validar se é o primeiro acesso do member, para validar se, durante o primeiro login, devemos solicitar o nome de tratamento.</description>
    <label>Primeiro Acesso</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_NomeTratamento__c.field-meta.xml
<CustomField>
    <fullName>V_NomeTratamento__c</fullName>
    <description>Nome que o participante prefere ser chamado. Campo a ser utilizado em comunicações com o participante. Esse campo será preenchido no momento do primeiro acesso do participante no portal.</description>
    <inlineHelpText>Nome que o participante prefere ser chamado. Campo a ser utilizado em comunicações com o participante. Esse campo será preenchido no momento do primeiro acesso do participante no portal.</inlineHelpText>
    <label>Nome de Tratamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SX_ChangePasswordController.cls
public without sharing class SX_ChangePasswordController {

    public boolean fFirstAccess {get;set;}
    public FieloPLT__Member__c fMember {get; set;}

    public String fErrorMsg {get; set;}

    public String fPassword {get; set;}
    public String fConfirmPassword {get; set;}

    public SX_ChangePasswordController() {
        fFirstAccess = true;
        List<FieloPLT__Member__c> lstMember = [SELECT FieloPLT__User__c, FieloPLT__User__r.Username,
                V_FirstAccess__c, V_NomeTratamento__c FROM FieloPLT__Member__c
                WHERE FieloPLT__User__c =: UserInfo.getUserId()];
        if (lstMember.isEmpty()) return;
        fMember = lstMember[0];
        fFirstAccess = fMember.V_FirstAccess__c;
    }

    public PageReference doChangePassword() {

        if (fFirstAccess && String.isEmpty(fMember.V_NomeTratamento__c)) {
            fErrorMsg = 'Informe como deseja ser tratado';
            return null;
        }

        if(String.isEmpty(fPassword) || String.isEmpty(fConfirmPassword) ){
            fErrorMsg = 'O preenchimento dos campos é obrigatório';
            return null;
        }

        Integer lTamanhoMinimo = Integer.valueOf(Label.V_ComprimentoMinimoSenha); // configurado na política de senha
        if(fPassword.length() < lTamanhoMinimo){
            fErrorMsg = 'A senha deve conter no mínimo '+Label.V_ComprimentoMinimoSenha+ ' caracteres';
            return null;
        }

        if (fPassword != fConfirmPassword) {
            fErrorMsg = 'Senhas não conferem';
            return null;
        }

        try {

            System.setPassword(fMember.FieloPLT__User__c, fPassword);
            ApexPages.PageReference login = Site.login(fMember.FieloPLT__User__r.Username, fPassword, '');

            if(login != null && fMember.V_FirstAccess__c) {
                updateNickname(fMember.Id, fMember.V_NomeTratamento__c);
            }
            return login;
        }
        catch (Exception ex) {

            String lError = ex.getMessage();
            if(lError.contains('Your password must have a mix of letters and numbers')){
                fErrorMsg = 'A senha deve conter letras e números'; 
            } else if(lError.contains('Your Password cannot equal or contain your user name')){
                fErrorMsg = 'A senha não pode ser igual ou conter seu e-mail cadastrado'; 
            } 
            else {
                fErrorMsg = ex.getMessage(); 
            }    
        }
        return null;
    }

    @Future
    private static void updateNickname(Id aMemberId, String aNickname) {
        FieloPLT__Member__c member = new FieloPLT__Member__c(Id = aMemberId, V_NomeTratamento__c = aNickname,
                V_FirstAccess__c = false);
        update member;
    }
}