force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_LiderImediato__c.field-meta.xml
<CustomField>
    <fullName>V_LiderImediato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Líder imediato atual do participante.</description>
    <inlineHelpText>Líder imediato atual do participante.</inlineHelpText>
    <label>Líder Imediato</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Liderados Imediatos</relationshipLabel>
    <relationshipName>Lider_Imediato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_MetasAnoFiscalVigenteNovo__c.field-meta.xml
<CustomField>
    <fullName>V_MetasAnoFiscalVigenteNovo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Exibe a identificação do ano fiscal vigente do participante.</description>
    <inlineHelpText>Exibe a identificação do ano fiscal vigente do participante.</inlineHelpText>
    <label>Metas do Ano Fiscal Vigente</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipLabel>Participantes</relationshipLabel>
    <relationshipName>Participantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/VN_GerenciadorMetaParticipanteAF__c.object-meta.xml
<CustomObject>
    <description>Gerenciador dos registros de metas dos participantes por Ano Fiscal.</description>
    <label>Gerenciador Meta Participante AF</label>
    <nameField>
        <displayFormat>GMAF-{000000}</displayFormat>
        <label>No. Gerenciador Ano Fiscal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gerenciador Metas Participantes AF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <description>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</description>
    <inlineHelpText>Registrar a nomenclatura do ano fiscal desejado. Exemplo: AF19</inlineHelpText>
    <label>Ano Fiscal</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VN_GerenciadorMetaParticipanteAF__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sinaliza se o gerenciador é o que está em vigência.</description>
    <inlineHelpText>Sinaliza se o gerenciador é o que está em vigência.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/VN_MetaParticipante__c.object-meta.xml
<CustomObject>
    <description>Armazena as informações principais por participante.</description>
    <label>Meta do Participante</label>
    <nameField>
        <label>Ano Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas dos Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_AMYTD__c.field-meta.xml
<CustomField>
    <fullName>V_AMYTD__c</fullName>
    <description>Campo preenchido via workflow &apos;Atualiza % AM YTD na Meta&apos; que ao marcar o sumarizador como processar mecânicas, o valor do campo % AM YTD no sumarizador é copiado para este campo.</description>
    <label>% AM YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_AnoFiscal__c.field-meta.xml
<CustomField>
    <fullName>V_AnoFiscal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ano fiscal da Meta do participante do participante</description>
    <label>Gerenciador Meta Participante AF</label>
    <referenceTo>VN_GerenciadorMetaParticipanteAF__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Participante__c.field-meta.xml
<CustomField>
    <fullName>V_Participante__c</fullName>
    <description>Participante relacionado à meta.</description>
    <inlineHelpText>Participante relacionado à meta.</inlineHelpText>
    <label>Participante</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Metas dos Participantes</relationshipLabel>
    <relationshipName>VN_MetasParticipantes1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_PercentialAtingimentoEquipe__c.field-meta.xml
<CustomField>
    <fullName>V_PercentialAtingimentoEquipe__c</fullName>
    <label>% Atingimento da Equipe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VN_MetaParticipante__c/fields/V_Vigente__c.field-meta.xml
<CustomField>
    <fullName>V_Vigente__c</fullName>
    <description>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</description>
    <formula>V_AnoFiscal__r.V_Vigente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Exibe se o registro de metas do participante por ano fiscal é o vigente ou não.</inlineHelpText>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SX_BatchAtualizarPercentualMetaEquipe.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: FM                           date: 18/10/2019
* 
* Name: SX_BatchAtualizarPercentualMetaEquipe.cls
* 
* Batch para criar e metas nos Members
*******************************************************************************/
global class SX_BatchAtualizarPercentualMetaEquipe implements Database.Batchable<sObject>, Database.Stateful, Schedulable {

    global String fSetAnoFiscal;

    global void execute(SchedulableContext sc) {
        Database.executeBatch(this, 30);
    }
    
    global SX_BatchAtualizarPercentualMetaEquipe() {

        if(SX_Utils.batchIsProcessing('SX_BatchAtualizarPercentualMetaEquipe')) return;
        List <VN_GerenciadorMetaParticipanteAF__c> lAnoFiscalVigente = [SELECT V_AnoFiscal__c FROM VN_GerenciadorMetaParticipanteAF__c WHERE V_Vigente__c = true];
        fSetAnoFiscal = lAnoFiscalVigente[0].V_AnoFiscal__c;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

		return Database.getQueryLocator([SELECT V_LiderImediato__c FROM FieloPLT__Member__c
										WHERE V_LiderImediato__c != null AND V_MetasAnoFiscalVigenteNovo__r.Name =: fSetAnoFiscal]);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {

    	if ( scope == null || scope.isEmpty()) return;
        List<FieloPLT__Member__c> lListMember = ( List<FieloPLT__Member__c> ) scope;
        Set<Id> lSetMember = new Set<Id>();
        for(FieloPLT__Member__c member: lListMember){
            if(!lSetMember.contains(member.V_LiderImediato__c))
                lSetMember.add(member.V_LiderImediato__c);
        }

        List<VN_MetaParticipante__c> lLstMetaToUpdate = new List<VN_MetaParticipante__c>();
        Map<Id, List<VN_MetaParticipante__c>> lMapMemberMeta = new Map<Id, List<VN_MetaParticipante__c>>();


        for(VN_MetaParticipante__c lMeta: [ SELECT Id, V_AMYTD__c, V_PercentialAtingimentoEquipe__c, V_Participante__r.V_LiderImediato__c
                                             FROM VN_MetaParticipante__c WHERE V_Participante__r.V_LiderImediato__c =: lSetMember AND Name =: fSetAnoFiscal]){
            if(!lMapMemberMeta.containsKey(lMeta.V_Participante__r.V_LiderImediato__c))
                lMapMemberMeta.put(lMeta.V_Participante__r.V_LiderImediato__c, new List<VN_MetaParticipante__c>());
            lMapMemberMeta.get(lMeta.V_Participante__r.V_LiderImediato__c).add(lMeta);
        }

        for(Id lMember : lSetMember){
            Decimal amytd = 0;
            Decimal percentualAtingimentoEquipe;
            Decimal tamanhoEquipe;

            if(lMapMemberMeta.containsKey(lMember)){
                List<VN_MetaParticipante__c> lMemberMeta =  lMapMemberMeta.get(lMember);
                tamanhoEquipe = lMemberMeta.size();
                for(VN_MetaParticipante__c meta : lMemberMeta){
                    if(meta.V_AMYTD__c > = 100) amytd ++;
                }

                percentualAtingimentoEquipe = 100 / tamanhoEquipe;
                percentualAtingimentoEquipe = percentualAtingimentoEquipe * amytd;

                for(VN_MetaParticipante__c metaAtualizar: lMemberMeta){
                    metaAtualizar.V_PercentialAtingimentoEquipe__c = percentualAtingimentoEquipe;
                    lLstMetaToUpdate.add(metaAtualizar);
                }

                if (!lLstMetaToUpdate.isEmpty()) update lLstMetaToUpdate;
            }
        }
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}