force-app/main/default/objects/FieloPLT__Member__c/FieloPLT__Member__c.object-meta.xml
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Member__c/fields/V_MetasAnoFiscalVigenteNovo__c.field-meta.xml
<CustomField>
    <fullName>V_MetasAnoFiscalVigenteNovo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Exibe a identificação do ano fiscal vigente do participante.</description>
    <inlineHelpText>Exibe a identificação do ano fiscal vigente do participante.</inlineHelpText>
    <label>Metas do Ano Fiscal Vigente</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipLabel>Participantes</relationshipLabel>
    <relationshipName>Participantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Transaction__c/FieloPLT__Transaction__c.object-meta.xml
<CustomObject>
    <description>Transactions are the result of performing specific activities, which in exchange grant Points, Badges or Rewards to Members.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__Transaction__c/fields/FieloPLT__Member__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>It shows the Member who generated the Transaction.</description>
    <inlineHelpText>Enter the Member who generated the Transaction.</inlineHelpText>
    <label>Member</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Transaction__c/fields/V_MetaDoParticipante__c.field-meta.xml
<CustomField>
    <fullName>V_MetaDoParticipante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nova estrutura - Relaciona o registro de ano fiscal do objeto Meta do Participante à transação que gerou pontos.</description>
    <inlineHelpText>Relaciona o registro de ano fiscal do objeto Meta do Participante à transação que gerou pontos.</inlineHelpText>
    <label>Meta do Participante</label>
    <referenceTo>VN_MetaParticipante__c</referenceTo>
    <relationshipLabel>Transações</relationshipLabel>
    <relationshipName>Transa_es</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SX_Transaction_Before.cls
/*******************************************************************************
*                          Copyright (C) 2019 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 01/02/2019
* 
* Name: SX_Transaction_Before.cls
* 
* Classe para disparar ações before em FieloPLT__Transaction__c
*
* Ações:
* 1 - associa meta fiscal na transação
*******************************************************************************/
public with sharing class SX_Transaction_Before {

	public static void execute() {

		VN_TriggerCheck.assert();

		List<FieloPLT__Transaction__c> lTriggerNew = (List<FieloPLT__Transaction__c>) trigger.new;

		Set<Id> lSetMember = new Set<Id>();
		for(FieloPLT__Transaction__c trans: lTriggerNew){
			lSetMember.add(trans.FieloPLT__Member__c);
		}

		/*********************  *********************/

		Map<Id, FieloPLT__Member__c> lMapMember = new Map<Id, FieloPLT__Member__c>();
		if(!lSetMember.isEmpty()){
			lMapMember = new Map<Id, FieloPLT__Member__c>([SELECT Id, V_MetasAnoFiscalVigenteNovo__c FROM FieloPLT__Member__c 
				WHERE Id =:lSetMember AND V_MetasAnoFiscalVigenteNovo__c != null]);
		}

		/*********************  *********************/

		for(FieloPLT__Transaction__c trans: lTriggerNew){

			//associa meta fiscal
			if(lMapMember.containsKey(trans.FieloPLT__Member__c)){
				trans.V_MetaDoParticipante__c = lMapMember.get(trans.FieloPLT__Member__c).V_MetasAnoFiscalVigenteNovo__c;
			}
		}	
	}
}