force-app/main/default/objects/FieloPLT__RedemptionItem__c/FieloPLT__RedemptionItem__c.object-meta.xml
<CustomObject>
    <description>Redemption Items represent each item which is part of a Redemption order.</description>
    <label>Redemption Item</label>
    <nameField>
        <displayFormat>RI-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemption Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/FieloPLT__Reward__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Reward that the Member has redeemed.</description>
    <inlineHelpText>The Reward that the Member has redeemed.</inlineHelpText>
    <label>Reward</label>
    <referenceTo>FieloPLT__Reward__c</referenceTo>
    <relationshipLabel>Redemption Items</relationshipLabel>
    <relationshipName>RedemptionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieloPLT__RedemptionItem__c/fields/V_LanceGanhador__c.field-meta.xml
<CustomField>
    <fullName>V_LanceGanhador__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo indica o lance do leilão ganhador (maior quantidade de pontos). Será atualizado por batch após o término da vigência do leilão.</description>
    <inlineHelpText>Campo indica o lance do leilão ganhador (maior quantidade de pontos). Será atualizado por batch após o término da vigência do leilão.</inlineHelpText>
    <label>Lance Ganhador</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Reward__c/FieloPLT__Reward__c.object-meta.xml
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SX_RedemptionItem_Before.cls
/*******************************************************************************
*                          Copyright (C) 2018 ValueNET
* ------------------------------------------------------------------------------
* Author: FFV                          date: 13/09/2018
* 
* Name: SX_RedemptionItem_Before.cls
* 
* Classe para disparar ações before em FieloPLT__RedemptionItem__c
*******************************************************************************/
public with sharing class SX_RedemptionItem_Before {
	

	public static void verificarUnicoLanceGanhador() {

		VN_TriggerCheck.assert();

		List<FieloPLT__RedemptionItem__c> lLstRdi = new List<FieloPLT__RedemptionItem__c>();
		Set<Id> lSetReward = new Set<Id>();
		for(FieloPLT__RedemptionItem__c rdi: (List<FieloPLT__RedemptionItem__c>) trigger.new){

			if(VN_TriggerCheck.isChangedTo(rdi, FieloPLT__RedemptionItem__c.V_LanceGanhador__c, true)){

				lSetReward.add(rdi.FieloPLT__Reward__c);
				lLstRdi.add(rdi);
			}
		}
		if(lLstRdi.isEmpty()) return;

		Map<Id, FieloPLT__Reward__c> lMapReward = 
	  		new Map<Id, FieloPLT__Reward__c>([SELECT Id, (SELECT Id FROM FieloPLT__RedemptionItems__r WHERE V_LanceGanhador__c = true AND Id !=: lLstRdi)
		  										FROM FieloPLT__Reward__c
		  										WHERE Id =: lSetReward]);

	  	for(FieloPLT__RedemptionItem__c rdi: lLstRdi){

	  		FieloPLT__Reward__c lReward = lMapReward.get(rdi.FieloPLT__Reward__c);
	  		if(lReward == null) continue;

	  		if(lReward.FieloPLT__RedemptionItems__r.size() > 0){
	  			rdi.addError('Não é possível atualizar o lance ganhador desse Youbet por já haver lance ganhador assinalado. Por favor, verificar.');
	  		}
	  	}
	}
}